CREATE TABLE Customer (
CustomerID SERIAL PRIMARY KEY NOT NULL,
FirstName VARCHAR(50) NOT NULL,
LastName VARCHAR(50) NOT NULL,
Email VARCHAR(100) NOT NULL,
Phone VARCHAR(20) UNIQUE NOT NULL,
Address TEXT NOT NULL,
);

CREATE TABLE Product (
ProductID SERIAL PRIMARY KEY NOT NULL,
NameProduct VARCHAR(100) NOT NULL,
DescriptionProduct TEXT,
Price DECIMAL(10,2) NOT NULL,
Stock INT NOT NULL,
);

CREATE TABLE Store (
StoreID SERIAL PRIMARY KEY NOT NULL,
NameStore VARCHAR(100) NOT NULL,
AddressStore TEXT NOT NULL,
);

CREATE TABLE Employee (
EmployeeID SERIAL PRIMARY KEY NOT NULL,
FirstName VARCHAR(50) NOT NULL,
LastName VARCHAR(50) NOT NULL,
Position VARCHAR(50) NOT NULL,
);

CREATE TABLE Payment (
PaymentID SERIAL PRIMARY KEY NOT NULL,
PaymentMethod VARCHAR(50) NOT NULL,
);

CREATE TABLE Delivery (
DeliveryID SERIAL PRIMARY KEY NOT NULL,
DeliveryMethod VARCHAR(50) NOT NULL,
DeliveryPrice DECIMAL(10,2) NOT NULL,
);

CREATE TABLE Date (
DateID SERIAL PRIMARY KEY NOT NULL,
DateTime TIMESTAMP NOT NULL,
);

CREATE TABLE Order (
OrderID SERIAL PRIMARY KEY NOT NULL,
CustomerID INT NOT NULL,
ProductID INT NOT NULL,
StoreID INT NOT NULL,
EmployeeID INT NOT NULL,
PaymentID INT NOT NULL,
DeliveryID INT NOT NULL,
DateID INT NOT NULL,
TotalAmountOrder DECIMAL(12,2) NOT NULL,
CONSTRAINT fk_Order_Customer FOREIGN KEY (CustomerID) REFERENCES Customer(CustomerID),
CONSTRAINT fk_Order_Product FOREIGN KEY (ProductID) REFERENCES Product(ProductID),
CONSTRAINT fk_Order_Store FOREIGN KEY (StoreID) REFERENCES Store(StoreID),
CONSTRAINT fk_Order_Employee FOREIGN KEY (EmployeeID) REFERENCES Employee(EmployeeID),
CONSTRAINT fk_Order_Payment FOREIGN KEY (PaymentID) REFERENCES Payment(PaymentID),
CONSTRAINT fk_Order_Delivery FOREIGN KEY (DeliveryID) REFERENCES Delivery(DeliveryID),
CONSTRAINT fk_Order_Date FOREIGN KEY (DateID) REFERENCES Date(DateID),
);

