INSERT INTO product (name_product, description_product, price,stock,product_size,product_category,brand,inventory_status,sales_type)
VALUES
('TimHuGrapes','Sweet, ripe oranges',8,86,'Large','Vegetables','Sunkist','In Stock','Retail'),
('VangXauGrapes','Mixed berries',9,41,'Small','Dairy','Sunkist','Out of Stock','Retail'),
('MongMoXauApples','Mixed berries',6,59,'Medium','Seafood','Dole','Pre-Order','Retail'),
('HeheXauOranges','Fresh, juicy apples',5,90,'Large','Meat','Driscolls','Pre-Order','Retail'),
('MongMoDepOranges','Mixed berries',3,17,'Large','Fruits','HEB','Out of Stock','Direct to Consumer'),
('HeheDepGrapes','Mixed berries',5,59,'Small','Seafood','Chiquita','Pre-Order','Wholesale'),
('DoXauApples','Mixed berries',2,87,'Small','Seafood','Chiquita','In Stock','Wholesale'),
('HeheXauBananas','Fresh, juicy apples',7,67,'Small','Vegetables','Dole','Pre-Order','Wholesale'),
('VangXanhBerries','Sweet, ripe oranges',3,73,'Large','Fruits','Driscolls','In Stock','Direct to Consumer'),
('VangHuOranges','Fresh, juicy apples',10,65,'Large','Vegetables','Chiquita','Out of Stock','Retail'),
('TimSachApples','Fresh, juicy apples',10,37,'Small','Fruits','Sunkist','Pre-Order','Wholesale'),
('HeheNgonApples','Mixed berries',3,73,'Medium','Dairy','Driscolls','Out of Stock','Retail'),
('MongMoXauApples','Mixed berries',1,46,'Large','Dairy','Chiquita','Out of Stock','Retail'),
('HeheDepBerries','Tasty bananas',5,42,'Small','Vegetables','Sunkist','Out of Stock','Retail'),
('HihiXauApples','Delicious grapes',9,53,'Small','Seafood','Driscolls','In Stock','Retail'),
('HaHaXanhGrapes','Fresh, juicy apples',1,58,'Medium','Dairy','Sunkist','Pre-Order','Direct to Consumer'),
('HaHaXauApples','Sweet, ripe oranges',9,48,'Large','Meat','HEB','In Stock','Direct to Consumer'),
('MongMoChinBerries','Sweet, ripe oranges',2,71,'Large','Vegetables','Driscolls','Pre-Order','Wholesale'),
('DoThuiBerries','Mixed berries',1,24,'Medium','Meat','HEB','In Stock','Wholesale'),
('HeheXanhOranges','Delicious grapes',2,84,'Small','Dairy','Sunkist','Pre-Order','Wholesale'),
('HaHaDepOranges','Fresh, juicy apples',9,55,'Large','Vegetables','Sunkist','Out of Stock','Wholesale'),
('HihiDepBerries','Tasty bananas',6,21,'Small','Fruits','Chiquita','Pre-Order','Wholesale'),
('HihiThuiBananas','Sweet, ripe oranges',7,80,'Small','Seafood','Dole','In Stock','Wholesale'),
('HeheXauBananas','Fresh, juicy apples',4,23,'Medium','Vegetables','Driscolls','In Stock','Retail'),
('HihiChinOranges','Fresh, juicy apples',4,84,'Small','Meat','Sunkist','In Stock','Retail'),
('MongMoXauOranges','Sweet, ripe oranges',10,42,'Large','Seafood','Driscolls','Pre-Order','Retail'),
('VangDepBananas','Tasty bananas',3,70,'Small','Fruits','HEB','Pre-Order','Direct to Consumer'),
('DoDepGrapes','Fresh, juicy apples',6,100,'Small','Vegetables','HEB','In Stock','Direct to Consumer'),
('VangChinOranges','Fresh, juicy apples',2,92,'Medium','Fruits','HEB','Out of Stock','Wholesale'),
('HihiNgonOranges','Fresh, juicy apples',5,12,'Large','Meat','HEB','In Stock','Direct to Consumer'),
('MongMoXauBananas','Tasty bananas',9,31,'Small','Meat','Chiquita','Out of Stock','Retail'),
('HihiSachGrapes','Mixed berries',2,81,'Small','Vegetables','Chiquita','Out of Stock','Direct to Consumer'),
('MongMoHuBerries','Mixed berries',10,18,'Large','Meat','Sunkist','Pre-Order','Wholesale'),
('HihiHuGrapes','Sweet, ripe oranges',2,96,'Large','Seafood','Driscolls','In Stock','Direct to Consumer'),
('TimHuBerries','Delicious grapes',5,14,'Small','Fruits','Chiquita','Pre-Order','Retail'),
('TimHuApples','Mixed berries',2,100,'Medium','Vegetables','HEB','In Stock','Direct to Consumer'),
('HeheNgonBananas','Fresh, juicy apples',1,27,'Large','Seafood','Sunkist','Out of Stock','Wholesale'),
('TimThuiBananas','Sweet, ripe oranges',8,57,'Medium','Fruits','Sunkist','Out of Stock','Wholesale'),
('HeheXanhBerries','Mixed berries',1,79,'Large','Seafood','HEB','Out of Stock','Retail'),
('HeheThuiBananas','Fresh, juicy apples',2,39,'Small','Dairy','Dole','Pre-Order','Wholesale'),
('DoXanhOranges','Mixed berries',7,38,'Medium','Dairy','Sunkist','Out of Stock','Retail'),
('PhaleNgonBananas','Fresh, juicy apples',7,56,'Medium','Vegetables','Dole','In Stock','Retail'),
('TimSachGrapes','Sweet, ripe oranges',3,19,'Small','Fruits','Driscolls','Out of Stock','Retail'),
('PhaleXanhGrapes','Mixed berries',2,47,'Large','Seafood','Chiquita','In Stock','Direct to Consumer'),
('PhaleXauBerries','Fresh, juicy apples',7,79,'Large','Vegetables','Driscolls','Pre-Order','Retail'),
('HaHaDepBerries','Delicious grapes',10,13,'Medium','Fruits','Sunkist','In Stock','Wholesale'),
('HaHaSachApples','Sweet, ripe oranges',5,20,'Small','Meat','Chiquita','Out of Stock','Direct to Consumer'),
('HihiThuiBerries','Mixed berries',10,15,'Medium','Meat','Driscolls','Pre-Order','Direct to Consumer'),
('MongMoChinApples','Tasty bananas',8,90,'Small','Seafood','Sunkist','In Stock','Wholesale'),
('HeheXauGrapes','Tasty bananas',3,67,'Large','Dairy','Driscolls','Pre-Order','Retail'),
('DoSachOranges','Fresh, juicy apples',10,44,'Small','Fruits','HEB','In Stock','Direct to Consumer'),
('DoThuiOranges','Sweet, ripe oranges',3,82,'Large','Vegetables','Chiquita','Pre-Order','Retail'),
('HihiChinApples','Sweet, ripe oranges',6,66,'Large','Vegetables','Chiquita','Pre-Order','Retail'),
('DoXauBerries','Mixed berries',4,26,'Large','Fruits','Driscolls','In Stock','Direct to Consumer'),
('MongMoXanhBerries','Delicious grapes',7,10,'Small','Meat','Dole','Out of Stock','Wholesale'),
('PhaleXanhApples','Delicious grapes',4,26,'Large','Fruits','Chiquita','Out of Stock','Direct to Consumer'),
('MongMoChinApples','Fresh, juicy apples',2,79,'Large','Dairy','Dole','Out of Stock','Direct to Consumer'),
('MongMoXauApples','Mixed berries',1,88,'Large','Meat','HEB','Out of Stock','Retail'),
('PhaleDepOranges','Delicious grapes',10,10,'Medium','Seafood','Sunkist','In Stock','Wholesale'),
('HaHaChinBerries','Sweet, ripe oranges',2,28,'Large','Fruits','HEB','Out of Stock','Retail'),
('HeheXanhBananas','Delicious grapes',2,42,'Small','Vegetables','Dole','Pre-Order','Direct to Consumer'),
('HihiHuApples','Mixed berries',10,74,'Large','Fruits','Dole','In Stock','Wholesale'),
('HaHaXanhApples','Fresh, juicy apples',1,23,'Large','Vegetables','Dole','Pre-Order','Wholesale'),
('DoNgonApples','Tasty bananas',6,94,'Large','Vegetables','Dole','In Stock','Direct to Consumer'),
('VangNgonApples','Mixed berries',8,20,'Small','Vegetables','Driscolls','Out of Stock','Retail'),
('DoXauOranges','Sweet, ripe oranges',3,62,'Medium','Meat','Chiquita','Pre-Order','Direct to Consumer'),
('HeheDepBananas','Fresh, juicy apples',4,94,'Large','Seafood','Chiquita','Pre-Order','Direct to Consumer'),
('HihiChinBananas','Fresh, juicy apples',8,38,'Medium','Fruits','HEB','Out of Stock','Wholesale'),
('HihiXanhBerries','Fresh, juicy apples',8,33,'Medium','Dairy','Chiquita','Pre-Order','Retail'),
('HaHaNgonOranges','Sweet, ripe oranges',3,65,'Large','Meat','Dole','Out of Stock','Direct to Consumer'),
('PhaleChinOranges','Mixed berries',3,97,'Large','Seafood','Chiquita','Pre-Order','Wholesale'),
('PhaleSachBerries','Mixed berries',5,75,'Small','Meat','Chiquita','Out of Stock','Wholesale'),
('VangThuiBerries','Fresh, juicy apples',10,44,'Medium','Vegetables','Driscolls','Out of Stock','Retail'),
('HaHaXauBananas','Delicious grapes',1,98,'Small','Meat','HEB','Out of Stock','Retail'),
('DoThuiBananas','Mixed berries',1,65,'Large','Fruits','Sunkist','Pre-Order','Retail'),
('HaHaThuiApples','Mixed berries',1,66,'Medium','Meat','Driscolls','In Stock','Wholesale'),
('HeheXanhBerries','Delicious grapes',8,27,'Large','Seafood','HEB','In Stock','Retail'),
('HeheDepGrapes','Sweet, ripe oranges',4,22,'Small','Seafood','HEB','Out of Stock','Wholesale'),
('HihiChinGrapes','Fresh, juicy apples',9,68,'Small','Dairy','Sunkist','Pre-Order','Wholesale'),
('HihiHuBerries','Delicious grapes',3,47,'Large','Vegetables','Driscolls','Out of Stock','Retail'),
('HeheXauBananas','Delicious grapes',10,98,'Large','Seafood','Sunkist','Pre-Order','Wholesale'),
('PhaleXanhOranges','Delicious grapes',10,74,'Medium','Dairy','Chiquita','Out of Stock','Retail'),
('HihiThuiGrapes','Mixed berries',1,21,'Medium','Dairy','Chiquita','Pre-Order','Retail'),
('VangDepGrapes','Sweet, ripe oranges',2,61,'Small','Seafood','Dole','Pre-Order','Direct to Consumer'),
('HeheXauApples','Mixed berries',5,93,'Small','Vegetables','Sunkist','Out of Stock','Wholesale'),
('HeheSachOranges','Fresh, juicy apples',5,50,'Medium','Seafood','Driscolls','Pre-Order','Wholesale'),
('DoThuiOranges','Fresh, juicy apples',4,75,'Small','Meat','Dole','Pre-Order','Wholesale'),
('TimSachBananas','Delicious grapes',8,31,'Large','Dairy','Chiquita','Pre-Order','Retail'),
('TimXauOranges','Mixed berries',5,97,'Medium','Vegetables','Sunkist','Out of Stock','Direct to Consumer'),
('MongMoHuBananas','Sweet, ripe oranges',1,63,'Large','Vegetables','Driscolls','Out of Stock','Retail'),
('PhaleXanhApples','Delicious grapes',3,14,'Large','Vegetables','Sunkist','Pre-Order','Wholesale'),
('HaHaDepBerries','Fresh, juicy apples',5,48,'Small','Vegetables','Driscolls','In Stock','Wholesale'),
('MongMoNgonApples','Mixed berries',2,76,'Large','Vegetables','Chiquita','Pre-Order','Wholesale'),
('VangNgonGrapes','Delicious grapes',7,78,'Large','Dairy','Chiquita','Pre-Order','Retail'),
('MongMoXauBananas','Tasty bananas',2,46,'Large','Meat','Chiquita','Pre-Order','Retail'),
('VangSachBerries','Delicious grapes',6,86,'Small','Dairy','Driscolls','Out of Stock','Retail'),
('TimHuOranges','Delicious grapes',8,51,'Small','Dairy','HEB','Pre-Order','Direct to Consumer'),
('DoSachBananas','Mixed berries',10,60,'Small','Meat','Sunkist','In Stock','Wholesale'),
('MongMoThuiApples','Sweet, ripe oranges',7,82,'Medium','Seafood','HEB','Out of Stock','Wholesale'),
('HeheHuApples','Sweet, ripe oranges',4,71,'Small','Dairy','Driscolls','Pre-Order','Wholesale'),
('HeheThuiOranges','Fresh, juicy apples',10,64,'Small','Dairy','Dole','Pre-Order','Retail'),
('MongMoDepBerries','Fresh, juicy apples',2,50,'Medium','Fruits','Driscolls','Pre-Order','Retail'),
('PhaleChinOranges','Mixed berries',10,48,'Small','Meat','Chiquita','Out of Stock','Retail'),
('PhaleNgonGrapes','Mixed berries',10,16,'Large','Fruits','Sunkist','Pre-Order','Direct to Consumer'),
('HeheThuiBananas','Sweet, ripe oranges',3,50,'Medium','Fruits','Driscolls','Out of Stock','Direct to Consumer'),
('TimXanhOranges','Delicious grapes',10,97,'Large','Vegetables','Chiquita','In Stock','Direct to Consumer'),
('HaHaThuiBerries','Tasty bananas',4,47,'Medium','Vegetables','Dole','Out of Stock','Direct to Consumer'),
('TimSachOranges','Fresh, juicy apples',3,33,'Large','Vegetables','Driscolls','In Stock','Direct to Consumer'),
('HaHaDepGrapes','Fresh, juicy apples',2,40,'Large','Vegetables','Sunkist','Out of Stock','Wholesale'),
('HaHaSachApples','Delicious grapes',4,62,'Medium','Meat','Sunkist','Out of Stock','Wholesale'),
('MongMoThuiGrapes','Delicious grapes',7,26,'Medium','Dairy','Sunkist','Pre-Order','Direct to Consumer'),
('HihiChinApples','Mixed berries',9,22,'Large','Seafood','Dole','Out of Stock','Retail'),
('DoXanhBerries','Tasty bananas',2,77,'Large','Seafood','Driscolls','Out of Stock','Wholesale'),
('MongMoNgonApples','Delicious grapes',9,60,'Small','Vegetables','Chiquita','Out of Stock','Wholesale'),
('DoSachBerries','Sweet, ripe oranges',10,94,'Medium','Dairy','HEB','Out of Stock','Direct to Consumer'),
('HihiNgonBerries','Delicious grapes',2,39,'Large','Dairy','HEB','Pre-Order','Direct to Consumer'),
('DoHuApples','Fresh, juicy apples',4,78,'Small','Seafood','HEB','In Stock','Retail'),
('HeheThuiApples','Sweet, ripe oranges',9,32,'Medium','Meat','Sunkist','In Stock','Direct to Consumer'),
('PhaleXauGrapes','Mixed berries',1,62,'Large','Meat','HEB','Out of Stock','Wholesale'),
('HeheNgonApples','Delicious grapes',7,90,'Small','Fruits','Chiquita','Pre-Order','Direct to Consumer'),
('PhaleThuiBerries','Sweet, ripe oranges',10,94,'Medium','Fruits','HEB','Out of Stock','Direct to Consumer'),
('HeheThuiApples','Sweet, ripe oranges',6,69,'Small','Vegetables','Chiquita','In Stock','Wholesale'),
('PhaleThuiOranges','Fresh, juicy apples',9,21,'Large','Seafood','Chiquita','Out of Stock','Wholesale'),
('TimNgonOranges','Fresh, juicy apples',4,45,'Small','Seafood','Dole','Pre-Order','Wholesale'),
('DoNgonApples','Mixed berries',3,16,'Small','Seafood','Chiquita','Out of Stock','Retail'),
('TimXanhBananas','Mixed berries',8,26,'Large','Meat','Dole','In Stock','Wholesale'),
('HihiXanhOranges','Delicious grapes',3,24,'Medium','Fruits','Driscolls','In Stock','Retail'),
('MongMoSachGrapes','Tasty bananas',2,62,'Medium','Vegetables','HEB','Pre-Order','Wholesale'),
('PhaleNgonBananas','Delicious grapes',1,78,'Medium','Vegetables','HEB','In Stock','Direct to Consumer'),
('HihiChinApples','Tasty bananas',1,59,'Medium','Seafood','Driscolls','Out of Stock','Direct to Consumer'),
('TimXanhGrapes','Fresh, juicy apples',3,90,'Medium','Seafood','Driscolls','Pre-Order','Direct to Consumer'),
('HaHaChinOranges','Delicious grapes',9,73,'Medium','Dairy','Chiquita','Out of Stock','Retail'),
('DoHuApples','Mixed berries',10,12,'Medium','Fruits','Dole','Pre-Order','Direct to Consumer'),
('HaHaDepBananas','Delicious grapes',9,91,'Medium','Seafood','Driscolls','In Stock','Wholesale'),
('TimChinOranges','Sweet, ripe oranges',1,81,'Large','Dairy','Sunkist','Out of Stock','Direct to Consumer'),
('HihiThuiBerries','Sweet, ripe oranges',3,88,'Large','Dairy','HEB','In Stock','Wholesale'),
('HeheXanhBerries','Fresh, juicy apples',10,45,'Medium','Fruits','HEB','In Stock','Retail'),
('HeheXauGrapes','Delicious grapes',2,37,'Small','Vegetables','Chiquita','Pre-Order','Direct to Consumer'),
('HihiHuBerries','Sweet, ripe oranges',9,14,'Medium','Dairy','HEB','Pre-Order','Retail'),
('HeheThuiGrapes','Fresh, juicy apples',10,96,'Large','Seafood','Driscolls','Out of Stock','Direct to Consumer'),
('HaHaHuGrapes','Fresh, juicy apples',2,43,'Medium','Fruits','Dole','Pre-Order','Retail'),
('HaHaNgonBananas','Fresh, juicy apples',6,25,'Large','Dairy','HEB','Pre-Order','Wholesale'),
('MongMoNgonBerries','Delicious grapes',5,95,'Medium','Meat','Sunkist','Pre-Order','Wholesale'),
('HihiThuiOranges','Fresh, juicy apples',5,28,'Large','Fruits','Dole','In Stock','Direct to Consumer'),
('VangThuiBananas','Delicious grapes',7,23,'Small','Dairy','Driscolls','Out of Stock','Retail'),
('VangDepBerries','Fresh, juicy apples',4,36,'Medium','Seafood','Dole','Out of Stock','Direct to Consumer'),
('HeheSachApples','Sweet, ripe oranges',7,47,'Large','Fruits','HEB','Out of Stock','Retail'),
('VangHuOranges','Mixed berries',5,74,'Large','Meat','Dole','Out of Stock','Retail'),
('VangChinApples','Sweet, ripe oranges',3,66,'Large','Vegetables','Chiquita','Pre-Order','Wholesale'),
('TimNgonOranges','Tasty bananas',9,84,'Large','Vegetables','Sunkist','In Stock','Direct to Consumer'),
('MongMoDepOranges','Tasty bananas',10,82,'Medium','Vegetables','Dole','Out of Stock','Retail'),
('DoXanhBerries','Delicious grapes',4,91,'Medium','Meat','Chiquita','Pre-Order','Retail'),
('MongMoSachGrapes','Delicious grapes',7,71,'Large','Seafood','HEB','Pre-Order','Retail'),
('HeheHuGrapes','Fresh, juicy apples',5,44,'Large','Dairy','Chiquita','Pre-Order','Wholesale'),
('VangDepOranges','Sweet, ripe oranges',4,75,'Small','Seafood','Dole','Pre-Order','Wholesale'),
('DoSachOranges','Fresh, juicy apples',9,26,'Small','Vegetables','Chiquita','In Stock','Wholesale'),
('HeheChinApples','Tasty bananas',8,43,'Small','Fruits','HEB','Out of Stock','Wholesale'),
('HaHaChinBananas','Tasty bananas',10,58,'Small','Vegetables','Driscolls','Out of Stock','Direct to Consumer'),
('MongMoHuApples','Mixed berries',3,55,'Large','Vegetables','Chiquita','In Stock','Retail'),
('MongMoHuOranges','Fresh, juicy apples',3,52,'Small','Meat','Chiquita','Out of Stock','Direct to Consumer'),
('MongMoXauBananas','Sweet, ripe oranges',4,44,'Large','Vegetables','Dole','In Stock','Direct to Consumer'),
('DoChinOranges','Sweet, ripe oranges',5,45,'Medium','Dairy','Chiquita','Out of Stock','Direct to Consumer'),
('DoSachBananas','Mixed berries',7,53,'Medium','Dairy','HEB','In Stock','Retail'),
('PhaleChinBerries','Delicious grapes',9,89,'Medium','Meat','HEB','Out of Stock','Direct to Consumer'),
('VangNgonBananas','Delicious grapes',4,19,'Large','Fruits','Dole','Out of Stock','Direct to Consumer'),
('PhaleThuiOranges','Tasty bananas',10,49,'Medium','Dairy','Driscolls','Pre-Order','Wholesale'),
('VangHuBerries','Sweet, ripe oranges',3,13,'Large','Vegetables','HEB','Out of Stock','Wholesale'),
('TimDepBerries','Mixed berries',8,73,'Large','Meat','Chiquita','In Stock','Retail'),
('MongMoNgonBerries','Sweet, ripe oranges',3,70,'Large','Fruits','Chiquita','In Stock','Retail'),
('MongMoSachBananas','Fresh, juicy apples',5,68,'Large','Seafood','Chiquita','Pre-Order','Direct to Consumer'),
('HaHaDepBananas','Fresh, juicy apples',5,20,'Medium','Vegetables','Dole','In Stock','Direct to Consumer'),
('PhaleXauOranges','Sweet, ripe oranges',9,10,'Medium','Vegetables','HEB','Out of Stock','Direct to Consumer'),
('HihiThuiBerries','Tasty bananas',3,65,'Small','Fruits','Chiquita','Out of Stock','Retail'),
('TimChinBerries','Mixed berries',2,82,'Medium','Seafood','Sunkist','In Stock','Direct to Consumer'),
('MongMoThuiBananas','Delicious grapes',5,15,'Large','Dairy','Dole','Pre-Order','Direct to Consumer'),
('HaHaSachOranges','Fresh, juicy apples',5,64,'Small','Meat','Chiquita','Out of Stock','Direct to Consumer'),
('VangXanhApples','Tasty bananas',5,56,'Medium','Meat','Dole','Out of Stock','Retail'),
('HaHaSachOranges','Mixed berries',6,34,'Small','Seafood','Chiquita','Pre-Order','Direct to Consumer'),
('HihiNgonGrapes','Tasty bananas',7,59,'Small','Fruits','HEB','In Stock','Retail'),
('VangThuiBananas','Fresh, juicy apples',3,72,'Medium','Vegetables','Dole','Pre-Order','Wholesale'),
('DoHuGrapes','Sweet, ripe oranges',2,93,'Medium','Fruits','Dole','Pre-Order','Direct to Consumer'),
('TimChinBananas','Mixed berries',1,53,'Small','Seafood','Driscolls','In Stock','Retail'),
('TimXauBerries','Tasty bananas',3,92,'Small','Dairy','Chiquita','Out of Stock','Retail'),
('HaHaSachGrapes','Mixed berries',8,77,'Medium','Dairy','Dole','Out of Stock','Direct to Consumer'),
('TimSachBerries','Tasty bananas',6,87,'Small','Fruits','Sunkist','Pre-Order','Direct to Consumer'),
('TimNgonBerries','Fresh, juicy apples',4,30,'Small','Vegetables','Sunkist','Pre-Order','Retail'),
('HaHaChinApples','Tasty bananas',2,22,'Small','Meat','HEB','Pre-Order','Retail'),
('HeheChinGrapes','Fresh, juicy apples',9,85,'Small','Meat','Sunkist','Out of Stock','Direct to Consumer'),
('TimSachApples','Fresh, juicy apples',6,37,'Large','Vegetables','HEB','Pre-Order','Direct to Consumer'),
('VangThuiOranges','Fresh, juicy apples',5,12,'Medium','Seafood','Dole','Pre-Order','Retail'),
('TimSachGrapes','Mixed berries',1,61,'Small','Dairy','HEB','Out of Stock','Direct to Consumer'),
('DoHuApples','Tasty bananas',5,51,'Medium','Fruits','Driscolls','In Stock','Wholesale'),
('MongMoSachBananas','Fresh, juicy apples',8,67,'Large','Vegetables','Chiquita','In Stock','Direct to Consumer'),
('TimDepGrapes','Sweet, ripe oranges',4,58,'Medium','Dairy','Sunkist','In Stock','Wholesale'),
('TimHuGrapes','Tasty bananas',6,21,'Medium','Dairy','Dole','Out of Stock','Retail'),
('HihiXanhOranges','Fresh, juicy apples',3,81,'Large','Fruits','Chiquita','In Stock','Direct to Consumer'),
('HihiNgonBerries','Delicious grapes',1,68,'Large','Seafood','Sunkist','Pre-Order','Wholesale'),
('TimXanhOranges','Sweet, ripe oranges',7,29,'Small','Fruits','Sunkist','Pre-Order','Direct to Consumer'),
('HaHaHuApples','Delicious grapes',9,41,'Small','Dairy','HEB','Pre-Order','Wholesale'),
('PhaleXauBerries','Delicious grapes',1,28,'Small','Seafood','Chiquita','In Stock','Wholesale'),
('MongMoChinOranges','Fresh, juicy apples',2,49,'Medium','Vegetables','Dole','Out of Stock','Direct to Consumer'),
('HeheNgonGrapes','Tasty bananas',9,93,'Medium','Fruits','Driscolls','Out of Stock','Wholesale'),
('HeheXanhApples','Mixed berries',2,75,'Medium','Dairy','Chiquita','Pre-Order','Retail'),
('HaHaXanhApples','Fresh, juicy apples',2,33,'Small','Fruits','Chiquita','In Stock','Wholesale'),
('HeheXanhApples','Tasty bananas',1,33,'Small','Fruits','Dole','Out of Stock','Retail'),
('TimDepApples','Mixed berries',10,75,'Small','Fruits','Dole','Pre-Order','Retail'),
('HaHaXanhBerries','Tasty bananas',3,49,'Medium','Seafood','Sunkist','Pre-Order','Retail'),
('VangHuGrapes','Tasty bananas',9,60,'Small','Seafood','HEB','Pre-Order','Retail'),
('HeheHuOranges','Sweet, ripe oranges',9,63,'Medium','Vegetables','Driscolls','Pre-Order','Retail'),
('HaHaXauOranges','Tasty bananas',10,80,'Large','Fruits','Sunkist','Pre-Order','Wholesale'),
('MongMoNgonBananas','Fresh, juicy apples',5,15,'Medium','Meat','Sunkist','Pre-Order','Direct to Consumer'),
('VangXanhApples','Fresh, juicy apples',3,81,'Large','Vegetables','HEB','In Stock','Direct to Consumer'),
('TimXanhGrapes','Tasty bananas',3,43,'Large','Fruits','Dole','Pre-Order','Retail'),
('HaHaChinGrapes','Fresh, juicy apples',4,14,'Medium','Fruits','Sunkist','Out of Stock','Wholesale'),
('MongMoNgonGrapes','Mixed berries',1,66,'Large','Seafood','Chiquita','Pre-Order','Direct to Consumer'),
('DoXanhOranges','Mixed berries',6,50,'Medium','Dairy','Driscolls','Out of Stock','Wholesale'),
('VangHuGrapes','Sweet, ripe oranges',6,61,'Large','Fruits','Sunkist','Pre-Order','Wholesale'),
('MongMoSachBerries','Fresh, juicy apples',6,94,'Large','Fruits','HEB','Out of Stock','Retail'),
('PhaleXauApples','Fresh, juicy apples',6,88,'Medium','Vegetables','Sunkist','Pre-Order','Wholesale'),
('DoThuiBananas','Fresh, juicy apples',10,43,'Medium','Vegetables','Sunkist','In Stock','Direct to Consumer'),
('HaHaChinGrapes','Tasty bananas',3,56,'Small','Dairy','Sunkist','Pre-Order','Wholesale'),
('TimXauOranges','Fresh, juicy apples',3,65,'Large','Dairy','Chiquita','Out of Stock','Wholesale'),
('MongMoXanhApples','Mixed berries',1,50,'Large','Meat','Sunkist','Out of Stock','Direct to Consumer'),
('HaHaHuOranges','Delicious grapes',2,28,'Large','Vegetables','Driscolls','Pre-Order','Wholesale'),
('HaHaSachOranges','Fresh, juicy apples',2,60,'Small','Vegetables','Dole','Pre-Order','Retail'),
('TimHuApples','Sweet, ripe oranges',7,85,'Medium','Meat','Dole','Out of Stock','Direct to Consumer'),
('TimChinOranges','Mixed berries',8,82,'Small','Seafood','Chiquita','Out of Stock','Wholesale'),
('VangSachOranges','Delicious grapes',6,56,'Medium','Seafood','Dole','In Stock','Direct to Consumer'),
('HihiSachBananas','Fresh, juicy apples',4,57,'Medium','Seafood','Chiquita','Pre-Order','Retail'),
('PhaleNgonApples','Tasty bananas',8,17,'Medium','Vegetables','HEB','Pre-Order','Wholesale'),
('MongMoSachBananas','Sweet, ripe oranges',2,94,'Large','Vegetables','Dole','In Stock','Wholesale'),
('HihiSachOranges','Tasty bananas',4,99,'Small','Vegetables','Driscolls','In Stock','Retail'),
('HaHaThuiOranges','Delicious grapes',1,42,'Small','Meat','HEB','Pre-Order','Direct to Consumer'),
('HihiSachApples','Fresh, juicy apples',10,14,'Large','Vegetables','Sunkist','Pre-Order','Wholesale'),
('TimSachBerries','Mixed berries',4,27,'Medium','Fruits','Sunkist','Pre-Order','Retail'),
('DoHuBananas','Fresh, juicy apples',6,63,'Medium','Dairy','Sunkist','In Stock','Wholesale'),
('VangChinBananas','Sweet, ripe oranges',9,59,'Large','Seafood','Sunkist','In Stock','Wholesale'),
('HihiXauBerries','Mixed berries',10,13,'Medium','Fruits','Sunkist','In Stock','Direct to Consumer'),
('MongMoSachGrapes','Fresh, juicy apples',2,33,'Large','Dairy','HEB','Out of Stock','Retail'),
('HaHaXanhBananas','Fresh, juicy apples',4,59,'Large','Dairy','HEB','Out of Stock','Wholesale'),
('HihiNgonBananas','Sweet, ripe oranges',3,19,'Large','Fruits','Driscolls','In Stock','Wholesale'),
('DoXauBananas','Sweet, ripe oranges',8,49,'Small','Seafood','Dole','Pre-Order','Wholesale'),
('TimNgonApples','Mixed berries',7,14,'Large','Dairy','HEB','In Stock','Direct to Consumer'),
('HihiHuGrapes','Fresh, juicy apples',8,53,'Large','Meat','Dole','Pre-Order','Retail'),
('HaHaChinApples','Mixed berries',1,93,'Medium','Meat','HEB','Pre-Order','Wholesale'),
('MongMoDepApples','Fresh, juicy apples',1,99,'Large','Fruits','HEB','Out of Stock','Wholesale'),
('TimXanhGrapes','Sweet, ripe oranges',2,89,'Medium','Dairy','Dole','Pre-Order','Retail'),
('MongMoXauApples','Tasty bananas',9,75,'Large','Vegetables','HEB','In Stock','Retail'),
('MongMoXanhApples','Tasty bananas',3,60,'Small','Meat','Chiquita','Out of Stock','Retail'),
('TimXauGrapes','Sweet, ripe oranges',4,72,'Small','Fruits','Dole','Pre-Order','Retail'),
('TimXanhOranges','Mixed berries',9,71,'Medium','Dairy','Chiquita','In Stock','Direct to Consumer'),
('TimDepBerries','Mixed berries',1,30,'Large','Meat','Driscolls','Pre-Order','Wholesale'),
('HaHaXauBananas','Fresh, juicy apples',9,25,'Large','Vegetables','Chiquita','Out of Stock','Retail'),
('MongMoXanhGrapes','Fresh, juicy apples',1,57,'Large','Seafood','HEB','Pre-Order','Direct to Consumer'),
('PhaleChinGrapes','Mixed berries',2,49,'Large','Dairy','Sunkist','In Stock','Wholesale'),
('MongMoSachOranges','Delicious grapes',10,82,'Medium','Meat','Dole','Pre-Order','Retail'),
('HihiNgonApples','Fresh, juicy apples',9,45,'Small','Meat','Dole','Pre-Order','Direct to Consumer'),
('TimXanhBerries','Mixed berries',4,41,'Small','Vegetables','Chiquita','In Stock','Retail'),
('MongMoXanhBerries','Sweet, ripe oranges',4,33,'Small','Meat','Driscolls','In Stock','Wholesale'),
('TimChinBerries','Delicious grapes',7,19,'Medium','Seafood','Driscolls','Pre-Order','Direct to Consumer'),
('MongMoSachBerries','Fresh, juicy apples',8,21,'Medium','Fruits','HEB','Pre-Order','Direct to Consumer'),
('VangHuOranges','Mixed berries',6,49,'Small','Meat','Dole','In Stock','Retail'),
('TimDepGrapes','Mixed berries',1,37,'Small','Meat','Sunkist','In Stock','Direct to Consumer'),
('DoThuiBerries','Tasty bananas',5,11,'Large','Fruits','Driscolls','Pre-Order','Retail'),
('HaHaSachApples','Sweet, ripe oranges',5,77,'Small','Vegetables','HEB','Pre-Order','Direct to Consumer'),
('MongMoChinGrapes','Fresh, juicy apples',5,57,'Large','Seafood','Driscolls','Out of Stock','Wholesale'),
('PhaleXanhApples','Sweet, ripe oranges',8,94,'Small','Meat','Dole','In Stock','Wholesale'),
('PhaleDepBananas','Tasty bananas',4,25,'Large','Meat','Sunkist','Out of Stock','Wholesale'),
('HihiXanhGrapes','Mixed berries',4,96,'Large','Dairy','Dole','In Stock','Wholesale'),
('PhaleThuiBerries','Fresh, juicy apples',6,40,'Medium','Meat','Chiquita','Out of Stock','Direct to Consumer'),
('HeheChinBerries','Delicious grapes',3,66,'Large','Meat','Sunkist','Out of Stock','Retail'),
('VangChinBananas','Fresh, juicy apples',6,28,'Medium','Vegetables','Sunkist','In Stock','Retail'),
('HihiXauOranges','Mixed berries',3,28,'Large','Meat','Driscolls','Pre-Order','Wholesale'),
('HeheSachApples','Fresh, juicy apples',9,66,'Small','Seafood','Chiquita','Pre-Order','Retail'),
('MongMoThuiBananas','Tasty bananas',10,45,'Medium','Meat','Dole','In Stock','Retail'),
('TimDepGrapes','Sweet, ripe oranges',4,51,'Large','Seafood','Chiquita','Pre-Order','Direct to Consumer'),
('DoSachBerries','Sweet, ripe oranges',6,15,'Large','Fruits','HEB','Pre-Order','Wholesale'),
('HaHaThuiBananas','Delicious grapes',2,71,'Small','Vegetables','HEB','Pre-Order','Wholesale'),
('DoDepBerries','Delicious grapes',4,87,'Medium','Meat','HEB','Out of Stock','Retail'),
('DoXauOranges','Sweet, ripe oranges',3,26,'Medium','Dairy','Driscolls','Pre-Order','Direct to Consumer'),
('DoNgonBananas','Sweet, ripe oranges',6,68,'Large','Meat','Sunkist','Out of Stock','Direct to Consumer'),
('HeheChinApples','Mixed berries',3,66,'Medium','Seafood','Dole','Pre-Order','Retail'),
('HaHaXauGrapes','Delicious grapes',3,67,'Small','Meat','HEB','Out of Stock','Retail'),
('DoSachBananas','Sweet, ripe oranges',9,22,'Small','Seafood','HEB','Out of Stock','Direct to Consumer'),
('VangXauApples','Fresh, juicy apples',9,16,'Small','Dairy','Sunkist','In Stock','Direct to Consumer'),
('MongMoXanhBerries','Sweet, ripe oranges',3,39,'Large','Vegetables','Driscolls','Out of Stock','Direct to Consumer'),
('HaHaThuiBerries','Tasty bananas',8,71,'Small','Meat','Dole','In Stock','Retail'),
('DoNgonGrapes','Fresh, juicy apples',5,93,'Small','Seafood','Driscolls','Out of Stock','Wholesale'),
('MongMoDepOranges','Fresh, juicy apples',6,68,'Medium','Seafood','Dole','In Stock','Direct to Consumer'),
('DoSachApples','Sweet, ripe oranges',8,68,'Medium','Fruits','HEB','Out of Stock','Direct to Consumer'),
('HaHaChinOranges','Mixed berries',8,20,'Large','Vegetables','Chiquita','Out of Stock','Wholesale'),
('HaHaSachOranges','Delicious grapes',9,44,'Large','Dairy','Dole','Pre-Order','Retail'),
('TimNgonOranges','Tasty bananas',2,73,'Small','Fruits','HEB','Out of Stock','Direct to Consumer'),
('PhaleThuiOranges','Mixed berries',6,72,'Small','Fruits','Sunkist','Pre-Order','Direct to Consumer'),
('DoXauGrapes','Sweet, ripe oranges',1,77,'Small','Vegetables','Driscolls','Out of Stock','Direct to Consumer'),
('HeheXanhBananas','Delicious grapes',10,52,'Small','Fruits','Driscolls','Out of Stock','Wholesale'),
('HeheHuApples','Sweet, ripe oranges',9,72,'Large','Vegetables','Sunkist','Pre-Order','Direct to Consumer'),
('VangXauOranges','Delicious grapes',10,82,'Medium','Seafood','Dole','Out of Stock','Wholesale'),
('HeheNgonBananas','Sweet, ripe oranges',10,75,'Large','Seafood','Sunkist','Out of Stock','Retail'),
('TimHuGrapes','Delicious grapes',6,82,'Large','Seafood','HEB','Out of Stock','Wholesale'),
('PhaleThuiOranges','Delicious grapes',6,66,'Small','Dairy','Dole','Pre-Order','Retail'),
('MongMoThuiBerries','Tasty bananas',8,51,'Small','Meat','Chiquita','Pre-Order','Wholesale'),
('PhaleNgonBerries','Fresh, juicy apples',2,81,'Large','Seafood','Dole','Out of Stock','Wholesale'),
('MongMoThuiGrapes','Mixed berries',4,45,'Large','Seafood','Chiquita','Pre-Order','Direct to Consumer'),
('HeheNgonGrapes','Fresh, juicy apples',9,40,'Small','Seafood','Driscolls','In Stock','Wholesale'),
('VangThuiBananas','Fresh, juicy apples',4,84,'Small','Vegetables','Sunkist','Out of Stock','Direct to Consumer'),
('HihiDepBananas','Fresh, juicy apples',9,94,'Small','Seafood','Dole','Out of Stock','Retail'),
('HihiXanhBananas','Fresh, juicy apples',5,59,'Small','Vegetables','Sunkist','Pre-Order','Direct to Consumer'),
('PhaleNgonBananas','Mixed berries',8,30,'Small','Seafood','Driscolls','Out of Stock','Wholesale'),
('TimHuGrapes','Fresh, juicy apples',9,74,'Large','Dairy','Sunkist','Out of Stock','Wholesale'),
('HihiChinApples','Fresh, juicy apples',6,75,'Large','Meat','Dole','Pre-Order','Direct to Consumer'),
('DoChinBerries','Sweet, ripe oranges',1,27,'Large','Meat','Dole','Out of Stock','Retail'),
('PhaleXanhApples','Delicious grapes',7,47,'Large','Vegetables','Chiquita','Pre-Order','Retail'),
('HihiNgonBerries','Tasty bananas',9,37,'Small','Vegetables','Chiquita','Out of Stock','Wholesale'),
('HihiSachBerries','Fresh, juicy apples',7,100,'Small','Fruits','Chiquita','Pre-Order','Wholesale'),
('DoHuApples','Delicious grapes',6,40,'Medium','Vegetables','Sunkist','In Stock','Wholesale'),
('HaHaXauApples','Mixed berries',10,45,'Small','Fruits','Driscolls','Out of Stock','Direct to Consumer'),
('TimHuOranges','Tasty bananas',1,52,'Medium','Fruits','Driscolls','Pre-Order','Direct to Consumer'),
('MongMoThuiBananas','Sweet, ripe oranges',8,32,'Small','Seafood','Sunkist','In Stock','Retail'),
('HaHaXauApples','Tasty bananas',1,26,'Medium','Vegetables','Chiquita','Out of Stock','Retail'),
('HeheChinBananas','Fresh, juicy apples',7,20,'Medium','Meat','Chiquita','Out of Stock','Direct to Consumer'),
('TimXanhGrapes','Tasty bananas',8,86,'Medium','Vegetables','HEB','In Stock','Retail'),
('PhaleHuApples','Sweet, ripe oranges',9,92,'Medium','Fruits','Dole','Pre-Order','Wholesale'),
('HihiXanhBananas','Sweet, ripe oranges',10,58,'Medium','Meat','Driscolls','Out of Stock','Direct to Consumer'),
('HihiSachBerries','Tasty bananas',7,26,'Large','Meat','Driscolls','In Stock','Retail'),
('HeheXanhApples','Delicious grapes',6,73,'Large','Seafood','HEB','Out of Stock','Wholesale'),
('PhaleChinBananas','Fresh, juicy apples',4,18,'Large','Seafood','Sunkist','In Stock','Wholesale'),
('HaHaNgonGrapes','Fresh, juicy apples',9,68,'Small','Vegetables','Sunkist','Pre-Order','Retail'),
('HeheXanhBananas','Sweet, ripe oranges',6,97,'Small','Fruits','Driscolls','Out of Stock','Retail'),
('DoThuiGrapes','Tasty bananas',4,66,'Small','Fruits','HEB','Out of Stock','Wholesale'),
('PhaleSachOranges','Sweet, ripe oranges',8,23,'Medium','Fruits','HEB','Out of Stock','Retail'),
('PhaleChinGrapes','Fresh, juicy apples',3,20,'Small','Seafood','Driscolls','Out of Stock','Retail'),
('HeheThuiBananas','Mixed berries',7,43,'Small','Vegetables','Chiquita','In Stock','Direct to Consumer'),
('HeheThuiApples','Tasty bananas',3,11,'Small','Dairy','Driscolls','Pre-Order','Wholesale'),
('VangXanhOranges','Delicious grapes',2,42,'Medium','Seafood','Dole','Out of Stock','Direct to Consumer'),
('DoHuGrapes','Sweet, ripe oranges',8,71,'Small','Vegetables','Driscolls','In Stock','Wholesale'),
('MongMoThuiBerries','Fresh, juicy apples',4,98,'Medium','Vegetables','Chiquita','Out of Stock','Wholesale'),
('HeheHuBerries','Delicious grapes',5,21,'Medium','Vegetables','Sunkist','Out of Stock','Retail'),
('HeheThuiBerries','Tasty bananas',8,75,'Medium','Fruits','Dole','In Stock','Wholesale'),
('HaHaThuiBerries','Fresh, juicy apples',8,88,'Large','Seafood','Driscolls','Pre-Order','Retail'),
('PhaleHuGrapes','Delicious grapes',3,92,'Small','Fruits','Sunkist','Out of Stock','Direct to Consumer'),
('HihiDepBananas','Tasty bananas',8,98,'Large','Dairy','Driscolls','In Stock','Wholesale'),
('PhaleXanhGrapes','Sweet, ripe oranges',3,92,'Small','Dairy','Dole','Pre-Order','Retail'),
('HihiXauOranges','Fresh, juicy apples',7,69,'Small','Vegetables','Dole','In Stock','Retail'),
('HeheChinApples','Tasty bananas',8,60,'Small','Meat','Sunkist','In Stock','Direct to Consumer'),
('VangChinBerries','Sweet, ripe oranges',5,81,'Medium','Seafood','HEB','Pre-Order','Retail'),
('MongMoThuiOranges','Fresh, juicy apples',3,84,'Large','Seafood','HEB','In Stock','Retail'),
('MongMoNgonGrapes','Sweet, ripe oranges',7,59,'Medium','Dairy','Dole','Out of Stock','Retail'),
('HaHaXanhOranges','Sweet, ripe oranges',4,94,'Small','Fruits','Sunkist','In Stock','Wholesale'),
('MongMoHuBananas','Sweet, ripe oranges',8,23,'Small','Seafood','HEB','In Stock','Direct to Consumer'),
('DoThuiBananas','Tasty bananas',2,51,'Large','Vegetables','Sunkist','In Stock','Direct to Consumer'),
('PhaleSachGrapes','Fresh, juicy apples',3,31,'Small','Meat','Chiquita','Out of Stock','Direct to Consumer'),
('HihiChinBananas','Fresh, juicy apples',4,88,'Medium','Dairy','Chiquita','Out of Stock','Wholesale'),
('HihiDepBerries','Tasty bananas',10,59,'Large','Vegetables','Driscolls','In Stock','Retail'),
('HeheSachOranges','Fresh, juicy apples',7,48,'Large','Dairy','Sunkist','In Stock','Retail'),
('PhaleXauBerries','Sweet, ripe oranges',7,64,'Medium','Dairy','HEB','Pre-Order','Wholesale'),
('VangHuApples','Fresh, juicy apples',1,20,'Large','Vegetables','Driscolls','Pre-Order','Wholesale'),
('MongMoHuOranges','Mixed berries',9,74,'Medium','Meat','Dole','Pre-Order','Direct to Consumer'),
('HihiHuGrapes','Mixed berries',5,78,'Large','Seafood','Driscolls','Pre-Order','Retail'),
('MongMoSachOranges','Mixed berries',6,56,'Small','Seafood','Sunkist','Pre-Order','Wholesale'),
('PhaleXauBananas','Mixed berries',6,13,'Medium','Seafood','Dole','In Stock','Direct to Consumer'),
('HihiXanhBerries','Delicious grapes',6,52,'Large','Fruits','Driscolls','In Stock','Retail'),
('HaHaSachApples','Tasty bananas',3,19,'Medium','Fruits','HEB','Pre-Order','Direct to Consumer'),
('DoDepOranges','Fresh, juicy apples',2,13,'Medium','Meat','HEB','Pre-Order','Retail'),
('DoSachApples','Mixed berries',4,86,'Medium','Vegetables','HEB','Pre-Order','Wholesale'),
('DoChinBananas','Delicious grapes',4,79,'Small','Seafood','Dole','In Stock','Direct to Consumer'),
('VangHuOranges','Tasty bananas',2,62,'Small','Dairy','Sunkist','Out of Stock','Retail'),
('PhaleDepApples','Fresh, juicy apples',5,20,'Medium','Fruits','Dole','In Stock','Direct to Consumer'),
('MongMoChinBerries','Tasty bananas',9,29,'Small','Vegetables','Chiquita','In Stock','Wholesale'),
('HaHaXauOranges','Sweet, ripe oranges',4,80,'Small','Dairy','Dole','Out of Stock','Wholesale'),
('MongMoSachGrapes','Tasty bananas',10,45,'Small','Meat','Dole','In Stock','Retail'),
('PhaleChinGrapes','Sweet, ripe oranges',7,42,'Medium','Meat','Chiquita','Out of Stock','Wholesale'),
('DoNgonGrapes','Tasty bananas',1,60,'Medium','Fruits','HEB','In Stock','Direct to Consumer'),
('MongMoSachBerries','Mixed berries',3,80,'Small','Fruits','Dole','Pre-Order','Direct to Consumer'),
('MongMoChinApples','Tasty bananas',5,45,'Medium','Seafood','Driscolls','Out of Stock','Retail'),
('PhaleThuiBananas','Fresh, juicy apples',3,52,'Medium','Vegetables','Driscolls','Out of Stock','Retail'),
('TimDepBerries','Sweet, ripe oranges',6,97,'Small','Meat','Sunkist','In Stock','Retail'),
('DoThuiApples','Sweet, ripe oranges',1,38,'Small','Meat','Driscolls','In Stock','Wholesale'),
('HaHaXauApples','Tasty bananas',2,23,'Medium','Seafood','Sunkist','Pre-Order','Retail'),
('MongMoDepBerries','Delicious grapes',3,36,'Medium','Seafood','Sunkist','In Stock','Direct to Consumer'),
('VangDepOranges','Fresh, juicy apples',7,93,'Medium','Dairy','Chiquita','In Stock','Retail'),
('HihiDepBerries','Sweet, ripe oranges',9,27,'Medium','Seafood','Chiquita','In Stock','Direct to Consumer'),
('MongMoHuOranges','Fresh, juicy apples',5,25,'Medium','Meat','HEB','Pre-Order','Retail'),
('DoSachBerries','Sweet, ripe oranges',1,87,'Medium','Dairy','Sunkist','Out of Stock','Direct to Consumer'),
('HaHaHuOranges','Fresh, juicy apples',6,19,'Large','Seafood','Driscolls','Out of Stock','Direct to Consumer'),
('DoSachBerries','Fresh, juicy apples',1,52,'Large','Dairy','Chiquita','Out of Stock','Wholesale'),
('DoSachGrapes','Sweet, ripe oranges',10,71,'Small','Seafood','Sunkist','Pre-Order','Direct to Consumer'),
('PhaleDepBerries','Fresh, juicy apples',4,81,'Small','Dairy','Sunkist','In Stock','Wholesale'),
('PhaleXanhOranges','Fresh, juicy apples',2,27,'Large','Dairy','Dole','Out of Stock','Retail'),
('HaHaChinOranges','Tasty bananas',8,18,'Medium','Fruits','Sunkist','Out of Stock','Direct to Consumer'),
('VangNgonOranges','Delicious grapes',2,45,'Small','Vegetables','HEB','In Stock','Retail'),
('HaHaSachBananas','Delicious grapes',9,97,'Small','Vegetables','Dole','Pre-Order','Direct to Consumer'),
('PhaleXanhBananas','Mixed berries',4,95,'Small','Meat','Sunkist','Pre-Order','Retail'),
('HaHaHuBananas','Sweet, ripe oranges',2,78,'Medium','Meat','Dole','Pre-Order','Wholesale'),
('TimDepBerries','Sweet, ripe oranges',2,50,'Large','Fruits','Driscolls','Out of Stock','Wholesale'),
('HeheNgonBerries','Delicious grapes',7,84,'Small','Dairy','Sunkist','Out of Stock','Retail'),
('MongMoXauGrapes','Fresh, juicy apples',6,26,'Large','Dairy','HEB','In Stock','Wholesale'),
('MongMoThuiBananas','Delicious grapes',1,73,'Medium','Seafood','Dole','Pre-Order','Wholesale'),
('PhaleChinOranges','Fresh, juicy apples',8,27,'Medium','Vegetables','Dole','In Stock','Wholesale'),
('VangSachOranges','Fresh, juicy apples',8,40,'Large','Seafood','Sunkist','Pre-Order','Direct to Consumer'),
('TimXauOranges','Delicious grapes',6,50,'Small','Vegetables','HEB','In Stock','Wholesale'),
('HeheXanhApples','Mixed berries',10,32,'Small','Meat','HEB','Out of Stock','Retail'),
('PhaleXanhBerries','Tasty bananas',6,68,'Small','Seafood','Driscolls','In Stock','Retail'),
('PhaleThuiBananas','Sweet, ripe oranges',4,77,'Medium','Meat','HEB','In Stock','Retail'),
('TimDepGrapes','Mixed berries',8,88,'Large','Meat','Chiquita','Out of Stock','Direct to Consumer'),
('MongMoDepOranges','Mixed berries',9,64,'Medium','Dairy','HEB','Pre-Order','Direct to Consumer'),
('HeheXanhBerries','Tasty bananas',7,26,'Medium','Dairy','Chiquita','Out of Stock','Retail'),
('VangChinBerries','Sweet, ripe oranges',10,48,'Medium','Vegetables','HEB','In Stock','Wholesale'),
('MongMoXanhBananas','Tasty bananas',7,52,'Large','Meat','Dole','Out of Stock','Retail'),
('HihiThuiBerries','Fresh, juicy apples',5,83,'Small','Vegetables','Dole','In Stock','Retail'),
('TimHuApples','Fresh, juicy apples',9,13,'Medium','Seafood','Dole','In Stock','Retail'),
('HihiThuiOranges','Tasty bananas',3,85,'Small','Vegetables','Chiquita','Pre-Order','Retail'),
('DoHuGrapes','Tasty bananas',5,86,'Large','Vegetables','Chiquita','In Stock','Retail'),
('PhaleXauOranges','Mixed berries',10,60,'Small','Dairy','Sunkist','Out of Stock','Direct to Consumer'),
('HaHaHuBananas','Sweet, ripe oranges',10,26,'Small','Seafood','HEB','Out of Stock','Retail'),
('HaHaChinApples','Mixed berries',4,61,'Large','Fruits','Sunkist','Pre-Order','Direct to Consumer'),
('DoDepBerries','Delicious grapes',7,13,'Small','Fruits','Sunkist','Pre-Order','Direct to Consumer'),
('VangHuOranges','Delicious grapes',4,89,'Medium','Meat','Dole','Out of Stock','Wholesale'),
('VangChinApples','Sweet, ripe oranges',4,98,'Large','Dairy','Chiquita','Pre-Order','Retail'),
('VangThuiBananas','Sweet, ripe oranges',10,70,'Large','Seafood','Sunkist','In Stock','Wholesale'),
('MongMoSachGrapes','Mixed berries',9,69,'Medium','Meat','Driscolls','In Stock','Retail'),
('VangXauOranges','Sweet, ripe oranges',3,85,'Small','Vegetables','Sunkist','In Stock','Retail'),
('HihiXanhApples','Mixed berries',8,25,'Large','Meat','Driscolls','Pre-Order','Retail'),
('DoXanhApples','Tasty bananas',10,49,'Large','Dairy','Dole','Pre-Order','Retail'),
('DoHuApples','Mixed berries',9,38,'Large','Seafood','Sunkist','In Stock','Direct to Consumer'),
('PhaleDepGrapes','Delicious grapes',10,100,'Medium','Seafood','Sunkist','Pre-Order','Direct to Consumer'),
('HeheHuOranges','Sweet, ripe oranges',1,87,'Medium','Fruits','Dole','In Stock','Direct to Consumer'),
('HihiNgonApples','Sweet, ripe oranges',1,21,'Small','Meat','Dole','In Stock','Direct to Consumer'),
('MongMoThuiOranges','Sweet, ripe oranges',4,17,'Large','Vegetables','Sunkist','Pre-Order','Wholesale'),
('TimDepGrapes','Fresh, juicy apples',6,57,'Small','Fruits','Driscolls','Out of Stock','Direct to Consumer'),
('DoXanhBerries','Fresh, juicy apples',5,74,'Small','Meat','Driscolls','Pre-Order','Retail'),
('HihiThuiBananas','Tasty bananas',4,31,'Small','Dairy','HEB','Pre-Order','Wholesale'),
('VangHuOranges','Mixed berries',2,93,'Large','Dairy','Dole','Out of Stock','Wholesale'),
('HaHaChinBerries','Fresh, juicy apples',4,82,'Small','Dairy','HEB','Pre-Order','Retail'),
('HihiNgonBananas','Mixed berries',10,14,'Large','Meat','Chiquita','Out of Stock','Wholesale'),
('PhaleHuGrapes','Tasty bananas',5,34,'Medium','Dairy','Dole','Pre-Order','Wholesale'),
('MongMoDepBerries','Delicious grapes',10,72,'Medium','Seafood','Sunkist','In Stock','Direct to Consumer'),
('HeheChinApples','Delicious grapes',3,97,'Medium','Meat','Chiquita','In Stock','Direct to Consumer'),
('MongMoSachBerries','Mixed berries',8,88,'Medium','Meat','Dole','Pre-Order','Retail'),
('DoXanhOranges','Mixed berries',10,14,'Large','Fruits','HEB','Out of Stock','Retail'),
('PhaleHuApples','Delicious grapes',7,35,'Large','Seafood','Sunkist','Out of Stock','Wholesale'),
('HaHaChinGrapes','Mixed berries',10,18,'Medium','Seafood','Sunkist','Out of Stock','Wholesale'),
('DoChinBerries','Fresh, juicy apples',3,71,'Medium','Fruits','Dole','Out of Stock','Wholesale'),
('PhaleChinGrapes','Mixed berries',2,22,'Large','Fruits','Sunkist','In Stock','Retail'),
('MongMoThuiBerries','Tasty bananas',2,75,'Medium','Meat','HEB','In Stock','Wholesale'),
('HeheHuBananas','Tasty bananas',6,20,'Small','Vegetables','Chiquita','Out of Stock','Wholesale'),
('VangXanhBananas','Mixed berries',1,42,'Small','Vegetables','Chiquita','Out of Stock','Direct to Consumer'),
('PhaleHuGrapes','Tasty bananas',7,100,'Medium','Seafood','Dole','In Stock','Direct to Consumer'),
('PhaleHuBananas','Fresh, juicy apples',10,90,'Small','Fruits','Chiquita','Pre-Order','Retail'),
('DoSachOranges','Sweet, ripe oranges',3,10,'Large','Fruits','HEB','In Stock','Direct to Consumer'),
('DoSachApples','Mixed berries',10,48,'Small','Dairy','Driscolls','In Stock','Wholesale'),
('VangNgonBananas','Delicious grapes',4,59,'Large','Dairy','Dole','Pre-Order','Retail'),
('HaHaXanhApples','Fresh, juicy apples',3,90,'Medium','Fruits','Chiquita','In Stock','Wholesale'),
('TimNgonOranges','Mixed berries',10,24,'Small','Seafood','HEB','Pre-Order','Wholesale'),
('PhaleXanhApples','Fresh, juicy apples',9,84,'Small','Meat','Driscolls','Out of Stock','Retail'),
('TimHuBerries','Mixed berries',9,10,'Medium','Seafood','HEB','Out of Stock','Direct to Consumer'),
('PhaleNgonGrapes','Tasty bananas',9,64,'Small','Dairy','Chiquita','In Stock','Retail'),
('HeheDepBerries','Fresh, juicy apples',8,27,'Large','Vegetables','Chiquita','Out of Stock','Retail'),
('DoThuiBerries','Sweet, ripe oranges',10,91,'Small','Meat','Dole','In Stock','Wholesale'),
('MongMoXanhOranges','Fresh, juicy apples',5,16,'Small','Fruits','Sunkist','Pre-Order','Retail'),
('PhaleChinApples','Sweet, ripe oranges',10,45,'Small','Dairy','Dole','Out of Stock','Retail'),
('HihiXanhOranges','Tasty bananas',1,38,'Small','Seafood','Dole','In Stock','Retail'),
('MongMoNgonBerries','Tasty bananas',2,32,'Small','Meat','Dole','Out of Stock','Direct to Consumer'),
('DoHuApples','Sweet, ripe oranges',7,34,'Large','Dairy','Chiquita','Pre-Order','Wholesale'),
('DoDepOranges','Sweet, ripe oranges',2,70,'Large','Vegetables','HEB','In Stock','Direct to Consumer'),
('HaHaXauGrapes','Fresh, juicy apples',4,89,'Large','Meat','Sunkist','In Stock','Wholesale'),
('HaHaHuOranges','Mixed berries',4,38,'Large','Meat','Sunkist','Out of Stock','Retail'),
('VangHuGrapes','Delicious grapes',10,80,'Medium','Dairy','Chiquita','Out of Stock','Wholesale'),
('VangXanhGrapes','Delicious grapes',8,73,'Small','Meat','Sunkist','In Stock','Wholesale'),
('DoXauBananas','Mixed berries',10,48,'Small','Dairy','Dole','Out of Stock','Retail'),
('PhaleThuiGrapes','Mixed berries',4,28,'Medium','Dairy','Dole','Pre-Order','Direct to Consumer'),
('MongMoChinApples','Mixed berries',9,59,'Medium','Vegetables','HEB','Out of Stock','Wholesale'),
('PhaleThuiGrapes','Mixed berries',3,77,'Large','Meat','HEB','Out of Stock','Wholesale'),
('TimDepBerries','Tasty bananas',10,20,'Large','Meat','Sunkist','Out of Stock','Wholesale'),
('HeheXauGrapes','Mixed berries',5,95,'Small','Meat','Dole','In Stock','Direct to Consumer'),
('HaHaXauBerries','Fresh, juicy apples',8,58,'Small','Dairy','HEB','In Stock','Direct to Consumer'),
('MongMoThuiGrapes','Delicious grapes',1,75,'Small','Vegetables','Chiquita','In Stock','Wholesale'),
('TimChinBerries','Mixed berries',2,74,'Large','Meat','HEB','Pre-Order','Wholesale'),
('HaHaChinBerries','Fresh, juicy apples',9,70,'Medium','Dairy','HEB','Out of Stock','Retail'),
('PhaleNgonGrapes','Fresh, juicy apples',8,24,'Medium','Meat','Driscolls','Pre-Order','Wholesale'),
('VangXauBerries','Tasty bananas',8,43,'Medium','Dairy','Driscolls','In Stock','Wholesale'),
('HaHaSachBananas','Sweet, ripe oranges',5,86,'Small','Seafood','HEB','Pre-Order','Wholesale'),
('VangHuGrapes','Mixed berries',5,58,'Small','Seafood','Sunkist','In Stock','Wholesale'),
('TimThuiBananas','Fresh, juicy apples',4,26,'Large','Dairy','Dole','In Stock','Wholesale'),
('TimHuApples','Mixed berries',3,58,'Medium','Vegetables','Dole','In Stock','Direct to Consumer'),
('DoNgonApples','Mixed berries',1,89,'Large','Seafood','HEB','Pre-Order','Wholesale'),
('VangHuBananas','Sweet, ripe oranges',7,70,'Small','Dairy','Sunkist','Pre-Order','Direct to Consumer'),
('MongMoXanhApples','Sweet, ripe oranges',7,71,'Medium','Dairy','Chiquita','Out of Stock','Direct to Consumer'),
('HaHaXauOranges','Fresh, juicy apples',7,85,'Medium','Meat','Driscolls','In Stock','Wholesale'),
('TimDepApples','Mixed berries',1,34,'Large','Dairy','HEB','In Stock','Retail'),
('TimXanhBananas','Fresh, juicy apples',2,88,'Small','Meat','HEB','Pre-Order','Retail'),
('HeheNgonApples','Sweet, ripe oranges',10,41,'Large','Dairy','Dole','Pre-Order','Direct to Consumer'),
('HaHaXauBananas','Fresh, juicy apples',7,26,'Large','Meat','Dole','Pre-Order','Direct to Consumer'),
('HeheNgonGrapes','Fresh, juicy apples',9,31,'Small','Meat','Dole','Pre-Order','Direct to Consumer'),
('MongMoChinBerries','Tasty bananas',8,96,'Small','Seafood','Sunkist','Out of Stock','Retail'),
('HeheXanhGrapes','Mixed berries',7,72,'Large','Dairy','HEB','Out of Stock','Direct to Consumer'),
('PhaleChinBananas','Delicious grapes',10,27,'Small','Dairy','Dole','Pre-Order','Direct to Consumer'),
('HeheNgonApples','Sweet, ripe oranges',6,53,'Large','Vegetables','Chiquita','Pre-Order','Direct to Consumer'),
('TimXanhOranges','Mixed berries',7,82,'Large','Seafood','Dole','In Stock','Direct to Consumer'),
('VangNgonGrapes','Sweet, ripe oranges',8,56,'Large','Seafood','Sunkist','Pre-Order','Wholesale'),
('HeheSachBerries','Sweet, ripe oranges',8,12,'Medium','Dairy','HEB','Pre-Order','Wholesale'),
('HihiThuiGrapes','Sweet, ripe oranges',1,15,'Large','Fruits','Driscolls','Pre-Order','Direct to Consumer'),
('MongMoNgonApples','Delicious grapes',6,45,'Large','Seafood','HEB','Out of Stock','Wholesale'),
('VangHuGrapes','Mixed berries',3,72,'Medium','Meat','Dole','In Stock','Wholesale'),
('MongMoHuOranges','Tasty bananas',7,55,'Large','Fruits','Driscolls','Out of Stock','Retail'),
('HeheHuGrapes','Tasty bananas',4,90,'Medium','Seafood','Sunkist','Pre-Order','Wholesale'),
('HeheThuiGrapes','Sweet, ripe oranges',9,44,'Large','Vegetables','Sunkist','Out of Stock','Wholesale'),
('DoSachOranges','Delicious grapes',5,61,'Small','Dairy','Driscolls','Out of Stock','Direct to Consumer'),
('VangThuiGrapes','Fresh, juicy apples',9,84,'Small','Fruits','HEB','Pre-Order','Wholesale'),
('VangXauBananas','Delicious grapes',6,45,'Small','Dairy','Sunkist','Pre-Order','Wholesale'),
('PhaleNgonBerries','Tasty bananas',2,13,'Small','Dairy','Chiquita','In Stock','Wholesale'),
('HaHaChinBananas','Mixed berries',5,57,'Small','Meat','Chiquita','Pre-Order','Wholesale'),
('TimXanhApples','Mixed berries',1,98,'Medium','Meat','Sunkist','Pre-Order','Wholesale'),
('PhaleXanhBananas','Tasty bananas',7,58,'Medium','Meat','HEB','Pre-Order','Wholesale'),
('HaHaNgonBananas','Fresh, juicy apples',7,85,'Small','Vegetables','Chiquita','Out of Stock','Direct to Consumer'),
('MongMoThuiBananas','Mixed berries',5,30,'Large','Vegetables','Sunkist','Out of Stock','Retail'),
('VangThuiBerries','Delicious grapes',2,32,'Small','Meat','Dole','In Stock','Direct to Consumer'),
('HeheXanhOranges','Sweet, ripe oranges',1,13,'Large','Fruits','Chiquita','Pre-Order','Retail'),
('TimDepBerries','Sweet, ripe oranges',10,64,'Medium','Meat','Driscolls','Out of Stock','Retail'),
('MongMoDepApples','Fresh, juicy apples',2,65,'Small','Vegetables','Dole','Out of Stock','Retail'),
('MongMoChinOranges','Fresh, juicy apples',4,16,'Medium','Seafood','Dole','Out of Stock','Direct to Consumer'),
('HihiXanhBerries','Mixed berries',6,15,'Medium','Meat','Chiquita','In Stock','Wholesale'),
('DoHuBananas','Sweet, ripe oranges',10,94,'Medium','Vegetables','Driscolls','Pre-Order','Direct to Consumer'),
('TimChinOranges','Fresh, juicy apples',2,75,'Medium','Vegetables','Dole','Pre-Order','Wholesale'),
('HeheXauBerries','Sweet, ripe oranges',6,50,'Medium','Fruits','HEB','Out of Stock','Retail'),
('HaHaSachBerries','Mixed berries',4,44,'Small','Fruits','Sunkist','Out of Stock','Retail'),
('HeheThuiBerries','Fresh, juicy apples',9,85,'Small','Vegetables','Driscolls','In Stock','Wholesale'),
('HihiXauGrapes','Fresh, juicy apples',9,83,'Medium','Seafood','Dole','In Stock','Direct to Consumer'),
('VangThuiOranges','Tasty bananas',5,76,'Small','Fruits','Sunkist','In Stock','Retail'),
('VangSachApples','Tasty bananas',3,74,'Small','Vegetables','Driscolls','In Stock','Wholesale'),
('DoSachGrapes','Sweet, ripe oranges',6,27,'Medium','Fruits','Dole','Pre-Order','Retail'),
('VangXauGrapes','Mixed berries',1,89,'Small','Dairy','Driscolls','In Stock','Wholesale'),
('PhaleXauGrapes','Fresh, juicy apples',5,97,'Small','Fruits','Sunkist','In Stock','Retail'),
('VangSachApples','Tasty bananas',6,30,'Small','Meat','Chiquita','Out of Stock','Direct to Consumer'),
('HaHaDepGrapes','Tasty bananas',1,62,'Large','Fruits','Chiquita','In Stock','Retail'),
('HaHaNgonApples','Delicious grapes',2,23,'Medium','Dairy','Dole','In Stock','Direct to Consumer'),
('HaHaNgonBerries','Tasty bananas',2,93,'Small','Dairy','Driscolls','Out of Stock','Retail'),
('PhaleChinOranges','Tasty bananas',1,73,'Medium','Fruits','Dole','Out of Stock','Wholesale'),
('HaHaHuBananas','Fresh, juicy apples',5,48,'Large','Vegetables','HEB','In Stock','Direct to Consumer'),
('VangNgonGrapes','Tasty bananas',8,34,'Medium','Seafood','Driscolls','Out of Stock','Direct to Consumer'),
('MongMoNgonApples','Delicious grapes',8,57,'Large','Meat','Driscolls','Pre-Order','Direct to Consumer'),
('HeheSachBerries','Delicious grapes',3,39,'Medium','Seafood','Driscolls','Out of Stock','Retail'),
('VangThuiOranges','Mixed berries',4,37,'Large','Dairy','Sunkist','Pre-Order','Retail'),
('DoHuGrapes','Fresh, juicy apples',1,49,'Large','Dairy','Chiquita','Out of Stock','Direct to Consumer'),
('TimHuBananas','Mixed berries',6,24,'Medium','Dairy','HEB','Pre-Order','Direct to Consumer'),
('TimChinBananas','Fresh, juicy apples',10,50,'Small','Vegetables','Dole','In Stock','Direct to Consumer'),
('PhaleChinGrapes','Tasty bananas',10,91,'Medium','Meat','Chiquita','Pre-Order','Wholesale'),
('HaHaNgonOranges','Tasty bananas',1,50,'Large','Fruits','Sunkist','In Stock','Wholesale'),
('TimNgonBananas','Sweet, ripe oranges',4,28,'Large','Dairy','Chiquita','In Stock','Wholesale'),
('HeheNgonOranges','Mixed berries',2,13,'Small','Meat','Dole','Out of Stock','Direct to Consumer'),
('VangXanhBerries','Delicious grapes',8,47,'Large','Dairy','Dole','Out of Stock','Wholesale'),
('DoHuGrapes','Delicious grapes',8,51,'Medium','Dairy','HEB','In Stock','Direct to Consumer'),
('VangSachBananas','Delicious grapes',8,100,'Large','Meat','Dole','In Stock','Retail'),
('TimXanhOranges','Sweet, ripe oranges',4,49,'Small','Fruits','HEB','Out of Stock','Direct to Consumer'),
('VangXanhApples','Fresh, juicy apples',2,84,'Small','Seafood','HEB','Pre-Order','Wholesale'),
('HaHaDepApples','Sweet, ripe oranges',2,26,'Medium','Meat','HEB','Pre-Order','Wholesale'),
('DoHuApples','Delicious grapes',2,12,'Medium','Dairy','Driscolls','Out of Stock','Wholesale'),
('HeheDepBananas','Mixed berries',5,46,'Large','Meat','Sunkist','In Stock','Wholesale'),
('VangSachGrapes','Delicious grapes',3,80,'Large','Fruits','Chiquita','In Stock','Wholesale'),
('DoThuiOranges','Mixed berries',5,18,'Small','Seafood','Sunkist','Out of Stock','Retail'),
('VangNgonBananas','Delicious grapes',6,29,'Small','Dairy','Dole','Pre-Order','Wholesale'),
('DoSachBerries','Mixed berries',8,97,'Small','Meat','Sunkist','In Stock','Direct to Consumer'),
('HaHaNgonOranges','Fresh, juicy apples',3,93,'Medium','Vegetables','Driscolls','In Stock','Wholesale'),
('PhaleChinOranges','Delicious grapes',3,92,'Small','Fruits','Chiquita','Pre-Order','Retail'),
('TimSachOranges','Fresh, juicy apples',1,39,'Small','Vegetables','Chiquita','Out of Stock','Direct to Consumer'),
('HihiXanhOranges','Fresh, juicy apples',7,44,'Large','Fruits','Dole','Pre-Order','Wholesale'),
('HeheXanhBerries','Fresh, juicy apples',3,46,'Large','Meat','Chiquita','Out of Stock','Retail'),
('VangSachGrapes','Mixed berries',9,50,'Large','Vegetables','Dole','Pre-Order','Wholesale'),
('MongMoXauBerries','Delicious grapes',2,63,'Medium','Meat','HEB','Pre-Order','Retail'),
('HihiNgonBananas','Mixed berries',3,19,'Medium','Fruits','Dole','Out of Stock','Direct to Consumer'),
('VangDepBerries','Mixed berries',3,98,'Large','Meat','Driscolls','In Stock','Wholesale'),
('DoXauBerries','Tasty bananas',10,45,'Medium','Dairy','Driscolls','In Stock','Direct to Consumer'),
('DoNgonBananas','Fresh, juicy apples',6,50,'Large','Fruits','Sunkist','Out of Stock','Direct to Consumer'),
('HihiXanhBerries','Fresh, juicy apples',3,42,'Large','Seafood','Sunkist','Out of Stock','Retail'),
('HaHaSachGrapes','Mixed berries',10,87,'Small','Dairy','Dole','In Stock','Retail'),
('PhaleNgonOranges','Sweet, ripe oranges',2,19,'Large','Vegetables','Driscolls','In Stock','Retail'),
('HihiNgonBerries','Sweet, ripe oranges',9,22,'Large','Fruits','Driscolls','Pre-Order','Retail'),
('HaHaNgonApples','Sweet, ripe oranges',5,97,'Large','Meat','Sunkist','Pre-Order','Retail'),
('TimXauApples','Tasty bananas',9,34,'Large','Vegetables','Driscolls','In Stock','Retail'),
('HihiDepApples','Mixed berries',7,40,'Small','Seafood','Chiquita','In Stock','Retail'),
('PhaleChinBerries','Delicious grapes',9,48,'Small','Fruits','Chiquita','In Stock','Wholesale'),
('PhaleXanhGrapes','Sweet, ripe oranges',4,40,'Small','Seafood','Chiquita','Out of Stock','Direct to Consumer'),
('HaHaDepApples','Fresh, juicy apples',8,36,'Small','Fruits','HEB','In Stock','Retail'),
('DoXauApples','Delicious grapes',6,39,'Large','Dairy','Driscolls','Out of Stock','Direct to Consumer'),
('TimXauBananas','Mixed berries',10,17,'Large','Vegetables','Driscolls','Pre-Order','Retail'),
('DoHuBerries','Delicious grapes',3,13,'Medium','Vegetables','Sunkist','In Stock','Direct to Consumer'),
('TimXauApples','Delicious grapes',2,19,'Large','Fruits','HEB','Pre-Order','Direct to Consumer'),
('DoSachOranges','Fresh, juicy apples',8,12,'Small','Meat','HEB','In Stock','Retail'),
('HeheThuiApples','Delicious grapes',2,49,'Medium','Fruits','Chiquita','Pre-Order','Wholesale'),
('MongMoChinApples','Sweet, ripe oranges',10,16,'Large','Fruits','Chiquita','Pre-Order','Wholesale'),
('MongMoSachBananas','Tasty bananas',2,82,'Small','Vegetables','Dole','In Stock','Direct to Consumer'),
('DoThuiBerries','Delicious grapes',1,76,'Medium','Fruits','Sunkist','Out of Stock','Wholesale'),
('HaHaXauGrapes','Sweet, ripe oranges',4,25,'Small','Seafood','Dole','Out of Stock','Wholesale'),
('HaHaXanhGrapes','Sweet, ripe oranges',7,87,'Small','Fruits','Chiquita','Out of Stock','Direct to Consumer'),
('MongMoXanhBananas','Sweet, ripe oranges',4,72,'Large','Fruits','Sunkist','In Stock','Wholesale'),
('HeheChinOranges','Fresh, juicy apples',3,23,'Medium','Seafood','HEB','In Stock','Wholesale'),
('VangDepBananas','Mixed berries',1,60,'Medium','Meat','HEB','In Stock','Direct to Consumer'),
('DoHuOranges','Tasty bananas',1,86,'Small','Fruits','Chiquita','In Stock','Retail'),
('PhaleXauBerries','Mixed berries',4,17,'Small','Vegetables','Chiquita','Out of Stock','Direct to Consumer'),
('DoHuBananas','Fresh, juicy apples',7,57,'Small','Fruits','Chiquita','Out of Stock','Retail'),
('DoSachGrapes','Mixed berries',5,46,'Small','Meat','Chiquita','Pre-Order','Direct to Consumer'),
('PhaleDepApples','Fresh, juicy apples',7,11,'Small','Vegetables','HEB','Pre-Order','Wholesale'),
('HihiHuApples','Tasty bananas',7,88,'Large','Seafood','Driscolls','In Stock','Direct to Consumer'),
('MongMoXauApples','Sweet, ripe oranges',10,16,'Small','Meat','Driscolls','Out of Stock','Direct to Consumer'),
('HaHaHuBerries','Mixed berries',8,70,'Large','Dairy','Dole','Pre-Order','Direct to Consumer'),
('VangThuiGrapes','Tasty bananas',2,23,'Medium','Fruits','HEB','In Stock','Retail'),
('VangXauGrapes','Delicious grapes',7,14,'Small','Fruits','Chiquita','In Stock','Wholesale'),
('TimXauGrapes','Tasty bananas',8,46,'Medium','Meat','Sunkist','In Stock','Wholesale'),
('TimChinBananas','Mixed berries',10,50,'Small','Fruits','Chiquita','In Stock','Wholesale'),
('PhaleXauGrapes','Mixed berries',5,33,'Small','Dairy','Driscolls','Pre-Order','Wholesale'),
('HihiChinBananas','Sweet, ripe oranges',9,54,'Small','Meat','HEB','Pre-Order','Direct to Consumer'),
('HeheChinBerries','Fresh, juicy apples',1,72,'Small','Seafood','Sunkist','Pre-Order','Retail'),
('VangXanhApples','Delicious grapes',9,78,'Small','Fruits','Chiquita','Out of Stock','Direct to Consumer'),
('VangChinApples','Sweet, ripe oranges',5,27,'Medium','Vegetables','Chiquita','Out of Stock','Wholesale'),
('HihiXanhApples','Delicious grapes',4,33,'Large','Fruits','Chiquita','In Stock','Wholesale'),
('TimNgonOranges','Fresh, juicy apples',6,39,'Small','Meat','Dole','Out of Stock','Wholesale'),
('TimSachGrapes','Fresh, juicy apples',3,100,'Large','Meat','Dole','Pre-Order','Direct to Consumer'),
('HeheXanhApples','Fresh, juicy apples',2,29,'Small','Seafood','Sunkist','Out of Stock','Direct to Consumer'),
('HihiXauGrapes','Fresh, juicy apples',10,90,'Small','Meat','Sunkist','Out of Stock','Retail'),
('VangThuiGrapes','Mixed berries',4,10,'Small','Fruits','Dole','In Stock','Wholesale'),
('VangSachOranges','Tasty bananas',3,21,'Small','Dairy','Dole','Out of Stock','Retail'),
('HeheSachBananas','Mixed berries',4,74,'Small','Dairy','HEB','In Stock','Retail'),
('HaHaHuGrapes','Tasty bananas',9,74,'Medium','Vegetables','Dole','Out of Stock','Retail'),
('TimDepBananas','Mixed berries',3,70,'Small','Dairy','Sunkist','Pre-Order','Retail'),
('VangXauGrapes','Delicious grapes',4,46,'Large','Meat','Driscolls','In Stock','Retail'),
('HaHaSachBananas','Fresh, juicy apples',8,32,'Medium','Seafood','HEB','Out of Stock','Retail'),
('PhaleNgonGrapes','Delicious grapes',7,43,'Small','Dairy','HEB','Out of Stock','Retail'),
('TimXanhOranges','Fresh, juicy apples',1,29,'Small','Dairy','HEB','Pre-Order','Direct to Consumer'),
('PhaleThuiBerries','Tasty bananas',6,92,'Large','Dairy','Dole','In Stock','Retail'),
('MongMoDepOranges','Tasty bananas',7,62,'Medium','Fruits','Sunkist','Out of Stock','Direct to Consumer'),
('HeheSachOranges','Fresh, juicy apples',6,13,'Large','Meat','Sunkist','In Stock','Wholesale'),
('HihiChinBerries','Mixed berries',9,11,'Medium','Fruits','Chiquita','Pre-Order','Retail'),
('MongMoNgonGrapes','Mixed berries',4,69,'Small','Seafood','Sunkist','In Stock','Wholesale'),
('HaHaXanhBananas','Mixed berries',6,77,'Medium','Seafood','Driscolls','Out of Stock','Wholesale'),
('HihiXanhBerries','Tasty bananas',2,97,'Small','Fruits','HEB','In Stock','Retail'),
('HihiSachBananas','Mixed berries',6,32,'Medium','Dairy','Chiquita','Out of Stock','Wholesale'),
('HihiSachApples','Mixed berries',4,23,'Small','Seafood','Driscolls','In Stock','Retail'),
('VangChinBerries','Sweet, ripe oranges',4,11,'Large','Seafood','Chiquita','In Stock','Direct to Consumer'),
('HeheSachBerries','Delicious grapes',5,21,'Medium','Vegetables','HEB','In Stock','Wholesale'),
('MongMoDepOranges','Delicious grapes',9,39,'Small','Meat','Sunkist','Pre-Order','Direct to Consumer'),
('HihiHuOranges','Mixed berries',6,76,'Medium','Meat','HEB','In Stock','Wholesale'),
('TimChinBananas','Delicious grapes',8,36,'Medium','Seafood','Dole','In Stock','Direct to Consumer'),
('TimXauGrapes','Delicious grapes',4,74,'Medium','Dairy','Dole','Pre-Order','Wholesale'),
('VangHuGrapes','Mixed berries',9,19,'Large','Seafood','Sunkist','Out of Stock','Retail'),
('HaHaSachGrapes','Tasty bananas',1,44,'Small','Seafood','Dole','Pre-Order','Retail'),
('HihiXauBananas','Sweet, ripe oranges',6,18,'Medium','Dairy','Dole','Out of Stock','Wholesale'),
('MongMoXauGrapes','Delicious grapes',10,11,'Medium','Dairy','Chiquita','Out of Stock','Wholesale'),
('TimSachBananas','Fresh, juicy apples',9,58,'Large','Seafood','Chiquita','In Stock','Direct to Consumer'),
('HeheNgonApples','Sweet, ripe oranges',2,54,'Small','Fruits','HEB','Out of Stock','Wholesale'),
('DoNgonApples','Tasty bananas',7,71,'Large','Seafood','Driscolls','Pre-Order','Wholesale'),
('HeheXauApples','Fresh, juicy apples',1,95,'Medium','Dairy','HEB','Pre-Order','Wholesale'),
('TimChinBananas','Delicious grapes',5,30,'Large','Meat','Driscolls','Pre-Order','Wholesale'),
('HaHaHuOranges','Mixed berries',8,97,'Small','Fruits','Dole','Out of Stock','Wholesale'),
('HeheHuBerries','Fresh, juicy apples',9,76,'Small','Fruits','Sunkist','Pre-Order','Direct to Consumer'),
('MongMoXauBananas','Fresh, juicy apples',8,94,'Small','Dairy','HEB','Out of Stock','Wholesale'),
('PhaleHuApples','Fresh, juicy apples',9,46,'Large','Fruits','Driscolls','In Stock','Direct to Consumer'),
('PhaleNgonBananas','Tasty bananas',9,86,'Large','Seafood','Driscolls','In Stock','Wholesale'),
('HaHaSachBerries','Mixed berries',5,56,'Medium','Vegetables','Chiquita','Out of Stock','Wholesale'),
('HihiXanhBerries','Fresh, juicy apples',5,18,'Medium','Seafood','HEB','Out of Stock','Wholesale'),
('PhaleXanhBananas','Mixed berries',5,45,'Medium','Vegetables','HEB','In Stock','Direct to Consumer'),
('DoChinBananas','Sweet, ripe oranges',9,58,'Large','Seafood','Chiquita','In Stock','Retail'),
('DoNgonGrapes','Delicious grapes',3,78,'Small','Fruits','Driscolls','Out of Stock','Direct to Consumer'),
('PhaleXauBananas','Sweet, ripe oranges',4,91,'Large','Seafood','Driscolls','Pre-Order','Wholesale'),
('HihiSachOranges','Delicious grapes',1,17,'Medium','Dairy','Sunkist','Pre-Order','Wholesale'),
('TimSachOranges','Mixed berries',6,57,'Small','Vegetables','Chiquita','Pre-Order','Direct to Consumer'),
('HihiChinBerries','Tasty bananas',7,68,'Large','Meat','Dole','Out of Stock','Wholesale'),
('HeheNgonBerries','Sweet, ripe oranges',8,46,'Medium','Seafood','Driscolls','Pre-Order','Wholesale'),
('HeheSachGrapes','Delicious grapes',1,19,'Large','Dairy','Driscolls','Pre-Order','Wholesale'),
('DoChinApples','Sweet, ripe oranges',4,57,'Medium','Fruits','Dole','Pre-Order','Retail'),
('DoNgonBerries','Delicious grapes',9,27,'Large','Meat','HEB','Pre-Order','Retail'),
('HihiThuiApples','Sweet, ripe oranges',8,64,'Small','Meat','HEB','Pre-Order','Retail'),
('MongMoHuApples','Mixed berries',10,89,'Medium','Meat','Sunkist','Out of Stock','Direct to Consumer'),
('HaHaXauBerries','Delicious grapes',10,91,'Large','Meat','Chiquita','In Stock','Retail'),
('MongMoHuOranges','Fresh, juicy apples',1,67,'Large','Meat','Sunkist','In Stock','Wholesale'),
('HeheHuGrapes','Tasty bananas',10,58,'Large','Meat','Chiquita','In Stock','Retail'),
('PhaleChinBerries','Fresh, juicy apples',7,64,'Medium','Fruits','HEB','In Stock','Wholesale'),
('HaHaThuiGrapes','Delicious grapes',3,46,'Small','Vegetables','HEB','In Stock','Direct to Consumer'),
('HeheNgonGrapes','Mixed berries',8,98,'Medium','Dairy','Driscolls','Out of Stock','Retail'),
('HeheNgonGrapes','Sweet, ripe oranges',8,88,'Small','Dairy','Sunkist','Pre-Order','Direct to Consumer'),
('DoSachBerries','Mixed berries',6,46,'Large','Meat','Driscolls','Out of Stock','Direct to Consumer'),
('TimXanhOranges','Mixed berries',10,94,'Medium','Meat','Dole','Out of Stock','Retail'),
('HeheHuOranges','Tasty bananas',7,86,'Small','Seafood','Chiquita','Pre-Order','Wholesale'),
('TimXanhBananas','Sweet, ripe oranges',2,69,'Large','Seafood','Driscolls','Out of Stock','Direct to Consumer'),
('HeheSachBerries','Fresh, juicy apples',8,90,'Medium','Fruits','Dole','Out of Stock','Direct to Consumer'),
('PhaleSachGrapes','Mixed berries',10,65,'Small','Fruits','Chiquita','Out of Stock','Wholesale'),
('MongMoChinBerries','Mixed berries',6,47,'Large','Dairy','Dole','In Stock','Retail'),
('HeheThuiApples','Sweet, ripe oranges',6,100,'Small','Vegetables','Sunkist','In Stock','Direct to Consumer'),
('HaHaDepBerries','Sweet, ripe oranges',5,10,'Small','Meat','Chiquita','In Stock','Wholesale'),
('VangHuApples','Sweet, ripe oranges',9,93,'Small','Fruits','Sunkist','Out of Stock','Retail'),
('HihiXauBerries','Delicious grapes',6,77,'Large','Meat','Chiquita','In Stock','Retail'),
('HihiDepBerries','Fresh, juicy apples',7,23,'Large','Dairy','HEB','Pre-Order','Wholesale'),
('HaHaChinOranges','Tasty bananas',2,70,'Medium','Vegetables','Sunkist','In Stock','Wholesale'),
('DoChinGrapes','Tasty bananas',4,55,'Medium','Meat','Sunkist','Pre-Order','Wholesale'),
('HaHaSachGrapes','Fresh, juicy apples',2,67,'Small','Seafood','HEB','Pre-Order','Wholesale'),
('HeheHuApples','Delicious grapes',9,14,'Large','Fruits','HEB','Pre-Order','Wholesale'),
('PhaleDepApples','Delicious grapes',1,24,'Small','Meat','Driscolls','Out of Stock','Direct to Consumer'),
('MongMoXanhOranges','Mixed berries',2,78,'Medium','Meat','Chiquita','Out of Stock','Direct to Consumer'),
('PhaleChinOranges','Fresh, juicy apples',2,63,'Large','Meat','Driscolls','In Stock','Direct to Consumer'),
('DoHuGrapes','Fresh, juicy apples',4,58,'Medium','Meat','Chiquita','Pre-Order','Wholesale'),
('DoChinOranges','Sweet, ripe oranges',6,63,'Medium','Meat','HEB','In Stock','Direct to Consumer'),
('TimHuGrapes','Mixed berries',8,81,'Small','Dairy','Sunkist','In Stock','Direct to Consumer'),
('HaHaNgonBerries','Tasty bananas',5,16,'Large','Vegetables','Dole','Out of Stock','Wholesale'),
('DoChinOranges','Delicious grapes',1,63,'Medium','Seafood','Driscolls','In Stock','Wholesale'),
('HeheThuiBerries','Tasty bananas',2,98,'Medium','Meat','Dole','Out of Stock','Retail'),
('MongMoNgonOranges','Delicious grapes',2,44,'Medium','Fruits','Sunkist','In Stock','Retail'),
('MongMoChinOranges','Tasty bananas',5,86,'Medium','Fruits','Chiquita','Out of Stock','Direct to Consumer'),
('TimDepApples','Fresh, juicy apples',7,11,'Large','Fruits','Driscolls','Pre-Order','Direct to Consumer'),
('TimChinGrapes','Fresh, juicy apples',4,78,'Large','Dairy','Sunkist','Pre-Order','Retail'),
('HihiChinGrapes','Delicious grapes',7,94,'Medium','Meat','Chiquita','Pre-Order','Retail'),
('HaHaNgonBerries','Mixed berries',1,63,'Large','Vegetables','Chiquita','Out of Stock','Wholesale'),
('HeheChinApples','Delicious grapes',9,97,'Medium','Fruits','HEB','Out of Stock','Direct to Consumer'),
('HaHaNgonApples','Mixed berries',6,82,'Large','Vegetables','Sunkist','Out of Stock','Retail'),
('VangThuiBananas','Delicious grapes',3,58,'Small','Seafood','Chiquita','In Stock','Retail'),
('VangDepOranges','Sweet, ripe oranges',3,94,'Medium','Seafood','Driscolls','Pre-Order','Retail'),
('PhaleSachOranges','Fresh, juicy apples',3,53,'Large','Seafood','Dole','In Stock','Wholesale'),
('HaHaThuiBananas','Mixed berries',10,99,'Small','Vegetables','Sunkist','Out of Stock','Retail'),
('PhaleThuiApples','Tasty bananas',4,75,'Large','Dairy','HEB','In Stock','Direct to Consumer'),
('PhaleXauBerries','Fresh, juicy apples',9,41,'Medium','Meat','HEB','Pre-Order','Retail'),
('HihiNgonBerries','Sweet, ripe oranges',10,84,'Medium','Meat','Sunkist','Pre-Order','Retail'),
('VangNgonApples','Fresh, juicy apples',7,60,'Large','Meat','Driscolls','Pre-Order','Direct to Consumer'),
('VangSachApples','Tasty bananas',6,60,'Medium','Fruits','Sunkist','Out of Stock','Wholesale'),
('HihiHuOranges','Tasty bananas',5,29,'Small','Dairy','HEB','Out of Stock','Retail'),
('MongMoChinApples','Mixed berries',4,92,'Medium','Seafood','Driscolls','Pre-Order','Wholesale'),
('VangXauApples','Fresh, juicy apples',2,85,'Medium','Fruits','Driscolls','Pre-Order','Retail'),
('MongMoThuiBerries','Sweet, ripe oranges',1,48,'Large','Meat','HEB','Out of Stock','Wholesale'),
('VangNgonBananas','Mixed berries',3,72,'Medium','Fruits','Dole','Pre-Order','Direct to Consumer'),
('PhaleThuiGrapes','Delicious grapes',9,91,'Large','Dairy','Sunkist','Out of Stock','Wholesale'),
('HaHaChinBananas','Delicious grapes',9,54,'Medium','Meat','Driscolls','Pre-Order','Direct to Consumer'),
('MongMoXanhApples','Delicious grapes',6,34,'Medium','Meat','Chiquita','Pre-Order','Direct to Consumer'),
('TimXauApples','Fresh, juicy apples',7,82,'Large','Seafood','HEB','In Stock','Wholesale'),
('PhaleHuBananas','Tasty bananas',1,57,'Medium','Meat','HEB','Out of Stock','Retail'),
('MongMoXauBananas','Fresh, juicy apples',1,17,'Large','Meat','HEB','In Stock','Wholesale'),
('PhaleSachBerries','Mixed berries',4,26,'Small','Vegetables','Dole','Pre-Order','Direct to Consumer'),
('VangNgonBananas','Delicious grapes',9,47,'Small','Seafood','Driscolls','Pre-Order','Direct to Consumer'),
('HaHaThuiBananas','Tasty bananas',6,60,'Small','Fruits','Sunkist','Out of Stock','Wholesale'),
('PhaleChinGrapes','Delicious grapes',5,80,'Medium','Fruits','Sunkist','Out of Stock','Wholesale'),
('VangThuiBerries','Fresh, juicy apples',4,58,'Small','Meat','Chiquita','Pre-Order','Wholesale'),
('VangNgonGrapes','Tasty bananas',6,17,'Large','Vegetables','Dole','Out of Stock','Direct to Consumer'),
('HeheSachApples','Delicious grapes',4,89,'Small','Vegetables','Sunkist','In Stock','Retail'),
('TimChinBananas','Mixed berries',5,83,'Small','Meat','Driscolls','Out of Stock','Retail'),
('HihiChinApples','Tasty bananas',2,15,'Medium','Fruits','Dole','In Stock','Wholesale'),
('HaHaNgonBerries','Tasty bananas',1,16,'Small','Seafood','HEB','Pre-Order','Wholesale'),
('PhaleChinOranges','Sweet, ripe oranges',4,44,'Large','Fruits','Driscolls','Pre-Order','Direct to Consumer'),
('HaHaChinBerries','Fresh, juicy apples',2,35,'Medium','Vegetables','Dole','Out of Stock','Wholesale'),
('HeheSachBananas','Sweet, ripe oranges',9,34,'Medium','Meat','Chiquita','Pre-Order','Direct to Consumer'),
('HeheHuOranges','Mixed berries',1,25,'Small','Fruits','Driscolls','In Stock','Wholesale'),
('PhaleSachApples','Delicious grapes',4,87,'Large','Seafood','HEB','Pre-Order','Retail'),
('HaHaSachGrapes','Mixed berries',1,36,'Small','Fruits','Sunkist','Out of Stock','Direct to Consumer'),
('HaHaChinBerries','Tasty bananas',8,45,'Large','Seafood','Sunkist','In Stock','Wholesale'),
('MongMoXanhApples','Mixed berries',9,51,'Small','Fruits','HEB','Pre-Order','Retail'),
('HeheSachGrapes','Fresh, juicy apples',5,98,'Large','Seafood','Sunkist','In Stock','Direct to Consumer'),
('VangNgonBerries','Tasty bananas',6,67,'Large','Vegetables','Chiquita','In Stock','Wholesale'),
('HihiThuiApples','Fresh, juicy apples',9,84,'Large','Fruits','Chiquita','Out of Stock','Wholesale'),
('HihiThuiOranges','Sweet, ripe oranges',8,47,'Small','Dairy','Chiquita','Out of Stock','Wholesale'),
('DoSachBerries','Mixed berries',2,14,'Large','Dairy','Chiquita','Out of Stock','Retail'),
('TimXanhGrapes','Sweet, ripe oranges',9,25,'Large','Fruits','HEB','Pre-Order','Direct to Consumer'),
('TimNgonGrapes','Fresh, juicy apples',3,76,'Large','Dairy','Dole','Pre-Order','Retail'),
('PhaleDepOranges','Fresh, juicy apples',5,80,'Medium','Meat','HEB','Out of Stock','Retail'),
('DoHuBerries','Fresh, juicy apples',2,22,'Medium','Dairy','Dole','In Stock','Retail'),
('DoChinGrapes','Mixed berries',5,68,'Medium','Meat','Dole','In Stock','Wholesale'),
('TimXanhOranges','Fresh, juicy apples',8,39,'Medium','Dairy','HEB','Pre-Order','Wholesale'),
('MongMoThuiBananas','Delicious grapes',6,58,'Large','Seafood','Dole','Out of Stock','Wholesale'),
('HeheXauGrapes','Mixed berries',8,78,'Small','Seafood','Dole','Out of Stock','Direct to Consumer'),
('MongMoThuiGrapes','Tasty bananas',5,30,'Medium','Dairy','Sunkist','In Stock','Wholesale'),
('VangHuApples','Tasty bananas',6,82,'Small','Vegetables','Sunkist','In Stock','Wholesale'),
('HaHaNgonApples','Delicious grapes',9,43,'Large','Meat','HEB','Out of Stock','Retail'),
('HihiXauOranges','Fresh, juicy apples',3,83,'Large','Vegetables','Driscolls','Out of Stock','Retail'),
('HihiNgonBerries','Mixed berries',6,42,'Small','Seafood','Chiquita','Pre-Order','Wholesale'),
('MongMoNgonBerries','Mixed berries',10,71,'Small','Meat','Sunkist','In Stock','Retail'),
('MongMoChinOranges','Fresh, juicy apples',3,25,'Large','Fruits','HEB','Out of Stock','Retail'),
('DoChinBananas','Mixed berries',6,85,'Large','Seafood','Driscolls','Pre-Order','Retail'),
('HeheDepApples','Mixed berries',2,42,'Small','Vegetables','Driscolls','Pre-Order','Direct to Consumer'),
('HihiXanhBananas','Sweet, ripe oranges',7,27,'Small','Seafood','Sunkist','Pre-Order','Retail'),
('HaHaXanhOranges','Tasty bananas',3,35,'Small','Dairy','HEB','In Stock','Retail'),
('HihiXanhBananas','Sweet, ripe oranges',7,87,'Medium','Dairy','Chiquita','Pre-Order','Wholesale'),
('MongMoThuiBananas','Sweet, ripe oranges',7,73,'Medium','Seafood','Sunkist','Out of Stock','Wholesale'),
('HeheNgonBerries','Delicious grapes',5,69,'Small','Vegetables','Dole','Pre-Order','Wholesale'),
('HaHaHuGrapes','Delicious grapes',2,77,'Large','Meat','Dole','Out of Stock','Wholesale'),
('VangChinOranges','Fresh, juicy apples',5,40,'Large','Seafood','Driscolls','In Stock','Direct to Consumer'),
('VangNgonBananas','Delicious grapes',4,88,'Medium','Seafood','HEB','Out of Stock','Retail'),
('DoNgonBerries','Tasty bananas',1,22,'Large','Seafood','HEB','Out of Stock','Direct to Consumer'),
('HaHaHuOranges','Delicious grapes',5,52,'Medium','Meat','Sunkist','Pre-Order','Wholesale'),
('MongMoChinBerries','Fresh, juicy apples',10,26,'Large','Dairy','Dole','Pre-Order','Retail'),
('TimXauApples','Delicious grapes',3,44,'Small','Dairy','Driscolls','In Stock','Wholesale'),
('DoNgonBananas','Fresh, juicy apples',1,27,'Large','Fruits','HEB','Out of Stock','Retail'),
('MongMoHuBerries','Sweet, ripe oranges',10,41,'Large','Meat','Dole','Pre-Order','Wholesale'),
('HihiChinApples','Delicious grapes',2,78,'Medium','Seafood','HEB','Out of Stock','Direct to Consumer'),
('VangSachBananas','Mixed berries',6,98,'Small','Fruits','Chiquita','Pre-Order','Direct to Consumer'),
('PhaleNgonBerries','Sweet, ripe oranges',6,43,'Large','Dairy','Dole','Out of Stock','Retail'),
('HihiXanhBananas','Mixed berries',5,29,'Large','Seafood','Driscolls','In Stock','Direct to Consumer'),
('HaHaSachGrapes','Fresh, juicy apples',8,100,'Large','Fruits','Dole','In Stock','Wholesale'),
('VangXanhGrapes','Fresh, juicy apples',4,91,'Medium','Vegetables','Dole','In Stock','Wholesale'),
('PhaleHuGrapes','Delicious grapes',1,94,'Medium','Vegetables','Sunkist','Out of Stock','Wholesale'),
('TimChinApples','Fresh, juicy apples',5,98,'Large','Fruits','Driscolls','In Stock','Retail'),
('MongMoChinBananas','Fresh, juicy apples',6,31,'Medium','Dairy','Chiquita','Out of Stock','Retail'),
('HeheNgonOranges','Mixed berries',3,89,'Small','Meat','Chiquita','Out of Stock','Wholesale'),
('HihiHuBananas','Fresh, juicy apples',3,93,'Medium','Seafood','Chiquita','Pre-Order','Retail'),
('DoChinBerries','Tasty bananas',3,41,'Large','Vegetables','Sunkist','In Stock','Retail'),
('HaHaSachApples','Fresh, juicy apples',8,17,'Small','Fruits','Chiquita','In Stock','Wholesale'),
('VangSachBerries','Mixed berries',4,77,'Small','Fruits','Dole','In Stock','Direct to Consumer'),
('HeheChinOranges','Delicious grapes',3,14,'Medium','Fruits','Dole','Pre-Order','Retail'),
('PhaleXauBerries','Mixed berries',8,19,'Large','Seafood','Sunkist','Out of Stock','Retail'),
('HaHaXauApples','Tasty bananas',5,55,'Small','Meat','Dole','In Stock','Retail'),
('HaHaThuiOranges','Mixed berries',1,56,'Medium','Fruits','HEB','Pre-Order','Direct to Consumer'),
('HaHaNgonOranges','Delicious grapes',5,14,'Large','Seafood','Dole','Out of Stock','Retail'),
('PhaleNgonBananas','Tasty bananas',4,53,'Large','Meat','HEB','Out of Stock','Wholesale'),
('HeheNgonApples','Sweet, ripe oranges',2,71,'Medium','Vegetables','Driscolls','In Stock','Retail'),
('HaHaChinBerries','Fresh, juicy apples',6,24,'Large','Meat','Dole','Pre-Order','Direct to Consumer'),
('HeheChinOranges','Fresh, juicy apples',2,10,'Small','Dairy','Chiquita','Out of Stock','Direct to Consumer'),
('HaHaSachApples','Mixed berries',1,48,'Medium','Meat','Chiquita','Out of Stock','Wholesale'),
('HaHaXanhBerries','Mixed berries',10,45,'Large','Vegetables','Chiquita','Out of Stock','Direct to Consumer'),
('DoSachOranges','Tasty bananas',5,47,'Large','Dairy','Chiquita','Out of Stock','Retail'),
('VangThuiOranges','Mixed berries',6,91,'Small','Dairy','Driscolls','Out of Stock','Direct to Consumer'),
('PhaleThuiBerries','Sweet, ripe oranges',6,83,'Small','Seafood','Chiquita','In Stock','Retail'),
('TimHuBananas','Fresh, juicy apples',8,42,'Medium','Seafood','Driscolls','In Stock','Direct to Consumer'),
('MongMoDepApples','Delicious grapes',1,25,'Large','Fruits','Dole','Pre-Order','Retail'),
('TimThuiBananas','Delicious grapes',9,67,'Small','Seafood','Sunkist','Out of Stock','Wholesale'),
('HeheChinBerries','Mixed berries',10,31,'Small','Seafood','Sunkist','Pre-Order','Wholesale'),
('HihiXanhBerries','Sweet, ripe oranges',3,15,'Small','Vegetables','Chiquita','Out of Stock','Direct to Consumer'),
('VangThuiGrapes','Tasty bananas',7,73,'Small','Fruits','Sunkist','In Stock','Wholesale'),
('TimChinBerries','Fresh, juicy apples',10,28,'Medium','Vegetables','HEB','Pre-Order','Direct to Consumer'),
('TimHuGrapes','Tasty bananas',2,83,'Small','Dairy','Dole','Out of Stock','Wholesale'),
('DoChinOranges','Fresh, juicy apples',8,13,'Small','Dairy','Chiquita','Pre-Order','Wholesale'),
('PhaleDepBerries','Sweet, ripe oranges',2,63,'Large','Dairy','Driscolls','In Stock','Direct to Consumer'),
('MongMoXanhOranges','Sweet, ripe oranges',8,86,'Small','Vegetables','HEB','In Stock','Wholesale'),
('HeheThuiOranges','Mixed berries',8,91,'Medium','Meat','HEB','In Stock','Wholesale'),
('MongMoXanhApples','Delicious grapes',10,68,'Small','Meat','HEB','Out of Stock','Retail'),
('HihiChinBerries','Tasty bananas',3,15,'Medium','Dairy','Sunkist','Out of Stock','Wholesale'),
('PhaleThuiGrapes','Sweet, ripe oranges',9,65,'Large','Seafood','HEB','Pre-Order','Direct to Consumer'),
('VangSachOranges','Mixed berries',1,23,'Large','Dairy','Sunkist','In Stock','Wholesale'),
('VangNgonBerries','Sweet, ripe oranges',5,38,'Large','Vegetables','Driscolls','Pre-Order','Wholesale'),
('VangXanhGrapes','Mixed berries',10,95,'Medium','Fruits','HEB','Out of Stock','Wholesale'),
('HaHaDepApples','Tasty bananas',6,97,'Large','Vegetables','Sunkist','Pre-Order','Direct to Consumer'),
('HaHaSachBananas','Mixed berries',3,97,'Small','Dairy','Dole','Out of Stock','Wholesale'),
('PhaleHuBerries','Sweet, ripe oranges',2,29,'Small','Dairy','Chiquita','Out of Stock','Wholesale'),
('MongMoChinApples','Fresh, juicy apples',9,90,'Small','Seafood','Driscolls','In Stock','Wholesale'),
('MongMoSachApples','Mixed berries',7,22,'Small','Meat','Sunkist','In Stock','Wholesale'),
('HihiChinBerries','Fresh, juicy apples',9,52,'Large','Fruits','Driscolls','Out of Stock','Wholesale'),
('VangNgonBerries','Fresh, juicy apples',10,67,'Large','Meat','Dole','Out of Stock','Retail'),
('PhaleThuiBananas','Fresh, juicy apples',1,53,'Large','Meat','Driscolls','Pre-Order','Wholesale'),
('MongMoSachBananas','Tasty bananas',5,96,'Small','Vegetables','Dole','Out of Stock','Wholesale'),
('TimHuApples','Delicious grapes',9,12,'Medium','Dairy','Dole','Pre-Order','Wholesale'),
('DoDepApples','Tasty bananas',5,75,'Medium','Vegetables','Dole','Out of Stock','Retail'),
('TimChinOranges','Tasty bananas',8,63,'Medium','Fruits','HEB','Pre-Order','Direct to Consumer'),
('TimXanhBananas','Delicious grapes',6,18,'Small','Seafood','Dole','Out of Stock','Direct to Consumer'),
('HeheChinApples','Sweet, ripe oranges',7,17,'Medium','Seafood','Sunkist','Out of Stock','Direct to Consumer'),
('VangXauBananas','Fresh, juicy apples',3,67,'Small','Seafood','Sunkist','In Stock','Wholesale'),
('VangHuOranges','Mixed berries',1,71,'Medium','Dairy','Driscolls','In Stock','Wholesale'),
('TimThuiGrapes','Tasty bananas',9,82,'Small','Vegetables','HEB','Out of Stock','Wholesale'),
('HaHaXauOranges','Fresh, juicy apples',8,81,'Medium','Dairy','HEB','In Stock','Direct to Consumer'),
('TimChinBerries','Mixed berries',9,55,'Small','Fruits','Chiquita','In Stock','Wholesale'),
('MongMoNgonBananas','Delicious grapes',5,25,'Small','Vegetables','Sunkist','Out of Stock','Direct to Consumer'),
('HihiDepBerries','Delicious grapes',6,80,'Large','Seafood','Chiquita','In Stock','Direct to Consumer'),
('DoChinApples','Tasty bananas',7,38,'Small','Seafood','Dole','In Stock','Direct to Consumer'),
('TimSachBananas','Mixed berries',4,11,'Medium','Fruits','Driscolls','In Stock','Wholesale'),
('HeheHuBananas','Mixed berries',6,74,'Small','Dairy','Driscolls','Pre-Order','Direct to Consumer'),
('VangXanhApples','Tasty bananas',8,93,'Large','Meat','Dole','Out of Stock','Direct to Consumer'),
('HaHaXauBananas','Mixed berries',2,44,'Medium','Dairy','Chiquita','Pre-Order','Wholesale'),
('HeheChinApples','Sweet, ripe oranges',3,77,'Small','Vegetables','Driscolls','In Stock','Retail'),
('VangDepBerries','Delicious grapes',2,15,'Small','Meat','HEB','Out of Stock','Direct to Consumer'),
('HihiChinBerries','Mixed berries',5,69,'Large','Vegetables','HEB','Pre-Order','Retail'),
('MongMoHuBananas','Fresh, juicy apples',2,10,'Large','Vegetables','Dole','Out of Stock','Retail'),
('DoThuiOranges','Tasty bananas',7,72,'Large','Fruits','Sunkist','In Stock','Direct to Consumer'),
('TimThuiOranges','Mixed berries',10,31,'Small','Vegetables','Driscolls','Out of Stock','Wholesale'),
('DoXauOranges','Sweet, ripe oranges',5,35,'Large','Dairy','Sunkist','In Stock','Wholesale'),
('DoHuApples','Delicious grapes',4,35,'Medium','Dairy','Driscolls','In Stock','Direct to Consumer'),
('PhaleThuiBerries','Mixed berries',2,26,'Large','Vegetables','Driscolls','Out of Stock','Retail'),
('DoChinGrapes','Fresh, juicy apples',7,88,'Large','Vegetables','Chiquita','Out of Stock','Retail'),
('HeheXanhApples','Delicious grapes',7,62,'Small','Meat','Sunkist','Out of Stock','Direct to Consumer'),
('PhaleNgonOranges','Mixed berries',2,87,'Medium','Meat','HEB','Out of Stock','Wholesale'),
('HihiNgonBananas','Delicious grapes',6,36,'Small','Fruits','HEB','Out of Stock','Retail'),
('HeheSachBananas','Delicious grapes',9,46,'Large','Vegetables','Chiquita','Pre-Order','Retail'),
('HaHaThuiGrapes','Tasty bananas',10,96,'Medium','Fruits','Chiquita','Out of Stock','Direct to Consumer'),
('TimXanhOranges','Sweet, ripe oranges',5,31,'Medium','Vegetables','Sunkist','Out of Stock','Wholesale'),
('VangHuBananas','Delicious grapes',10,42,'Medium','Vegetables','HEB','Pre-Order','Direct to Consumer'),
('HihiXanhApples','Mixed berries',1,22,'Medium','Seafood','Driscolls','Out of Stock','Wholesale'),
('MongMoHuGrapes','Delicious grapes',9,46,'Small','Meat','Chiquita','In Stock','Wholesale'),
('TimNgonGrapes','Fresh, juicy apples',1,33,'Large','Fruits','Driscolls','In Stock','Wholesale'),
('DoNgonBerries','Tasty bananas',8,28,'Large','Dairy','Dole','In Stock','Retail'),
('TimChinGrapes','Delicious grapes',6,47,'Large','Meat','Driscolls','Pre-Order','Wholesale'),
('HihiThuiBerries','Delicious grapes',8,35,'Medium','Vegetables','Dole','Pre-Order','Wholesale'),
('DoDepOranges','Fresh, juicy apples',4,60,'Small','Seafood','HEB','In Stock','Wholesale'),
('TimXanhGrapes','Tasty bananas',8,11,'Large','Dairy','HEB','Pre-Order','Direct to Consumer'),
('DoXauOranges','Delicious grapes',3,93,'Small','Dairy','Driscolls','Pre-Order','Wholesale'),
('HaHaXanhApples','Tasty bananas',7,47,'Small','Dairy','Driscolls','In Stock','Retail'),
('HeheSachBerries','Delicious grapes',2,21,'Small','Vegetables','HEB','In Stock','Retail'),
('MongMoXanhBerries','Fresh, juicy apples',3,19,'Large','Dairy','Driscolls','Out of Stock','Direct to Consumer'),
('VangHuBerries','Delicious grapes',9,42,'Large','Dairy','Driscolls','Out of Stock','Direct to Consumer'),
('HeheSachBananas','Fresh, juicy apples',8,47,'Large','Seafood','Driscolls','Out of Stock','Wholesale'),
('VangNgonBananas','Tasty bananas',1,18,'Large','Fruits','HEB','Pre-Order','Wholesale'),
('HaHaDepApples','Mixed berries',9,87,'Small','Fruits','HEB','Out of Stock','Wholesale'),
('HihiSachApples','Sweet, ripe oranges',10,88,'Large','Seafood','Dole','In Stock','Retail'),
('MongMoDepApples','Delicious grapes',10,34,'Large','Fruits','Dole','In Stock','Direct to Consumer'),
('MongMoDepBerries','Mixed berries',7,26,'Medium','Vegetables','Sunkist','Pre-Order','Wholesale'),
('DoHuApples','Delicious grapes',3,62,'Small','Dairy','Dole','Pre-Order','Wholesale'),
('VangXauOranges','Mixed berries',5,16,'Medium','Seafood','Sunkist','Pre-Order','Retail'),
('VangNgonBananas','Fresh, juicy apples',8,91,'Small','Dairy','HEB','Pre-Order','Wholesale'),
('MongMoXauBerries','Fresh, juicy apples',7,86,'Medium','Fruits','Chiquita','In Stock','Retail'),
('MongMoNgonBananas','Delicious grapes',7,12,'Large','Seafood','Chiquita','In Stock','Wholesale'),
('HaHaHuOranges','Delicious grapes',7,82,'Large','Seafood','Dole','Pre-Order','Wholesale'),
('DoNgonApples','Sweet, ripe oranges',7,37,'Large','Meat','Sunkist','Pre-Order','Retail'),
('HeheDepApples','Mixed berries',3,88,'Small','Dairy','Dole','In Stock','Retail'),
('VangChinApples','Sweet, ripe oranges',9,84,'Medium','Meat','Sunkist','Pre-Order','Retail'),
('TimDepBerries','Sweet, ripe oranges',9,72,'Large','Meat','Dole','In Stock','Wholesale'),
('MongMoChinApples','Fresh, juicy apples',2,77,'Large','Seafood','Driscolls','In Stock','Direct to Consumer'),
('MongMoXanhBananas','Delicious grapes',3,43,'Large','Vegetables','Driscolls','Out of Stock','Retail'),
('VangXanhGrapes','Fresh, juicy apples',9,60,'Large','Dairy','Driscolls','Pre-Order','Retail'),
('MongMoDepBerries','Mixed berries',4,65,'Medium','Meat','Driscolls','Out of Stock','Wholesale'),
('HeheThuiBananas','Sweet, ripe oranges',9,93,'Medium','Meat','HEB','Pre-Order','Retail'),
('HihiChinBerries','Tasty bananas',3,24,'Small','Vegetables','Driscolls','Out of Stock','Retail'),
('HaHaHuOranges','Tasty bananas',3,11,'Small','Meat','HEB','Out of Stock','Retail'),
('VangNgonBerries','Fresh, juicy apples',6,94,'Medium','Fruits','Chiquita','Out of Stock','Wholesale'),
('HaHaThuiBananas','Tasty bananas',1,63,'Small','Dairy','HEB','In Stock','Retail'),
('DoXanhApples','Fresh, juicy apples',10,33,'Medium','Fruits','Dole','In Stock','Direct to Consumer'),
('DoChinGrapes','Sweet, ripe oranges',6,61,'Small','Meat','Chiquita','In Stock','Direct to Consumer'),
('VangThuiBerries','Tasty bananas',7,92,'Medium','Dairy','Chiquita','In Stock','Wholesale'),
('PhaleDepOranges','Fresh, juicy apples',6,24,'Small','Dairy','Driscolls','Out of Stock','Direct to Consumer'),
('HihiThuiOranges','Mixed berries',1,100,'Small','Vegetables','Chiquita','Pre-Order','Retail'),
('HeheChinOranges','Tasty bananas',8,93,'Small','Meat','HEB','Out of Stock','Retail'),
('HaHaXauGrapes','Mixed berries',1,67,'Large','Seafood','Chiquita','Out of Stock','Wholesale'),
('HaHaHuOranges','Sweet, ripe oranges',8,86,'Small','Seafood','Driscolls','Out of Stock','Wholesale'),
('HeheHuBerries','Fresh, juicy apples',2,79,'Medium','Dairy','Driscolls','Pre-Order','Direct to Consumer'),
('MongMoDepBananas','Sweet, ripe oranges',7,90,'Medium','Meat','Driscolls','Out of Stock','Retail'),
('TimChinGrapes','Fresh, juicy apples',5,43,'Small','Meat','Sunkist','Out of Stock','Direct to Consumer'),
('VangHuApples','Sweet, ripe oranges',9,82,'Small','Vegetables','Driscolls','In Stock','Wholesale'),
('HeheChinApples','Tasty bananas',5,22,'Medium','Meat','Dole','Out of Stock','Retail'),
('HihiSachGrapes','Tasty bananas',9,64,'Medium','Dairy','Sunkist','In Stock','Wholesale'),
('DoHuGrapes','Delicious grapes',7,48,'Small','Seafood','Sunkist','In Stock','Wholesale'),
('PhaleNgonOranges','Delicious grapes',7,92,'Medium','Seafood','Driscolls','In Stock','Retail'),
('DoXanhApples','Tasty bananas',3,70,'Large','Seafood','Dole','In Stock','Direct to Consumer'),
('PhaleXanhOranges','Mixed berries',1,15,'Medium','Meat','Driscolls','Pre-Order','Wholesale'),
('VangThuiApples','Fresh, juicy apples',7,83,'Large','Fruits','Driscolls','Pre-Order','Wholesale'),
('PhaleThuiBerries','Mixed berries',1,30,'Medium','Dairy','Chiquita','Pre-Order','Wholesale'),
('PhaleDepApples','Delicious grapes',2,32,'Medium','Fruits','Sunkist','Out of Stock','Wholesale'),
('VangXanhBananas','Mixed berries',10,70,'Small','Dairy','Chiquita','In Stock','Direct to Consumer'),
('MongMoDepBerries','Tasty bananas',10,71,'Medium','Dairy','Chiquita','Out of Stock','Wholesale'),
('HaHaDepGrapes','Fresh, juicy apples',4,36,'Small','Dairy','Sunkist','Pre-Order','Wholesale'),
('TimXanhApples','Sweet, ripe oranges',7,99,'Small','Vegetables','Chiquita','Pre-Order','Wholesale'),
('DoThuiApples','Mixed berries',3,38,'Large','Seafood','Chiquita','Out of Stock','Retail'),
('VangThuiBananas','Sweet, ripe oranges',7,69,'Medium','Dairy','Driscolls','Out of Stock','Direct to Consumer'),
('DoNgonBerries','Tasty bananas',1,70,'Large','Fruits','Sunkist','Out of Stock','Direct to Consumer'),
('TimDepOranges','Fresh, juicy apples',4,12,'Small','Seafood','HEB','Out of Stock','Direct to Consumer'),
('TimHuApples','Tasty bananas',1,29,'Small','Fruits','Sunkist','Pre-Order','Retail'),
('PhaleXauBerries','Mixed berries',10,78,'Large','Dairy','Chiquita','In Stock','Direct to Consumer'),
('HihiXauApples','Fresh, juicy apples',1,98,'Small','Seafood','Driscolls','Out of Stock','Direct to Consumer'),
('HaHaSachBerries','Delicious grapes',9,96,'Medium','Seafood','Chiquita','In Stock','Wholesale'),
('HaHaSachOranges','Mixed berries',6,99,'Large','Vegetables','Dole','Pre-Order','Wholesale'),
('TimXanhApples','Delicious grapes',3,95,'Medium','Fruits','Chiquita','Pre-Order','Direct to Consumer'),
('TimHuOranges','Sweet, ripe oranges',6,27,'Small','Vegetables','Chiquita','In Stock','Direct to Consumer'),
('PhaleXauOranges','Delicious grapes',4,16,'Small','Dairy','HEB','In Stock','Direct to Consumer'),
('HihiDepOranges','Delicious grapes',7,74,'Small','Fruits','Dole','In Stock','Wholesale'),
('DoSachOranges','Sweet, ripe oranges',6,19,'Small','Vegetables','HEB','Out of Stock','Direct to Consumer'),
('VangThuiGrapes','Delicious grapes',9,22,'Small','Fruits','HEB','In Stock','Retail'),
('VangXanhBerries','Mixed berries',10,96,'Large','Seafood','Sunkist','In Stock','Retail'),
('PhaleChinOranges','Delicious grapes',1,24,'Large','Seafood','Sunkist','Pre-Order','Retail'),
('HaHaXanhApples','Tasty bananas',2,64,'Small','Dairy','HEB','In Stock','Direct to Consumer'),
('MongMoXauGrapes','Mixed berries',3,97,'Small','Meat','HEB','Out of Stock','Direct to Consumer'),
('HihiThuiGrapes','Delicious grapes',8,14,'Medium','Meat','Dole','Pre-Order','Wholesale'),
('PhaleXauApples','Sweet, ripe oranges',6,34,'Medium','Fruits','Sunkist','In Stock','Wholesale'),
('PhaleChinBerries','Mixed berries',4,92,'Large','Vegetables','Dole','Out of Stock','Wholesale'),
('HeheThuiBerries','Mixed berries',9,10,'Small','Seafood','Driscolls','In Stock','Retail'),
('HaHaNgonGrapes','Tasty bananas',7,82,'Medium','Vegetables','Driscolls','In Stock','Direct to Consumer'),
('VangNgonApples','Mixed berries',10,23,'Small','Meat','Dole','In Stock','Direct to Consumer'),
('TimSachGrapes','Delicious grapes',4,75,'Large','Meat','Chiquita','Pre-Order','Direct to Consumer'),
('HeheDepGrapes','Fresh, juicy apples',10,79,'Medium','Seafood','HEB','Pre-Order','Retail'),
('HaHaXauBerries','Mixed berries',9,57,'Large','Fruits','Chiquita','In Stock','Direct to Consumer'),
('DoChinApples','Delicious grapes',10,53,'Large','Seafood','Sunkist','In Stock','Retail'),
('HeheThuiOranges','Sweet, ripe oranges',4,69,'Small','Fruits','Sunkist','In Stock','Wholesale'),
('TimXanhBerries','Tasty bananas',7,78,'Small','Vegetables','Dole','Out of Stock','Wholesale'),
('TimXauGrapes','Fresh, juicy apples',1,39,'Small','Dairy','HEB','Out of Stock','Retail'),
('HihiChinBananas','Tasty bananas',2,42,'Small','Meat','Chiquita','Pre-Order','Retail'),
('MongMoXauOranges','Fresh, juicy apples',2,60,'Small','Vegetables','Driscolls','Out of Stock','Wholesale'),
('HaHaXanhBananas','Mixed berries',5,89,'Medium','Fruits','HEB','In Stock','Wholesale'),
('HeheSachBananas','Delicious grapes',7,68,'Small','Meat','Driscolls','In Stock','Direct to Consumer'),
('VangHuGrapes','Tasty bananas',10,48,'Small','Seafood','Dole','Out of Stock','Retail'),
('DoChinApples','Fresh, juicy apples',5,57,'Medium','Vegetables','Driscolls','Pre-Order','Retail'),
('HihiXauBerries','Tasty bananas',2,48,'Large','Meat','Driscolls','In Stock','Wholesale'),
('HaHaSachOranges','Tasty bananas',1,41,'Small','Fruits','Dole','Pre-Order','Retail'),
('HihiSachGrapes','Mixed berries',5,77,'Large','Seafood','Driscolls','Out of Stock','Wholesale'),
('HihiDepOranges','Mixed berries',8,12,'Medium','Fruits','Sunkist','In Stock','Wholesale'),
('TimChinApples','Fresh, juicy apples',10,56,'Large','Meat','Dole','Out of Stock','Wholesale'),
('HeheXanhBananas','Delicious grapes',10,79,'Medium','Dairy','Chiquita','Out of Stock','Direct to Consumer'),
('HeheThuiBananas','Sweet, ripe oranges',9,20,'Medium','Meat','Dole','In Stock','Direct to Consumer'),
('VangXanhBerries','Delicious grapes',4,42,'Medium','Dairy','Dole','Out of Stock','Retail'),
('MongMoNgonBananas','Sweet, ripe oranges',1,28,'Medium','Dairy','Dole','In Stock','Direct to Consumer'),
('HihiSachOranges','Mixed berries',8,69,'Large','Fruits','Dole','Out of Stock','Wholesale'),
('HihiXanhBananas','Fresh, juicy apples',10,66,'Large','Meat','Dole','In Stock','Retail'),
('VangXauBananas','Mixed berries',1,37,'Medium','Vegetables','Dole','Pre-Order','Retail'),
('MongMoNgonOranges','Tasty bananas',4,77,'Medium','Seafood','Sunkist','Out of Stock','Retail'),
('TimXauGrapes','Mixed berries',4,97,'Medium','Fruits','Chiquita','Pre-Order','Direct to Consumer'),
('HeheXauOranges','Tasty bananas',6,57,'Large','Fruits','Dole','Pre-Order','Retail'),
('HeheXauBananas','Sweet, ripe oranges',8,63,'Medium','Meat','Driscolls','Pre-Order','Retail'),
('PhaleHuBananas','Mixed berries',10,63,'Small','Vegetables','Dole','In Stock','Direct to Consumer'),
('HihiThuiApples','Fresh, juicy apples',10,87,'Medium','Meat','Driscolls','Out of Stock','Retail'),
('MongMoDepBerries','Tasty bananas',1,78,'Large','Dairy','Dole','In Stock','Retail'),
('HihiXanhBerries','Tasty bananas',7,88,'Medium','Vegetables','Driscolls','Out of Stock','Direct to Consumer'),
('DoHuBananas','Tasty bananas',3,32,'Medium','Dairy','Chiquita','In Stock','Wholesale'),
('PhaleNgonApples','Sweet, ripe oranges',7,64,'Large','Vegetables','Chiquita','Pre-Order','Wholesale'),
('TimChinBananas','Fresh, juicy apples',4,25,'Large','Vegetables','Chiquita','Out of Stock','Direct to Consumer'),
('HeheChinBerries','Fresh, juicy apples',1,42,'Medium','Meat','Sunkist','Out of Stock','Retail')