INSERT INTO store (name_store, city, country, street_name, street_number, store_manager)
VALUES
('HihiStore7Walmart','New York','Germany','Hollywood Boulevard','671','David Williams'),
('HihiStore5Apple','Houston','France','Wall Street','722','Jane Doe'),
('HihiStore7Apple','New York','United Kingdom','Hollywood Boulevard','516','David Williams'),
('MongMoStore7Apple','Chicago','France','Wall Street','58','Mary Brown'),
('HeheHouseMicrosoft','Houston','France','Hollywood Boulevard','939','Mary Brown'),
('VangStore5Apple','New York','United States','Fifth Avenue','29','John Smith'),
('HaHaHomeWalmart','Chicago','France','Wall Street','916','Mary Brown'),
('HaHaStore4Amazon','Chicago','United Kingdom','Wall Street','811','John Smith'),
('HaHaStore3Microsoft','Houston','Germany','Wall Street','959','John Smith'),
('HihiStore7Apple','Chicago','United States','Wall Street','11','Mary Brown'),
('DoStore4Microsoft','Houston','France','Wall Street','572','David Williams'),
('HihiHouseWalmart','New York','United States','Main Street','847','David Williams'),
('VangStore2Walmart','New York','Germany','Main Street','439','Jane Doe'),
('HaHaStore3Amazon','New York','United States','Main Street','301','David Williams'),
('VangHomeAmazon','New York','United Kingdom','Hollywood Boulevard','522','Mary Brown'),
('PhaleHouseMicrosoft','Houston','United States','Hollywood Boulevard','700','John Smith'),
('VangStore4Apple','Phoenix','Canada','Park Avenue','587','Jane Doe'),
('VangStore2Walmart','Phoenix','Canada','Park Avenue','782','Jane Doe'),
('DoStore5Google','Houston','Germany','Fifth Avenue','586','Jane Doe'),
('HihiStore3Amazon','Chicago','France','Fifth Avenue','707','Jane Doe'),
('VangStore3Google','Chicago','Canada','Main Street','457','John Smith'),
('MongMoHouseApple','New York','Germany','Main Street','226','Mary Brown'),
('HihiStore2Apple','Houston','France','Hollywood Boulevard','771','Mary Brown'),
('HaHaStore2Google','New York','United States','Park Avenue','439','David Williams'),
('MongMoStore7Microsoft','Phoenix','Germany','Park Avenue','602','David Williams'),
('HeheStore2Apple','Chicago','United Kingdom','Fifth Avenue','755','Jane Doe'),
('VangHouseGoogle','Houston','Canada','Hollywood Boulevard','435','Jane Doe'),
('HeheStore5Amazon','Phoenix','France','Fifth Avenue','413','Peter Jones'),
('DoStore4Apple','Los Angeles','United States','Hollywood Boulevard','320','Peter Jones'),
('HihiStoreAmazon','Chicago','Canada','Park Avenue','371','Jane Doe'),
('DoStore2Amazon','Houston','United Kingdom','Main Street','234','Mary Brown'),
('TimStore5Amazon','New York','France','Park Avenue','44','David Williams'),
('HeheHomeApple','Chicago','Germany','Main Street','326','Mary Brown'),
('HihiStore5Google','Chicago','Germany','Fifth Avenue','860','Jane Doe'),
('PhaleStoreGoogle','Houston','France','Main Street','719','John Smith'),
('HaHaStore5Google','Houston','Germany','Main Street','356','David Williams'),
('HihiHouseWalmart','Los Angeles','Germany','Hollywood Boulevard','1','Mary Brown'),
('HaHaHomeMicrosoft','Chicago','France','Hollywood Boulevard','623','John Smith'),
('HihiHomeAmazon','Los Angeles','United States','Main Street','208','Mary Brown'),
('DoStore5Microsoft','Phoenix','United Kingdom','Hollywood Boulevard','606','John Smith'),
('DoStoreMicrosoft','New York','United States','Hollywood Boulevard','176','Peter Jones'),
('HaHaStore4Apple','New York','United States','Fifth Avenue','63','David Williams'),
('VangHouseGoogle','Los Angeles','Germany','Wall Street','71','Jane Doe'),
('MongMoStore7Microsoft','New York','United States','Park Avenue','672','David Williams'),
('HaHaStore3Walmart','Los Angeles','France','Park Avenue','713','John Smith'),
('MongMoStore7Google','Los Angeles','France','Hollywood Boulevard','544','Jane Doe'),
('HeheHouseGoogle','Los Angeles','United States','Park Avenue','972','Peter Jones'),
('HihiStoreWalmart','Houston','Germany','Hollywood Boulevard','141','Jane Doe'),
('HeheStore4Walmart','Houston','Germany','Hollywood Boulevard','508','Mary Brown'),
('HihiStore5Google','Phoenix','France','Fifth Avenue','362','Peter Jones'),
('DoHomeGoogle','Los Angeles','Germany','Park Avenue','186','John Smith'),
('PhaleStore2Google','Los Angeles','France','Fifth Avenue','694','David Williams'),
('MongMoStore2Apple','Phoenix','United Kingdom','Park Avenue','681','Peter Jones'),
('MongMoStoreGoogle','Phoenix','United States','Fifth Avenue','589','Peter Jones'),
('HaHaHouseMicrosoft','Chicago','United States','Park Avenue','584','Peter Jones'),
('HaHaHomeAmazon','Chicago','Canada','Park Avenue','197','Jane Doe'),
('TimHomeWalmart','New York','United States','Wall Street','521','David Williams'),
('DoStore5Walmart','Chicago','Canada','Main Street','576','Mary Brown'),
('TimStore5Amazon','Phoenix','United States','Wall Street','967','Jane Doe'),
('VangStore7Google','Los Angeles','Canada','Main Street','37','John Smith'),
('TimStore3Amazon','Los Angeles','France','Hollywood Boulevard','645','David Williams'),
('DoStore2Walmart','Houston','France','Wall Street','968','Mary Brown'),
('PhaleHomeApple','Phoenix','United States','Park Avenue','684','Jane Doe'),
('HaHaHouseMicrosoft','Los Angeles','United Kingdom','Wall Street','369','David Williams'),
('HaHaStoreApple','New York','Canada','Main Street','91','Peter Jones'),
('PhaleHouseAmazon','Phoenix','United States','Hollywood Boulevard','982','David Williams'),
('TimStoreGoogle','Houston','France','Main Street','487','Mary Brown'),
('HeheStoreApple','Chicago','Canada','Park Avenue','904','Mary Brown'),
('MongMoStore4Microsoft','New York','United Kingdom','Main Street','572','John Smith'),
('TimHomeApple','Chicago','United Kingdom','Main Street','99','Mary Brown'),
('HihiHomeApple','New York','United Kingdom','Main Street','512','Peter Jones'),
('TimStore2Amazon','Houston','Germany','Main Street','189','Jane Doe'),
('TimStoreGoogle','Chicago','Canada','Main Street','892','Peter Jones'),
('PhaleHomeWalmart','Houston','United Kingdom','Park Avenue','674','Jane Doe'),
('PhaleStore5Microsoft','New York','Germany','Fifth Avenue','482','John Smith'),
('MongMoStore5Walmart','Houston','United States','Wall Street','684','Mary Brown'),
('HihiStore7Walmart','Los Angeles','United States','Hollywood Boulevard','299','John Smith'),
('HaHaHouseWalmart','Los Angeles','Germany','Main Street','432','David Williams'),
('DoStoreAmazon','New York','United Kingdom','Hollywood Boulevard','246','David Williams'),
('MongMoStore7Walmart','New York','United Kingdom','Hollywood Boulevard','420','Jane Doe'),
('HeheStore2Microsoft','Los Angeles','France','Hollywood Boulevard','833','Mary Brown'),
('VangStore4Walmart','Chicago','France','Hollywood Boulevard','424','Mary Brown'),
('MongMoStore5Amazon','Chicago','Germany','Park Avenue','238','Jane Doe'),
('DoStore2Microsoft','New York','United States','Fifth Avenue','814','David Williams'),
('VangStore7Google','Chicago','United Kingdom','Hollywood Boulevard','890','Mary Brown'),
('HeheStore4Amazon','Houston','Canada','Fifth Avenue','804','Jane Doe'),
('HaHaStoreApple','Houston','France','Wall Street','611','Mary Brown'),
('VangStore7Amazon','Phoenix','United Kingdom','Wall Street','92','John Smith'),
('VangStore5Microsoft','Chicago','Canada','Park Avenue','432','David Williams'),
('MongMoStoreMicrosoft','Los Angeles','France','Main Street','338','Mary Brown'),
('MongMoStore3Google','Phoenix','United Kingdom','Hollywood Boulevard','516','John Smith'),
('HeheStore2Amazon','Los Angeles','United States','Hollywood Boulevard','489','John Smith'),
('VangStore2Google','Phoenix','France','Fifth Avenue','941','Jane Doe'),
('HeheStore4Walmart','Houston','France','Park Avenue','612','John Smith'),
('MongMoHouseWalmart','Houston','Canada','Hollywood Boulevard','732','Mary Brown'),
('TimStore2Walmart','New York','United States','Park Avenue','324','Peter Jones'),
('VangStore3Google','Los Angeles','United States','Main Street','32','Mary Brown'),
('VangStore2Google','Chicago','France','Fifth Avenue','454','Jane Doe'),
('HeheStoreAmazon','Phoenix','Canada','Main Street','246','David Williams'),
('HihiStore4Amazon','New York','France','Wall Street','648','David Williams'),
('HihiStore3Apple','Chicago','Canada','Wall Street','976','John Smith'),
('HihiStore5Amazon','Los Angeles','Canada','Main Street','483','Jane Doe'),
('HeheStore3Walmart','New York','United Kingdom','Fifth Avenue','88','Mary Brown'),
('PhaleStore4Microsoft','Los Angeles','United Kingdom','Hollywood Boulevard','279','John Smith'),
('HaHaStore3Apple','Houston','United States','Main Street','227','John Smith'),
('HihiStore2Walmart','Los Angeles','France','Park Avenue','171','Mary Brown'),
('HaHaHouseWalmart','Los Angeles','United Kingdom','Hollywood Boulevard','627','Mary Brown'),
('HihiStoreWalmart','Phoenix','France','Hollywood Boulevard','218','John Smith'),
('HihiHouseMicrosoft','Chicago','France','Main Street','461','David Williams'),
('DoHomeWalmart','New York','Germany','Wall Street','841','John Smith'),
('TimStore3Amazon','New York','United Kingdom','Fifth Avenue','644','Peter Jones'),
('HaHaStore4Apple','Phoenix','United Kingdom','Hollywood Boulevard','784','Peter Jones'),
('HeheStoreWalmart','Chicago','France','Fifth Avenue','337','John Smith'),
('PhaleStore7Microsoft','Houston','Canada','Hollywood Boulevard','274','David Williams'),
('PhaleHomeAmazon','Houston','Canada','Fifth Avenue','175','Jane Doe'),
('PhaleHomeMicrosoft','New York','France','Hollywood Boulevard','263','Jane Doe'),
('HaHaStoreWalmart','Phoenix','France','Hollywood Boulevard','574','Mary Brown'),
('HaHaStore2Walmart','Los Angeles','France','Main Street','106','Peter Jones'),
('MongMoStoreMicrosoft','New York','United Kingdom','Park Avenue','925','Mary Brown'),
('MongMoStore2Microsoft','New York','Canada','Wall Street','297','Mary Brown'),
('HihiHomeMicrosoft','New York','United States','Park Avenue','247','Jane Doe'),
('HihiHouseAmazon','Houston','Germany','Main Street','159','Mary Brown'),
('HihiHouseApple','Houston','Germany','Hollywood Boulevard','504','John Smith'),
('HeheStore2Microsoft','Phoenix','France','Wall Street','810','Jane Doe'),
('VangStore3Walmart','New York','Germany','Hollywood Boulevard','760','John Smith'),
('TimStore4Walmart','Los Angeles','Germany','Wall Street','358','Peter Jones'),
('PhaleStoreAmazon','Houston','Canada','Hollywood Boulevard','325','Jane Doe'),
('VangHomeApple','Chicago','United Kingdom','Hollywood Boulevard','774','Mary Brown'),
('HaHaStoreMicrosoft','New York','France','Park Avenue','162','Mary Brown'),
('DoStore4Google','Los Angeles','Germany','Wall Street','386','Jane Doe'),
('TimHouseApple','Phoenix','France','Main Street','481','Jane Doe'),
('TimStore3Google','Phoenix','Germany','Wall Street','651','Peter Jones'),
('HihiStore4Walmart','Phoenix','United States','Wall Street','111','Jane Doe'),
('MongMoHomeAmazon','Phoenix','Germany','Fifth Avenue','448','Peter Jones'),
('HeheStore2Walmart','Chicago','France','Park Avenue','753','Mary Brown'),
('TimHouseGoogle','Phoenix','France','Main Street','43','Peter Jones'),
('PhaleStore4Microsoft','Houston','United Kingdom','Main Street','436','Jane Doe'),
('DoStore4Apple','New York','United Kingdom','Fifth Avenue','663','Peter Jones'),
('HeheStore5Google','Phoenix','Germany','Main Street','184','John Smith'),
('TimHomeAmazon','New York','United States','Wall Street','466','David Williams'),
('HihiStore2Microsoft','Chicago','France','Hollywood Boulevard','480','Peter Jones'),
('DoStore3Amazon','Chicago','United States','Park Avenue','757','John Smith'),
('HaHaStore2Amazon','Phoenix','Canada','Main Street','194','Mary Brown'),
('DoStore3Microsoft','New York','United Kingdom','Main Street','181','John Smith'),
('VangHomeAmazon','New York','France','Main Street','121','Jane Doe'),
('TimHouseApple','Chicago','United States','Main Street','179','John Smith'),
('VangStore4Walmart','Los Angeles','United States','Hollywood Boulevard','259','Peter Jones'),
('HihiStore3Google','Los Angeles','France','Wall Street','678','Peter Jones'),
('MongMoStoreAmazon','Los Angeles','United States','Park Avenue','199','Peter Jones'),
('DoStoreGoogle','New York','United States','Wall Street','705','John Smith'),
('HihiHouseWalmart','Phoenix','Canada','Park Avenue','498','Peter Jones'),
('TimHomeWalmart','New York','France','Hollywood Boulevard','345','John Smith'),
('HihiStore4Amazon','Phoenix','United Kingdom','Hollywood Boulevard','49','John Smith'),
('VangStoreAmazon','Houston','United Kingdom','Park Avenue','839','Peter Jones'),
('VangStore5Walmart','New York','United States','Wall Street','437','Jane Doe'),
('VangStore7Amazon','Los Angeles','France','Park Avenue','484','David Williams'),
('VangStore2Amazon','Phoenix','United States','Wall Street','820','Mary Brown'),
('HaHaHouseWalmart','Chicago','United States','Park Avenue','800','John Smith'),
('HihiStore2Apple','New York','Germany','Wall Street','395','Mary Brown'),
('TimStore5Apple','Chicago','France','Wall Street','781','Peter Jones'),
('MongMoStoreWalmart','Phoenix','United States','Park Avenue','440','Peter Jones'),
('DoHomeMicrosoft','Chicago','France','Hollywood Boulevard','758','Jane Doe'),
('PhaleStore5Walmart','Los Angeles','United Kingdom','Hollywood Boulevard','578','John Smith'),
('HihiStore4Walmart','Los Angeles','Germany','Fifth Avenue','579','David Williams'),
('HaHaStore7Google','Los Angeles','United Kingdom','Hollywood Boulevard','480','Peter Jones'),
('MongMoStore5Apple','Phoenix','United States','Park Avenue','180','Jane Doe'),
('HeheStore7Walmart','Phoenix','United States','Fifth Avenue','129','John Smith'),
('VangHomeAmazon','New York','Canada','Fifth Avenue','335','David Williams'),
('HaHaStore3Amazon','Chicago','Canada','Park Avenue','314','John Smith'),
('HeheStore2Apple','Los Angeles','United States','Fifth Avenue','203','Mary Brown'),
('HaHaStore3Apple','Los Angeles','United Kingdom','Fifth Avenue','295','David Williams'),
('VangStore2Microsoft','Chicago','United States','Main Street','234','Jane Doe'),
('PhaleStore7Apple','Houston','Canada','Wall Street','721','David Williams'),
('HaHaStoreWalmart','Chicago','Germany','Fifth Avenue','715','Jane Doe'),
('HaHaStore3Walmart','New York','France','Wall Street','409','Mary Brown'),
('MongMoStore4Microsoft','Los Angeles','United States','Fifth Avenue','781','David Williams'),
('MongMoHouseGoogle','Phoenix','United States','Main Street','436','Peter Jones'),
('HaHaStoreApple','Los Angeles','France','Park Avenue','35','Mary Brown'),
('HeheStoreGoogle','Los Angeles','Germany','Park Avenue','75','Peter Jones'),
('HaHaStore5Apple','Los Angeles','France','Fifth Avenue','166','Jane Doe'),
('VangStore3Microsoft','Chicago','United Kingdom','Hollywood Boulevard','121','John Smith'),
('HihiStore5Google','Phoenix','United Kingdom','Park Avenue','413','Mary Brown'),
('HihiStore5Amazon','Chicago','United States','Main Street','527','David Williams'),
('DoStore7Google','Phoenix','United Kingdom','Fifth Avenue','702','John Smith'),
('PhaleStore2Walmart','Chicago','Canada','Wall Street','46','John Smith'),
('DoStore2Apple','Houston','United States','Main Street','941','Mary Brown'),
('PhaleStore5Microsoft','Chicago','Germany','Fifth Avenue','647','Mary Brown'),
('HaHaStore5Walmart','Phoenix','Germany','Main Street','496','Peter Jones'),
('DoStoreGoogle','New York','France','Park Avenue','470','Peter Jones'),
('DoStore5Walmart','Los Angeles','Germany','Hollywood Boulevard','73','John Smith'),
('DoStore3Apple','Chicago','Germany','Wall Street','36','John Smith'),
('PhaleHomeMicrosoft','Houston','Germany','Hollywood Boulevard','816','Jane Doe'),
('HihiStore3Apple','Chicago','United Kingdom','Wall Street','41','David Williams'),
('VangHomeWalmart','Phoenix','Germany','Hollywood Boulevard','975','Jane Doe'),
('VangHouseWalmart','Houston','Germany','Wall Street','235','David Williams'),
('HihiStore4Amazon','Los Angeles','United Kingdom','Fifth Avenue','418','David Williams'),
('HeheStoreMicrosoft','Los Angeles','United Kingdom','Wall Street','607','Jane Doe'),
('HihiStore3Apple','Houston','United States','Park Avenue','567','Mary Brown'),
('HaHaStore5Amazon','Chicago','United Kingdom','Hollywood Boulevard','626','Peter Jones'),
('PhaleStoreApple','Los Angeles','United States','Hollywood Boulevard','845','Peter Jones'),
('MongMoStoreApple','Houston','United Kingdom','Park Avenue','665','Jane Doe'),
('HeheStore4Microsoft','New York','Germany','Wall Street','38','John Smith'),
('TimStoreMicrosoft','Los Angeles','France','Fifth Avenue','357','David Williams'),
('HaHaHouseApple','Houston','Germany','Park Avenue','615','David Williams'),
('DoStore7Microsoft','Phoenix','United Kingdom','Hollywood Boulevard','30','Peter Jones'),
('VangStore2Microsoft','Phoenix','United Kingdom','Wall Street','804','Peter Jones'),
('DoHouseMicrosoft','Los Angeles','Canada','Park Avenue','89','Peter Jones'),
('HeheStoreGoogle','New York','United Kingdom','Fifth Avenue','694','John Smith'),
('MongMoHomeGoogle','Los Angeles','United States','Hollywood Boulevard','80','Jane Doe'),
('DoHomeWalmart','Phoenix','France','Main Street','775','John Smith'),
('HaHaHouseApple','Chicago','Canada','Park Avenue','551','Peter Jones'),
('VangStore4Apple','New York','France','Main Street','195','Peter Jones'),
('MongMoStore5Apple','New York','Canada','Fifth Avenue','550','John Smith'),
('HeheHouseWalmart','New York','United States','Main Street','467','Jane Doe'),
('HaHaStore4Apple','Houston','Canada','Main Street','420','Peter Jones'),
('MongMoStore7Amazon','Phoenix','France','Fifth Avenue','111','David Williams'),
('HihiStore2Amazon','Houston','Canada','Main Street','554','John Smith'),
('DoStore4Google','Los Angeles','Canada','Main Street','389','John Smith'),
('HeheStore3Apple','Houston','Canada','Fifth Avenue','143','David Williams'),
('TimStore3Amazon','Houston','United Kingdom','Main Street','958','Peter Jones'),
('HaHaStore5Apple','New York','United States','Hollywood Boulevard','261','David Williams'),
('MongMoStoreWalmart','Phoenix','France','Fifth Avenue','765','Jane Doe'),
('HeheHouseAmazon','New York','United Kingdom','Fifth Avenue','338','Peter Jones'),
('TimHouseApple','New York','United States','Wall Street','354','John Smith'),
('DoStore7Google','New York','France','Park Avenue','329','Peter Jones'),
('MongMoStoreAmazon','Chicago','United Kingdom','Hollywood Boulevard','938','Mary Brown'),
('HihiHomeAmazon','New York','France','Hollywood Boulevard','156','Mary Brown'),
('PhaleStore5Microsoft','Houston','Canada','Main Street','490','Peter Jones'),
('HeheHomeGoogle','Chicago','France','Wall Street','681','John Smith'),
('HeheHouseAmazon','Chicago','France','Park Avenue','130','Mary Brown'),
('HihiStore3Apple','New York','France','Park Avenue','497','Jane Doe'),
('HihiStore3Amazon','Phoenix','Germany','Fifth Avenue','851','John Smith'),
('VangHomeApple','Chicago','Germany','Park Avenue','69','John Smith'),
('HeheStore2Amazon','Houston','Germany','Hollywood Boulevard','287','David Williams'),
('DoStore7Microsoft','Chicago','France','Wall Street','977','Mary Brown'),
('MongMoHomeGoogle','Houston','United Kingdom','Wall Street','750','Mary Brown'),
('HihiStoreWalmart','Chicago','United Kingdom','Wall Street','255','David Williams'),
('VangStore2Google','New York','Canada','Wall Street','493','Jane Doe'),
('MongMoStoreGoogle','Chicago','United States','Wall Street','519','Mary Brown'),
('PhaleStoreAmazon','Chicago','France','Main Street','737','John Smith'),
('VangHomeGoogle','Los Angeles','United Kingdom','Hollywood Boulevard','965','Mary Brown'),
('MongMoStore2Walmart','Los Angeles','United Kingdom','Hollywood Boulevard','188','Jane Doe'),
('HaHaStore7Apple','Los Angeles','France','Wall Street','635','Peter Jones'),
('VangHomeAmazon','Chicago','United States','Park Avenue','656','John Smith'),
('VangStore4Walmart','Chicago','Germany','Park Avenue','175','Mary Brown'),
('MongMoStore3Apple','Houston','United States','Wall Street','395','Peter Jones'),
('DoHouseApple','Phoenix','United Kingdom','Hollywood Boulevard','940','Mary Brown'),
('PhaleHomeGoogle','Los Angeles','Germany','Park Avenue','412','John Smith'),
('MongMoStore5Apple','Chicago','Germany','Fifth Avenue','349','David Williams'),
('HihiStore2Google','Chicago','United States','Park Avenue','827','Peter Jones'),
('HeheHomeApple','Phoenix','Germany','Main Street','255','Mary Brown'),
('TimStore7Walmart','Phoenix','Canada','Wall Street','686','Jane Doe'),
('HeheStore3Apple','Los Angeles','United Kingdom','Main Street','367','Jane Doe'),
('PhaleStore5Amazon','Los Angeles','France','Wall Street','209','David Williams'),
('PhaleStore4Apple','New York','France','Main Street','818','Jane Doe'),
('MongMoStore4Microsoft','New York','Canada','Wall Street','783','David Williams'),
('VangStore2Google','Phoenix','Germany','Main Street','106','Mary Brown'),
('HeheHouseAmazon','Phoenix','Canada','Park Avenue','479','David Williams'),
('MongMoStore7Amazon','Phoenix','United States','Park Avenue','416','David Williams'),
('MongMoHouseGoogle','Los Angeles','United Kingdom','Park Avenue','277','Mary Brown'),
('VangHomeWalmart','Houston','Germany','Hollywood Boulevard','455','John Smith'),
('VangHouseWalmart','New York','France','Park Avenue','586','John Smith'),
('DoStore3Apple','Los Angeles','Germany','Main Street','161','David Williams'),
('HeheStore3Apple','New York','Canada','Park Avenue','142','Mary Brown'),
('HeheStoreGoogle','Chicago','France','Hollywood Boulevard','841','Peter Jones'),
('PhaleStore5Amazon','Houston','United Kingdom','Park Avenue','892','Peter Jones'),
('HihiStore5Amazon','Houston','France','Hollywood Boulevard','179','John Smith'),
('MongMoHouseMicrosoft','Los Angeles','France','Fifth Avenue','119','David Williams'),
('HihiStore2Apple','Phoenix','Canada','Wall Street','603','John Smith'),
('HeheStore4Amazon','Chicago','France','Fifth Avenue','722','Jane Doe'),
('VangStore2Google','Phoenix','Canada','Park Avenue','837','Mary Brown'),
('HaHaStore2Google','Los Angeles','Canada','Fifth Avenue','200','Jane Doe'),
('HihiStore7Walmart','Los Angeles','United States','Fifth Avenue','602','Peter Jones'),
('HaHaHouseApple','Phoenix','United States','Main Street','500','Jane Doe'),
('VangStore2Amazon','Los Angeles','Canada','Main Street','31','John Smith'),
('PhaleStore3Microsoft','Chicago','United States','Park Avenue','235','Peter Jones'),
('MongMoStore2Amazon','Phoenix','United Kingdom','Park Avenue','123','Mary Brown'),
('HihiStoreGoogle','Chicago','Germany','Park Avenue','523','Peter Jones'),
('TimStore7Google','Chicago','Germany','Fifth Avenue','677','Jane Doe'),
('PhaleStore3Amazon','Houston','France','Fifth Avenue','64','Jane Doe'),
('HaHaStore5Apple','Houston','France','Main Street','320','Mary Brown'),
('VangHouseMicrosoft','Phoenix','Germany','Fifth Avenue','761','David Williams'),
('VangStore5Amazon','Houston','Germany','Fifth Avenue','627','David Williams'),
('DoHomeApple','New York','United States','Park Avenue','305','David Williams'),
('HaHaStore4Google','Phoenix','United States','Park Avenue','360','John Smith'),
('VangStore3Microsoft','Los Angeles','United Kingdom','Wall Street','994','Mary Brown'),
('HaHaStore2Walmart','Los Angeles','Germany','Main Street','804','Jane Doe'),
('HeheStore7Walmart','Chicago','Canada','Park Avenue','69','Mary Brown'),
('HihiHomeGoogle','Houston','United States','Wall Street','697','Peter Jones'),
('TimStore4Google','New York','Germany','Wall Street','669','Jane Doe'),
('HaHaStore7Microsoft','Chicago','United States','Hollywood Boulevard','443','Peter Jones'),
('VangStore5Google','Phoenix','United Kingdom','Main Street','6','David Williams'),
('HihiHomeMicrosoft','New York','Germany','Wall Street','652','John Smith'),
('HihiStore5Apple','Los Angeles','United Kingdom','Hollywood Boulevard','221','John Smith'),
('HeheStore5Walmart','Phoenix','Germany','Park Avenue','15','John Smith'),
('MongMoStoreMicrosoft','Houston','Germany','Fifth Avenue','467','Peter Jones'),
('MongMoStore2Amazon','Chicago','United States','Fifth Avenue','248','John Smith'),
('HaHaStore3Amazon','Chicago','Canada','Main Street','167','David Williams'),
('VangHouseMicrosoft','Los Angeles','United Kingdom','Park Avenue','144','Peter Jones'),
('PhaleStore3Microsoft','Los Angeles','United Kingdom','Fifth Avenue','496','Jane Doe'),
('TimStore5Apple','Phoenix','United Kingdom','Fifth Avenue','397','Jane Doe'),
('HihiStore3Microsoft','Los Angeles','United States','Wall Street','338','Peter Jones'),
('HaHaStore7Google','Houston','United Kingdom','Park Avenue','142','Mary Brown'),
('HaHaStore5Apple','Los Angeles','France','Fifth Avenue','862','John Smith'),
('TimStore5Microsoft','Houston','France','Main Street','333','David Williams'),
('HaHaHomeGoogle','Houston','France','Wall Street','953','John Smith'),
('PhaleHouseGoogle','Los Angeles','Canada','Main Street','647','Jane Doe'),
('DoStore7Amazon','Houston','United Kingdom','Wall Street','593','David Williams'),
('MongMoStore7Google','Chicago','France','Hollywood Boulevard','976','Mary Brown'),
('TimStoreMicrosoft','Los Angeles','United Kingdom','Wall Street','590','Jane Doe'),
('HaHaStoreApple','Houston','United Kingdom','Wall Street','987','John Smith'),
('HeheStore4Apple','Phoenix','United Kingdom','Main Street','183','Peter Jones'),
('TimStore3Apple','Chicago','France','Wall Street','333','Peter Jones'),
('VangStoreMicrosoft','New York','France','Fifth Avenue','441','Jane Doe'),
('HaHaStore2Apple','New York','France','Fifth Avenue','759','John Smith'),
('HeheStore2Apple','Phoenix','Canada','Fifth Avenue','688','Peter Jones'),
('HihiHomeMicrosoft','Chicago','Germany','Main Street','754','Jane Doe'),
('PhaleStore7Amazon','Los Angeles','France','Park Avenue','878','David Williams'),
('DoStore5Amazon','Phoenix','Germany','Fifth Avenue','70','Peter Jones'),
('DoStoreGoogle','New York','United Kingdom','Main Street','458','Mary Brown'),
('HihiStore3Google','Phoenix','United States','Hollywood Boulevard','215','Peter Jones'),
('MongMoHouseApple','Chicago','United Kingdom','Wall Street','861','Jane Doe'),
('PhaleStore7Walmart','Chicago','France','Hollywood Boulevard','874','David Williams'),
('DoHouseAmazon','Houston','Germany','Park Avenue','41','Jane Doe'),
('VangStore5Apple','Phoenix','Canada','Fifth Avenue','588','Mary Brown'),
('HihiHomeAmazon','Houston','Germany','Hollywood Boulevard','721','Jane Doe'),
('HeheStore3Microsoft','Chicago','United Kingdom','Main Street','297','Mary Brown'),
('VangStore4Microsoft','Houston','United States','Hollywood Boulevard','688','Peter Jones'),
('MongMoStore7Google','Houston','France','Main Street','95','Peter Jones'),
('HaHaStore4Google','Chicago','Germany','Main Street','418','Jane Doe'),
('MongMoStore7Amazon','New York','France','Hollywood Boulevard','906','Mary Brown'),
('HaHaStore4Microsoft','Los Angeles','United States','Fifth Avenue','631','Jane Doe'),
('PhaleStoreApple','Chicago','United Kingdom','Hollywood Boulevard','326','Jane Doe'),
('DoStore5Google','New York','Canada','Park Avenue','846','Mary Brown'),
('HihiStore2Google','Chicago','United States','Park Avenue','364','David Williams'),
('VangStore2Apple','Houston','United Kingdom','Fifth Avenue','556','David Williams'),
('VangHouseGoogle','Chicago','Germany','Wall Street','784','John Smith'),
('HihiHouseGoogle','Los Angeles','Germany','Wall Street','31','Mary Brown'),
('HeheHomeWalmart','Phoenix','Canada','Wall Street','834','Mary Brown'),
('TimStore3Amazon','Los Angeles','United States','Main Street','819','David Williams'),
('DoStoreMicrosoft','Houston','Germany','Fifth Avenue','843','John Smith'),
('TimStore3Microsoft','Los Angeles','Germany','Wall Street','175','David Williams'),
('HihiStoreMicrosoft','Chicago','Germany','Wall Street','541','Mary Brown'),
('HeheHouseApple','Phoenix','United States','Fifth Avenue','85','Jane Doe'),
('TimStore2Google','Phoenix','France','Park Avenue','726','John Smith'),
('HaHaStoreMicrosoft','Los Angeles','United States','Wall Street','258','Peter Jones'),
('HeheStore7Amazon','Los Angeles','France','Wall Street','958','Peter Jones'),
('DoStore4Apple','Houston','Canada','Park Avenue','636','Jane Doe'),
('DoStore3Apple','Chicago','United States','Fifth Avenue','406','David Williams'),
('HaHaStore2Google','Chicago','United Kingdom','Main Street','837','Mary Brown'),
('TimStore5Apple','Phoenix','United Kingdom','Main Street','889','David Williams'),
('MongMoStore3Amazon','Chicago','United States','Main Street','780','Peter Jones'),
('MongMoHouseApple','Los Angeles','Germany','Wall Street','61','Mary Brown'),
('TimHomeAmazon','Houston','United States','Fifth Avenue','506','David Williams'),
('VangStore4Google','New York','Germany','Wall Street','558','Jane Doe'),
('MongMoStore4Microsoft','Phoenix','United States','Park Avenue','162','John Smith'),
('HaHaStore4Google','Los Angeles','Canada','Hollywood Boulevard','451','John Smith'),
('HihiStoreGoogle','Los Angeles','United States','Hollywood Boulevard','795','Peter Jones'),
('TimHouseAmazon','Chicago','Canada','Wall Street','602','David Williams'),
('HaHaHouseWalmart','Houston','France','Wall Street','150','David Williams'),
('HaHaStore3Apple','Houston','United States','Main Street','673','Jane Doe'),
('TimHomeApple','New York','France','Main Street','721','John Smith'),
('HaHaStore3Apple','Houston','France','Hollywood Boulevard','760','Mary Brown'),
('HaHaStore7Apple','Houston','Canada','Hollywood Boulevard','431','John Smith'),
('PhaleStore5Amazon','Phoenix','United Kingdom','Hollywood Boulevard','779','Mary Brown'),
('HaHaStore4Google','Chicago','Germany','Park Avenue','712','Peter Jones'),
('HihiHomeWalmart','Chicago','United States','Fifth Avenue','972','Jane Doe'),
('HaHaHouseGoogle','Chicago','Canada','Main Street','423','Jane Doe'),
('PhaleStore4Microsoft','Phoenix','United Kingdom','Fifth Avenue','455','Mary Brown'),
('MongMoHomeWalmart','Los Angeles','United States','Park Avenue','177','David Williams'),
('PhaleStore5Walmart','Phoenix','Germany','Fifth Avenue','204','David Williams'),
('HaHaStore5Microsoft','Houston','United Kingdom','Wall Street','686','Peter Jones'),
('TimHomeWalmart','Phoenix','Germany','Fifth Avenue','148','Mary Brown'),
('HihiStoreApple','Houston','France','Hollywood Boulevard','11','Jane Doe'),
('PhaleStoreGoogle','Houston','France','Wall Street','527','David Williams'),
('TimStore4Amazon','Phoenix','United States','Fifth Avenue','439','John Smith'),
('DoHomeGoogle','Phoenix','Canada','Fifth Avenue','99','Jane Doe'),
('TimStore3Amazon','Chicago','United Kingdom','Hollywood Boulevard','391','David Williams'),
('HihiStoreApple','Phoenix','United States','Fifth Avenue','702','Mary Brown'),
('PhaleStore3Amazon','Chicago','Germany','Wall Street','369','Jane Doe'),
('MongMoStore2Amazon','Phoenix','Germany','Park Avenue','480','Peter Jones'),
('PhaleStoreGoogle','Houston','Canada','Hollywood Boulevard','686','Peter Jones'),
('VangStore7Amazon','Los Angeles','France','Hollywood Boulevard','288','Mary Brown'),
('VangStore5Microsoft','Phoenix','United States','Wall Street','182','Jane Doe'),
('MongMoStore5Amazon','New York','Canada','Fifth Avenue','624','David Williams'),
('TimHomeMicrosoft','Los Angeles','Germany','Fifth Avenue','518','Peter Jones'),
('MongMoStore2Walmart','Los Angeles','United Kingdom','Fifth Avenue','735','John Smith'),
('DoStore7Apple','Houston','United States','Main Street','899','David Williams'),
('TimStore5Walmart','Houston','United States','Fifth Avenue','716','Jane Doe'),
('PhaleStore5Amazon','Chicago','Germany','Main Street','25','John Smith'),
('MongMoStore7Walmart','Los Angeles','Germany','Park Avenue','373','David Williams'),
('HihiStore5Amazon','New York','United States','Fifth Avenue','869','Jane Doe'),
('PhaleHouseWalmart','Chicago','Canada','Main Street','368','Peter Jones'),
('HihiHouseWalmart','Los Angeles','France','Hollywood Boulevard','283','Mary Brown'),
('DoStore5Microsoft','Phoenix','France','Main Street','934','John Smith'),
('MongMoHomeApple','Los Angeles','France','Wall Street','279','John Smith'),
('HihiHomeWalmart','New York','United States','Main Street','840','Peter Jones'),
('HeheStore4Apple','Los Angeles','United Kingdom','Park Avenue','551','Jane Doe'),
('HaHaStore2Apple','Los Angeles','United States','Park Avenue','752','Peter Jones'),
('MongMoStore5Google','Houston','Germany','Main Street','323','Peter Jones'),
('HeheStore7Amazon','Phoenix','France','Wall Street','387','Mary Brown'),
('MongMoStore4Apple','Chicago','France','Main Street','464','Mary Brown'),
('DoStoreApple','Houston','France','Main Street','951','Mary Brown'),
('DoHouseApple','Phoenix','Germany','Park Avenue','514','John Smith'),
('DoHomeWalmart','Phoenix','France','Main Street','732','Mary Brown'),
('DoStore7Google','Los Angeles','United States','Fifth Avenue','845','Mary Brown'),
('VangHomeGoogle','Houston','Canada','Wall Street','424','David Williams'),
('VangHouseAmazon','Chicago','United States','Park Avenue','377','John Smith'),
('HeheStore7Google','Los Angeles','United Kingdom','Fifth Avenue','71','Mary Brown'),
('TimStore3Walmart','Los Angeles','United Kingdom','Hollywood Boulevard','337','Mary Brown'),
('HaHaStoreMicrosoft','New York','France','Main Street','648','David Williams'),
('DoStoreMicrosoft','Los Angeles','United States','Fifth Avenue','47','John Smith'),
('MongMoStore3Google','Houston','Germany','Fifth Avenue','251','Jane Doe'),
('VangStore3Amazon','Los Angeles','France','Hollywood Boulevard','983','Mary Brown'),
('TimStore4Google','Chicago','France','Fifth Avenue','583','John Smith'),
('MongMoHouseAmazon','New York','Canada','Fifth Avenue','966','Mary Brown'),
('TimHomeMicrosoft','New York','United Kingdom','Park Avenue','617','David Williams'),
('HaHaHomeMicrosoft','New York','United States','Fifth Avenue','534','Jane Doe'),
('HeheStore2Walmart','New York','Germany','Wall Street','570','Mary Brown'),
('PhaleStore3Google','Houston','Germany','Fifth Avenue','852','Peter Jones'),
('DoStore7Amazon','Houston','United Kingdom','Wall Street','165','Jane Doe'),
('TimStore3Apple','Phoenix','United States','Hollywood Boulevard','925','Peter Jones'),
('MongMoStore4Microsoft','New York','United States','Main Street','904','David Williams'),
('VangStore7Google','Houston','Germany','Fifth Avenue','190','Peter Jones'),
('VangStore2Walmart','Chicago','France','Hollywood Boulevard','766','Peter Jones'),
('HihiStore5Amazon','Los Angeles','United Kingdom','Wall Street','168','David Williams'),
('MongMoStoreWalmart','Chicago','Germany','Hollywood Boulevard','152','Mary Brown'),
('HeheStoreApple','New York','United Kingdom','Park Avenue','471','Jane Doe'),
('HihiStore4Walmart','New York','Germany','Hollywood Boulevard','813','David Williams'),
('PhaleStore5Microsoft','Chicago','United Kingdom','Main Street','678','Jane Doe'),
('PhaleStore2Amazon','Los Angeles','France','Wall Street','783','David Williams'),
('MongMoStore2Amazon','Chicago','France','Wall Street','721','Mary Brown'),
('HihiHouseGoogle','Chicago','United Kingdom','Fifth Avenue','224','Jane Doe'),
('TimHouseWalmart','New York','United States','Fifth Avenue','804','David Williams'),
('TimStore3Apple','New York','Germany','Fifth Avenue','99','Mary Brown'),
('VangHomeAmazon','New York','Germany','Fifth Avenue','331','Jane Doe'),
('TimStore2Amazon','Los Angeles','Germany','Main Street','939','John Smith'),
('HihiStore4Amazon','Los Angeles','Canada','Main Street','281','John Smith'),
('HeheStore2Walmart','Chicago','France','Wall Street','851','John Smith'),
('PhaleHomeGoogle','Los Angeles','France','Hollywood Boulevard','22','David Williams'),
('HaHaStore7Amazon','Houston','Canada','Hollywood Boulevard','865','Jane Doe'),
('VangStoreGoogle','Chicago','United Kingdom','Park Avenue','240','Jane Doe'),
('DoStore4Apple','Houston','France','Hollywood Boulevard','506','Jane Doe'),
('TimStore2Google','New York','Canada','Main Street','948','Peter Jones'),
('TimStore2Microsoft','Phoenix','United States','Park Avenue','236','Peter Jones'),
('HihiHomeGoogle','Houston','France','Fifth Avenue','173','David Williams'),
('PhaleStore5Apple','Houston','France','Fifth Avenue','508','John Smith'),
('HihiStoreAmazon','Chicago','United States','Hollywood Boulevard','828','Jane Doe'),
('HeheStoreGoogle','Phoenix','Canada','Hollywood Boulevard','879','Peter Jones'),
('TimStore7Apple','Chicago','Germany','Wall Street','959','Peter Jones'),
('MongMoStore2Apple','Chicago','France','Wall Street','832','Mary Brown'),
('MongMoStore3Google','Los Angeles','United States','Hollywood Boulevard','62','Mary Brown'),
('TimHouseWalmart','Los Angeles','United States','Main Street','67','Mary Brown'),
('HaHaStore5Google','Chicago','France','Hollywood Boulevard','771','Peter Jones'),
('MongMoHouseWalmart','Houston','France','Park Avenue','477','Mary Brown'),
('MongMoStore7Microsoft','Houston','United Kingdom','Wall Street','676','Mary Brown'),
('HihiHouseWalmart','Los Angeles','United States','Wall Street','427','John Smith'),
('PhaleHomeMicrosoft','New York','United States','Hollywood Boulevard','273','Peter Jones'),
('MongMoHomeAmazon','Los Angeles','United Kingdom','Wall Street','62','Jane Doe'),
('HihiHouseGoogle','Houston','Canada','Hollywood Boulevard','784','John Smith'),
('DoStore7Google','Los Angeles','Germany','Park Avenue','706','Peter Jones'),
('HaHaHomeGoogle','Phoenix','France','Fifth Avenue','238','Jane Doe'),
('HihiHomeGoogle','Phoenix','France','Wall Street','244','David Williams'),
('MongMoStore5Walmart','Los Angeles','France','Wall Street','237','Peter Jones'),
('VangStore2Microsoft','New York','Germany','Fifth Avenue','933','David Williams'),
('VangHouseWalmart','Chicago','United States','Wall Street','200','Mary Brown'),
('DoStore3Apple','Phoenix','Canada','Main Street','156','John Smith'),
('VangStore3Amazon','Phoenix','France','Hollywood Boulevard','480','Mary Brown'),
('TimStore4Amazon','Phoenix','United Kingdom','Main Street','305','Mary Brown'),
('HihiHouseMicrosoft','Chicago','United States','Wall Street','594','David Williams'),
('MongMoStore4Apple','Los Angeles','Germany','Fifth Avenue','973','Peter Jones'),
('PhaleStoreWalmart','New York','Germany','Main Street','627','John Smith'),
('DoStore2Amazon','Chicago','France','Main Street','493','John Smith'),
('HihiStore3Microsoft','Houston','United Kingdom','Main Street','83','Jane Doe'),
('DoHouseApple','Chicago','United States','Main Street','931','John Smith'),
('HeheHouseGoogle','Los Angeles','United States','Park Avenue','924','Mary Brown'),
('HihiStore3Amazon','Los Angeles','Germany','Hollywood Boulevard','313','John Smith'),
('HihiStore2Amazon','Houston','France','Main Street','223','Peter Jones'),
('HihiStore2Amazon','New York','Germany','Fifth Avenue','740','Peter Jones'),
('PhaleHouseMicrosoft','New York','Canada','Main Street','214','Jane Doe'),
('PhaleStoreGoogle','Chicago','Canada','Park Avenue','246','Peter Jones'),
('VangStore3Amazon','Houston','United States','Main Street','770','Peter Jones'),
('MongMoStore4Google','Phoenix','United States','Wall Street','671','David Williams'),
('PhaleStore5Walmart','Los Angeles','Germany','Park Avenue','579','Jane Doe'),
('PhaleStore3Google','Chicago','Canada','Hollywood Boulevard','371','Mary Brown'),
('TimHomeWalmart','Los Angeles','United Kingdom','Main Street','150','Peter Jones'),
('TimStoreApple','Chicago','Canada','Park Avenue','840','Mary Brown'),
('MongMoStore3Amazon','New York','United Kingdom','Wall Street','141','Jane Doe'),
('MongMoHomeApple','New York','France','Hollywood Boulevard','273','Peter Jones'),
('PhaleStore5Apple','Houston','United States','Fifth Avenue','508','John Smith'),
('PhaleStore3Amazon','New York','United States','Fifth Avenue','151','Jane Doe'),
('HihiStore3Amazon','Phoenix','Germany','Wall Street','247','Mary Brown'),
('HeheStore5Amazon','Chicago','United Kingdom','Park Avenue','367','Peter Jones'),
('DoStore2Amazon','Los Angeles','Canada','Fifth Avenue','726','David Williams'),
('HihiStore2Amazon','Los Angeles','United Kingdom','Main Street','298','Jane Doe'),
('HaHaStore7Apple','Los Angeles','United States','Hollywood Boulevard','942','David Williams'),
('TimStore7Walmart','New York','United Kingdom','Park Avenue','502','David Williams'),
('MongMoStoreAmazon','Houston','Germany','Hollywood Boulevard','585','Peter Jones'),
('HeheStore7Amazon','Houston','Germany','Fifth Avenue','981','Peter Jones'),
('HeheHomeGoogle','Chicago','United Kingdom','Park Avenue','803','John Smith'),
('HaHaStore4Apple','Los Angeles','Canada','Hollywood Boulevard','516','Jane Doe'),
('MongMoStoreMicrosoft','Chicago','Canada','Main Street','661','Jane Doe'),
('HeheStore2Walmart','Houston','United States','Hollywood Boulevard','536','Peter Jones'),
('HeheHomeMicrosoft','Los Angeles','United Kingdom','Hollywood Boulevard','720','Peter Jones'),
('VangHomeMicrosoft','Chicago','Germany','Main Street','823','Mary Brown'),
('HaHaHomeWalmart','New York','Germany','Park Avenue','8','Jane Doe'),
('HihiHomeGoogle','New York','United Kingdom','Wall Street','263','Mary Brown'),
('HaHaStore5Amazon','Los Angeles','Germany','Fifth Avenue','223','John Smith'),
('HaHaStore2Apple','Houston','Canada','Main Street','354','Mary Brown'),
('PhaleHomeWalmart','Phoenix','France','Fifth Avenue','447','Peter Jones'),
('HihiStore2Microsoft','Chicago','Germany','Park Avenue','288','John Smith'),
('DoHouseApple','Los Angeles','France','Hollywood Boulevard','240','Mary Brown'),
('HeheStore2Apple','Phoenix','Canada','Park Avenue','627','John Smith'),
('MongMoStore2Amazon','Houston','France','Park Avenue','554','Jane Doe'),
('HihiStore7Walmart','Houston','Germany','Fifth Avenue','587','Peter Jones'),
('VangStore4Walmart','Phoenix','United Kingdom','Fifth Avenue','242','Peter Jones'),
('VangStore4Google','Chicago','Germany','Wall Street','35','Jane Doe'),
('HaHaStore4Walmart','New York','France','Fifth Avenue','470','Peter Jones'),
('HeheStore7Amazon','Houston','United States','Wall Street','948','John Smith'),
('HihiStore5Apple','Phoenix','United States','Hollywood Boulevard','893','Jane Doe'),
('DoStore5Google','New York','Germany','Park Avenue','706','David Williams'),
('VangHomeAmazon','Phoenix','Germany','Main Street','590','Mary Brown'),
('HihiStore3Walmart','Chicago','France','Fifth Avenue','324','John Smith'),
('TimStore4Walmart','Houston','France','Hollywood Boulevard','492','Mary Brown'),
('HaHaStore4Google','Houston','Germany','Fifth Avenue','853','Peter Jones'),
('VangStore7Microsoft','New York','United Kingdom','Hollywood Boulevard','319','David Williams'),
('HaHaHouseGoogle','New York','United States','Main Street','865','David Williams'),
('MongMoStore7Walmart','Chicago','France','Park Avenue','731','Peter Jones'),
('HeheStore3Walmart','Phoenix','Canada','Wall Street','405','Mary Brown'),
('VangHomeAmazon','Chicago','Germany','Fifth Avenue','770','Peter Jones'),
('PhaleStore2Apple','New York','France','Wall Street','692','David Williams'),
('DoStore5Walmart','New York','United States','Wall Street','873','David Williams'),
('HaHaStoreMicrosoft','Phoenix','Canada','Fifth Avenue','776','Peter Jones'),
('HeheStore7Google','Houston','Canada','Wall Street','553','David Williams'),
('HaHaStore5Google','Houston','France','Hollywood Boulevard','698','Mary Brown'),
('PhaleStore5Walmart','Houston','Canada','Hollywood Boulevard','7','David Williams'),
('HihiStore2Walmart','Houston','United States','Main Street','464','Mary Brown'),
('HeheStore2Walmart','Chicago','France','Wall Street','67','John Smith'),
('TimHomeWalmart','Phoenix','United Kingdom','Hollywood Boulevard','744','Peter Jones'),
('HihiStore3Google','Houston','Canada','Hollywood Boulevard','794','Jane Doe'),
('MongMoStore7Amazon','Chicago','United States','Main Street','772','Peter Jones'),
('MongMoStore4Amazon','Phoenix','Germany','Park Avenue','105','David Williams'),
('HeheStore4Walmart','Chicago','United Kingdom','Wall Street','792','John Smith'),
('MongMoStoreMicrosoft','New York','United Kingdom','Hollywood Boulevard','671','David Williams'),
('PhaleStore4Microsoft','Phoenix','France','Fifth Avenue','922','David Williams'),
('HihiStore4Microsoft','Chicago','United Kingdom','Hollywood Boulevard','402','Mary Brown'),
('DoStore4Apple','Houston','France','Wall Street','978','Jane Doe'),
('DoHomeAmazon','Los Angeles','United Kingdom','Hollywood Boulevard','672','David Williams'),
('HihiStore4Amazon','Los Angeles','United Kingdom','Park Avenue','969','Mary Brown'),
('HihiStore3Microsoft','Houston','United Kingdom','Main Street','511','Mary Brown'),
('PhaleStore7Walmart','Houston','Germany','Park Avenue','819','David Williams'),
('HihiStoreApple','Phoenix','United States','Park Avenue','340','David Williams'),
('HeheHomeGoogle','Phoenix','France','Hollywood Boulevard','735','Jane Doe'),
('MongMoStoreAmazon','Chicago','Germany','Main Street','934','Peter Jones'),
('HeheHomeMicrosoft','Los Angeles','Canada','Main Street','592','Jane Doe'),
('TimStore7Microsoft','Houston','United States','Fifth Avenue','296','John Smith'),
('DoHomeGoogle','Chicago','France','Park Avenue','548','David Williams'),
('VangStore5Amazon','Los Angeles','United Kingdom','Fifth Avenue','464','Jane Doe'),
('TimStore2Amazon','Houston','Canada','Park Avenue','419','Jane Doe'),
('PhaleStore5Amazon','New York','France','Main Street','565','Jane Doe'),
('MongMoHomeMicrosoft','Los Angeles','Canada','Wall Street','734','John Smith'),
('DoStore2Walmart','Phoenix','Germany','Fifth Avenue','902','Jane Doe'),
('DoHouseMicrosoft','New York','United Kingdom','Fifth Avenue','991','John Smith'),
('TimStore5Amazon','Houston','France','Hollywood Boulevard','454','Jane Doe'),
('TimStore2Amazon','Chicago','Canada','Wall Street','237','Mary Brown'),
('DoStoreWalmart','Phoenix','Canada','Fifth Avenue','677','Peter Jones'),
('MongMoStoreAmazon','Los Angeles','United States','Park Avenue','3','David Williams'),
('MongMoStore4Apple','Houston','United Kingdom','Park Avenue','293','John Smith'),
('TimStore3Microsoft','Los Angeles','United States','Park Avenue','973','Jane Doe'),
('HeheHouseAmazon','Los Angeles','Canada','Wall Street','965','John Smith'),
('HihiStore5Walmart','Los Angeles','United States','Fifth Avenue','971','John Smith'),
('VangStore5Google','Houston','Canada','Hollywood Boulevard','578','David Williams'),
('HeheStore2Microsoft','Houston','United States','Main Street','855','Peter Jones'),
('VangHouseMicrosoft','Houston','United States','Hollywood Boulevard','420','David Williams'),
('TimStore7Apple','New York','Germany','Wall Street','207','John Smith'),
('TimStore5Walmart','Chicago','United States','Hollywood Boulevard','821','Jane Doe'),
('HaHaStore4Amazon','Phoenix','France','Main Street','759','David Williams'),
('PhaleStore2Microsoft','Chicago','United States','Park Avenue','485','Mary Brown'),
('HaHaStoreAmazon','Chicago','Canada','Park Avenue','511','Peter Jones'),
('MongMoHomeAmazon','Phoenix','United Kingdom','Hollywood Boulevard','567','Peter Jones'),
('MongMoStore3Amazon','Phoenix','France','Fifth Avenue','88','Mary Brown'),
('HihiStore4Walmart','Los Angeles','Canada','Park Avenue','560','Peter Jones'),
('VangStore5Walmart','Los Angeles','France','Main Street','83','Peter Jones'),
('HihiStore3Apple','Los Angeles','Germany','Main Street','51','David Williams'),
('DoStore3Walmart','Houston','United Kingdom','Main Street','428','David Williams'),
('HaHaStore5Amazon','Phoenix','Germany','Fifth Avenue','579','Jane Doe'),
('TimStore3Apple','Chicago','United States','Fifth Avenue','209','Jane Doe'),
('DoHomeWalmart','Los Angeles','Canada','Wall Street','371','Mary Brown'),
('HeheStore5Microsoft','Phoenix','Germany','Fifth Avenue','15','David Williams'),
('HeheHouseGoogle','Los Angeles','Germany','Wall Street','107','David Williams'),
('DoHomeWalmart','New York','United States','Main Street','941','Peter Jones'),
('TimStore2Walmart','New York','United Kingdom','Main Street','200','John Smith'),
('HaHaStoreAmazon','Chicago','Germany','Fifth Avenue','12','John Smith'),
('PhaleStore3Microsoft','Los Angeles','Canada','Wall Street','390','Peter Jones'),
('MongMoStore2Apple','Houston','France','Wall Street','819','Mary Brown'),
('DoStore5Amazon','Los Angeles','United Kingdom','Fifth Avenue','735','Peter Jones'),
('HeheStoreGoogle','New York','Canada','Main Street','586','David Williams'),
('PhaleStore7Microsoft','Houston','France','Hollywood Boulevard','570','David Williams'),
('DoStoreApple','Houston','Canada','Hollywood Boulevard','22','David Williams'),
('TimStore3Microsoft','Chicago','Germany','Park Avenue','256','Mary Brown'),
('MongMoStore4Amazon','New York','United States','Park Avenue','836','Peter Jones'),
('VangStore3Walmart','Chicago','United States','Main Street','133','John Smith'),
('VangStore3Microsoft','Chicago','United Kingdom','Main Street','231','John Smith'),
('MongMoStore2Google','Houston','France','Hollywood Boulevard','834','Mary Brown'),
('TimStoreGoogle','Houston','Canada','Park Avenue','283','David Williams'),
('DoHomeApple','New York','United Kingdom','Park Avenue','759','Jane Doe'),
('HihiStore2Apple','Houston','United Kingdom','Wall Street','205','David Williams'),
('PhaleStore7Google','Houston','United Kingdom','Hollywood Boulevard','256','David Williams'),
('TimStore5Google','New York','France','Wall Street','228','John Smith'),
('HeheStore7Microsoft','New York','Germany','Main Street','334','Peter Jones'),
('PhaleStore2Apple','New York','France','Main Street','487','Peter Jones'),
('MongMoStore4Microsoft','Phoenix','United States','Fifth Avenue','362','David Williams'),
('HaHaStore5Walmart','Chicago','United States','Hollywood Boulevard','389','Peter Jones'),
('HihiStore3Microsoft','Phoenix','United Kingdom','Main Street','240','Mary Brown'),
('TimStore3Walmart','Phoenix','Germany','Park Avenue','223','Mary Brown'),
('HaHaStore7Apple','Houston','Canada','Main Street','120','Peter Jones'),
('HeheStore7Walmart','Phoenix','United Kingdom','Fifth Avenue','961','Jane Doe'),
('HaHaStoreMicrosoft','Houston','Germany','Wall Street','4','Jane Doe'),
('HaHaStore2Apple','Los Angeles','United Kingdom','Wall Street','786','David Williams'),
('DoStore5Microsoft','New York','United Kingdom','Hollywood Boulevard','838','John Smith'),
('HihiHomeMicrosoft','Chicago','United States','Fifth Avenue','546','John Smith'),
('TimStore5Google','Los Angeles','United Kingdom','Wall Street','175','Mary Brown'),
('VangStore2Apple','Houston','Canada','Hollywood Boulevard','651','David Williams'),
('TimHomeGoogle','Los Angeles','United States','Park Avenue','500','John Smith'),
('VangStore4Apple','Houston','United States','Fifth Avenue','545','John Smith'),
('TimStore3Apple','New York','United States','Park Avenue','526','John Smith'),
('TimHouseApple','Phoenix','France','Hollywood Boulevard','477','John Smith'),
('HeheStoreMicrosoft','New York','Germany','Wall Street','769','Mary Brown'),
('HeheHouseAmazon','Phoenix','Canada','Fifth Avenue','631','Mary Brown'),
('VangStore5Microsoft','Phoenix','Canada','Hollywood Boulevard','463','Peter Jones'),
('PhaleStore3Apple','Los Angeles','Canada','Fifth Avenue','382','David Williams'),
('HihiHomeGoogle','Houston','United Kingdom','Main Street','802','John Smith'),
('HaHaStore5Google','Los Angeles','France','Main Street','195','Jane Doe'),
('VangStore5Apple','Houston','Canada','Wall Street','45','Jane Doe'),
('DoStoreMicrosoft','Chicago','United States','Park Avenue','762','John Smith'),
('MongMoStore4Amazon','New York','Canada','Main Street','826','Mary Brown'),
('HihiHouseWalmart','Los Angeles','United Kingdom','Main Street','151','John Smith'),
('HaHaStore3Apple','New York','United States','Park Avenue','93','John Smith'),
('MongMoStore3Walmart','Chicago','United Kingdom','Hollywood Boulevard','775','Peter Jones'),
('TimHomeMicrosoft','New York','United States','Main Street','737','Peter Jones'),
('VangStore5Microsoft','Houston','Canada','Fifth Avenue','940','Mary Brown'),
('MongMoStore2Apple','New York','Germany','Fifth Avenue','659','Peter Jones'),
('HeheStore2Microsoft','Los Angeles','France','Wall Street','305','John Smith'),
('TimStore4Amazon','Houston','France','Hollywood Boulevard','153','Peter Jones'),
('VangStore3Microsoft','New York','Canada','Main Street','831','Mary Brown'),
('TimStore3Walmart','New York','France','Fifth Avenue','597','Jane Doe'),
('HeheStore7Google','New York','United States','Wall Street','485','Jane Doe'),
('VangStore4Amazon','Chicago','France','Main Street','245','David Williams'),
('PhaleStore5Microsoft','Los Angeles','Canada','Main Street','605','Jane Doe'),
('HaHaStore3Google','Chicago','United States','Wall Street','623','David Williams'),
('HihiStore3Google','Houston','France','Main Street','599','Mary Brown'),
('VangStore4Microsoft','Chicago','Germany','Main Street','839','Peter Jones'),
('PhaleStore5Amazon','New York','United States','Wall Street','226','David Williams'),
('MongMoStore3Apple','Houston','France','Park Avenue','962','Mary Brown'),
('VangStoreApple','New York','Germany','Hollywood Boulevard','695','John Smith'),
('VangStore7Google','Chicago','France','Park Avenue','654','David Williams'),
('HihiStore7Walmart','Los Angeles','United Kingdom','Hollywood Boulevard','441','Jane Doe'),
('HaHaStore2Google','Los Angeles','France','Fifth Avenue','254','Peter Jones'),
('HihiHouseGoogle','Chicago','France','Main Street','289','John Smith'),
('PhaleStore7Microsoft','Phoenix','United Kingdom','Park Avenue','176','David Williams'),
('TimHouseWalmart','Houston','Germany','Main Street','157','Jane Doe'),
('PhaleStore7Apple','New York','Canada','Park Avenue','553','David Williams'),
('VangStore2Microsoft','Los Angeles','United States','Main Street','772','Peter Jones'),
('TimStoreMicrosoft','Houston','Canada','Main Street','601','David Williams'),
('TimStoreAmazon','Houston','Canada','Wall Street','81','Jane Doe'),
('MongMoStore3Walmart','Chicago','United States','Fifth Avenue','208','Jane Doe'),
('HeheStore2Google','Phoenix','Canada','Wall Street','805','Mary Brown'),
('TimStore7Microsoft','Chicago','Canada','Park Avenue','63','David Williams'),
('MongMoStore5Microsoft','Houston','Canada','Park Avenue','90','Mary Brown'),
('TimStore7Google','Houston','Canada','Hollywood Boulevard','500','Jane Doe'),
('HaHaHouseAmazon','Chicago','Canada','Main Street','672','Peter Jones'),
('VangStore4Apple','Phoenix','France','Hollywood Boulevard','627','Jane Doe'),
('PhaleStore3Walmart','New York','France','Hollywood Boulevard','733','Mary Brown'),
('TimStore5Google','New York','France','Park Avenue','79','Jane Doe'),
('HaHaHouseWalmart','New York','United States','Fifth Avenue','38','David Williams'),
('TimStore7Microsoft','Chicago','United Kingdom','Main Street','284','John Smith'),
('HihiStore3Microsoft','Chicago','France','Fifth Avenue','735','Jane Doe'),
('TimHouseWalmart','Phoenix','United Kingdom','Hollywood Boulevard','747','Jane Doe'),
('VangStore5Microsoft','Phoenix','United Kingdom','Park Avenue','683','Peter Jones'),
('PhaleStoreMicrosoft','Los Angeles','Germany','Fifth Avenue','573','David Williams'),
('HihiStore7Google','Houston','France','Park Avenue','992','Jane Doe'),
('MongMoStore2Google','Phoenix','United Kingdom','Wall Street','258','Mary Brown'),
('VangStoreWalmart','Los Angeles','United States','Hollywood Boulevard','508','Jane Doe'),
('DoHouseAmazon','New York','United States','Fifth Avenue','708','John Smith'),
('VangHomeAmazon','Houston','United States','Wall Street','742','Jane Doe'),
('DoStore7Amazon','Chicago','United States','Main Street','78','Jane Doe'),
('PhaleStoreAmazon','Houston','United Kingdom','Main Street','948','John Smith'),
('VangStore7Apple','Los Angeles','United States','Main Street','310','David Williams'),
('VangHouseMicrosoft','New York','France','Main Street','701','Jane Doe'),
('TimStore4Microsoft','Phoenix','United States','Fifth Avenue','731','John Smith'),
('DoHomeGoogle','Los Angeles','United States','Park Avenue','49','Mary Brown'),
('PhaleHouseWalmart','Los Angeles','Canada','Fifth Avenue','604','Jane Doe'),
('HihiHouseGoogle','Chicago','United States','Main Street','696','Mary Brown'),
('HihiStore7Walmart','New York','France','Park Avenue','950','Mary Brown'),
('TimHomeWalmart','Phoenix','United States','Wall Street','837','John Smith'),
('HeheStore3Microsoft','Chicago','Canada','Wall Street','261','Peter Jones'),
('MongMoStore4Microsoft','Los Angeles','France','Fifth Avenue','248','David Williams'),
('HaHaStore3Apple','New York','United States','Wall Street','647','David Williams'),
('DoStoreWalmart','New York','United Kingdom','Park Avenue','452','David Williams'),
('PhaleStore4Microsoft','Chicago','Germany','Main Street','739','David Williams'),
('VangStore2Amazon','Los Angeles','France','Main Street','244','Peter Jones'),
('PhaleHouseMicrosoft','Chicago','Canada','Wall Street','820','John Smith'),
('DoStore2Microsoft','New York','United States','Fifth Avenue','432','Peter Jones'),
('DoHomeApple','Los Angeles','United States','Hollywood Boulevard','815','David Williams'),
('TimStore3Walmart','Phoenix','United States','Hollywood Boulevard','923','Mary Brown'),
('DoStoreApple','Houston','Germany','Fifth Avenue','551','Mary Brown'),
('TimStore5Walmart','Los Angeles','France','Wall Street','941','John Smith'),
('HihiHouseAmazon','Chicago','Canada','Hollywood Boulevard','708','John Smith'),
('HeheStore7Walmart','Los Angeles','United Kingdom','Hollywood Boulevard','704','Mary Brown'),
('HeheStore3Microsoft','Phoenix','Germany','Fifth Avenue','409','Mary Brown'),
('HaHaHouseMicrosoft','Houston','United States','Main Street','424','Peter Jones'),
('PhaleStore4Microsoft','Los Angeles','Germany','Wall Street','927','Jane Doe'),
('VangStore3Google','Houston','United Kingdom','Wall Street','539','Mary Brown'),
('PhaleStore3Walmart','New York','Canada','Hollywood Boulevard','972','Mary Brown'),
('VangHouseAmazon','Chicago','France','Main Street','719','Jane Doe'),
('PhaleStore2Apple','New York','Germany','Hollywood Boulevard','55','Mary Brown'),
('DoHomeApple','Houston','Germany','Fifth Avenue','503','John Smith'),
('TimStore7Walmart','New York','Germany','Wall Street','760','David Williams'),
('VangStore5Walmart','Los Angeles','France','Fifth Avenue','193','John Smith'),
('PhaleStore4Apple','Houston','Germany','Hollywood Boulevard','720','Jane Doe'),
('HaHaStore2Google','Phoenix','United States','Main Street','169','John Smith'),
('PhaleHomeMicrosoft','Chicago','United Kingdom','Fifth Avenue','39','David Williams'),
('PhaleStore4Walmart','New York','Germany','Wall Street','652','Mary Brown'),
('MongMoHomeGoogle','Phoenix','United States','Wall Street','754','David Williams'),
('DoHomeWalmart','Houston','United States','Fifth Avenue','892','Mary Brown'),
('PhaleHomeWalmart','Phoenix','Germany','Main Street','109','Mary Brown'),
('VangStore2Walmart','Chicago','Canada','Main Street','156','Peter Jones'),
('PhaleStore7Apple','Chicago','France','Hollywood Boulevard','80','David Williams'),
('MongMoStore2Google','Chicago','Canada','Park Avenue','773','John Smith'),
('VangHouseMicrosoft','Chicago','United States','Main Street','451','John Smith'),
('HihiHomeGoogle','Chicago','United Kingdom','Fifth Avenue','438','John Smith'),
('HihiStore5Walmart','Houston','France','Park Avenue','46','Mary Brown'),
('MongMoStore7Microsoft','Los Angeles','Germany','Fifth Avenue','912','David Williams'),
('MongMoStore3Amazon','Chicago','United States','Main Street','151','Jane Doe'),
('HeheHouseApple','Chicago','Canada','Hollywood Boulevard','454','Peter Jones'),
('HihiStore5Amazon','Chicago','Germany','Wall Street','364','Peter Jones'),
('TimHomeAmazon','New York','United Kingdom','Main Street','773','John Smith'),
('HeheHomeMicrosoft','Phoenix','United Kingdom','Wall Street','969','Jane Doe'),
('DoStore4Walmart','Phoenix','Canada','Park Avenue','784','David Williams'),
('DoHouseWalmart','Phoenix','United Kingdom','Main Street','164','David Williams'),
('TimStore4Google','Houston','United States','Main Street','808','David Williams'),
('MongMoStoreGoogle','Los Angeles','France','Wall Street','892','Jane Doe'),
('DoStore3Microsoft','New York','United States','Park Avenue','724','David Williams'),
('DoStore2Amazon','Los Angeles','United Kingdom','Hollywood Boulevard','231','Jane Doe'),
('TimHouseMicrosoft','Phoenix','United Kingdom','Park Avenue','956','David Williams'),
('DoStore4Microsoft','New York','Germany','Hollywood Boulevard','934','Jane Doe'),
('HihiStore4Google','Chicago','United States','Park Avenue','945','Jane Doe'),
('HihiStore2Google','Los Angeles','United States','Main Street','494','David Williams'),
('TimStore2Walmart','Houston','United States','Park Avenue','286','Peter Jones'),
('PhaleHomeWalmart','New York','United States','Main Street','754','Peter Jones'),
('VangStore5Microsoft','New York','France','Main Street','534','Peter Jones'),
('PhaleStore3Walmart','Chicago','Germany','Fifth Avenue','840','John Smith'),
('HeheHomeWalmart','New York','United Kingdom','Main Street','979','David Williams'),
('HaHaHomeMicrosoft','Houston','United States','Park Avenue','507','Mary Brown'),
('HaHaStoreMicrosoft','Houston','France','Hollywood Boulevard','778','John Smith'),
('HihiStore4Google','Chicago','United Kingdom','Wall Street','905','John Smith'),
('VangStore7Apple','New York','France','Fifth Avenue','358','David Williams'),
('TimHomeAmazon','Los Angeles','United Kingdom','Wall Street','387','John Smith'),
('PhaleStore7Amazon','Phoenix','Canada','Wall Street','36','John Smith'),
('DoStore3Walmart','Houston','France','Wall Street','905','Mary Brown'),
('VangHomeApple','Chicago','Canada','Wall Street','267','John Smith'),
('PhaleStore5Apple','Houston','France','Wall Street','191','David Williams'),
('DoStore7Apple','New York','United Kingdom','Park Avenue','394','John Smith'),
('TimHouseWalmart','Chicago','United States','Park Avenue','663','Jane Doe'),
('DoStoreMicrosoft','Phoenix','France','Fifth Avenue','548','Jane Doe'),
('TimStore4Walmart','New York','United States','Park Avenue','392','Jane Doe'),
('HaHaHomeWalmart','Chicago','United Kingdom','Hollywood Boulevard','849','David Williams'),
('HaHaHouseAmazon','Los Angeles','United States','Main Street','810','John Smith'),
('MongMoStore4Amazon','Los Angeles','United States','Park Avenue','468','Peter Jones'),
('DoStore2Walmart','New York','United Kingdom','Hollywood Boulevard','430','Mary Brown'),
('HihiHouseApple','New York','United Kingdom','Fifth Avenue','996','David Williams'),
('TimStore4Amazon','New York','Canada','Hollywood Boulevard','329','Mary Brown'),
('VangHomeGoogle','Phoenix','United States','Park Avenue','892','Jane Doe'),
('TimHomeAmazon','Phoenix','France','Fifth Avenue','179','John Smith'),
('MongMoStoreApple','Phoenix','France','Hollywood Boulevard','824','David Williams'),
('HeheStoreAmazon','Los Angeles','United States','Main Street','948','David Williams'),
('VangHomeMicrosoft','Los Angeles','United Kingdom','Main Street','590','John Smith'),
('MongMoStore4Walmart','Los Angeles','United Kingdom','Hollywood Boulevard','853','Jane Doe'),
('VangHouseMicrosoft','Los Angeles','Germany','Fifth Avenue','703','Peter Jones'),
('HeheStore5Google','Houston','France','Fifth Avenue','383','Peter Jones'),
('DoHomeWalmart','Phoenix','Germany','Hollywood Boulevard','362','Jane Doe'),
('HaHaStore5Apple','Los Angeles','United States','Fifth Avenue','724','Mary Brown'),
('DoHouseWalmart','Phoenix','United Kingdom','Wall Street','793','Mary Brown'),
('PhaleStoreMicrosoft','New York','United States','Hollywood Boulevard','168','Mary Brown'),
('HeheStore4Apple','Chicago','Canada','Fifth Avenue','358','John Smith'),
('HeheHouseMicrosoft','Phoenix','France','Park Avenue','542','Peter Jones'),
('VangStore7Walmart','New York','United Kingdom','Wall Street','674','David Williams'),
('HeheStore5Apple','Chicago','France','Wall Street','994','Jane Doe'),
('VangStoreMicrosoft','Houston','United Kingdom','Main Street','145','Mary Brown'),
('HihiHomeWalmart','Phoenix','France','Main Street','90','David Williams'),
('TimStore2Google','Houston','Germany','Hollywood Boulevard','395','Mary Brown'),
('PhaleStore2Apple','New York','Canada','Wall Street','602','Mary Brown'),
('HaHaHomeGoogle','Phoenix','Germany','Park Avenue','979','Peter Jones'),
('HaHaStore3Apple','Phoenix','France','Fifth Avenue','315','Mary Brown'),
('VangStore5Walmart','Los Angeles','United Kingdom','Park Avenue','667','Peter Jones'),
('PhaleStore2Microsoft','Phoenix','United States','Wall Street','844','Mary Brown'),
('MongMoStore4Amazon','Chicago','Germany','Wall Street','211','John Smith'),
('HihiStore4Microsoft','Los Angeles','United Kingdom','Hollywood Boulevard','993','Peter Jones'),
('VangStore5Walmart','Los Angeles','Germany','Park Avenue','61','David Williams'),
('DoStore5Apple','Houston','United Kingdom','Hollywood Boulevard','191','David Williams'),
('TimStore2Amazon','Chicago','Canada','Park Avenue','701','Peter Jones'),
('MongMoStore4Walmart','Phoenix','United States','Main Street','55','Peter Jones'),
('PhaleStore5Walmart','Chicago','France','Hollywood Boulevard','91','Jane Doe'),
('HeheStore5Amazon','Phoenix','United Kingdom','Main Street','166','John Smith'),
('VangStore7Google','Chicago','Germany','Park Avenue','197','Peter Jones'),
('DoHouseGoogle','New York','Canada','Fifth Avenue','958','David Williams'),
('TimStore7Walmart','Houston','United States','Fifth Avenue','48','Jane Doe'),
('VangStore7Google','Chicago','Germany','Main Street','168','Jane Doe'),
('TimStore3Google','New York','France','Main Street','892','David Williams'),
('HaHaHouseMicrosoft','Los Angeles','United Kingdom','Hollywood Boulevard','38','Peter Jones'),
('DoStore2Google','Houston','United Kingdom','Hollywood Boulevard','241','David Williams'),
('MongMoStore2Apple','Houston','United States','Fifth Avenue','177','David Williams'),
('PhaleStoreMicrosoft','Los Angeles','United States','Hollywood Boulevard','213','David Williams'),
('HeheStore4Walmart','Los Angeles','Germany','Hollywood Boulevard','334','John Smith'),
('TimHomeWalmart','Los Angeles','United States','Park Avenue','287','Peter Jones'),
('DoStoreGoogle','Phoenix','France','Wall Street','599','Peter Jones'),
('DoStore3Amazon','New York','Canada','Wall Street','763','John Smith'),
('VangHouseWalmart','Chicago','United Kingdom','Main Street','660','David Williams'),
('HaHaStoreGoogle','New York','Germany','Park Avenue','334','John Smith'),
('MongMoStore2Apple','Houston','Germany','Main Street','624','John Smith'),
('HeheStore7Microsoft','Houston','France','Park Avenue','661','David Williams'),
('DoHouseApple','Los Angeles','Canada','Wall Street','434','David Williams'),
('TimStore3Google','Chicago','United Kingdom','Park Avenue','113','Jane Doe'),
('HaHaStoreGoogle','Chicago','United Kingdom','Hollywood Boulevard','520','Peter Jones'),
('HaHaStore4Walmart','Los Angeles','Germany','Park Avenue','154','Mary Brown'),
('HeheStoreMicrosoft','Houston','Germany','Main Street','719','Mary Brown'),
('TimHouseApple','Phoenix','Germany','Main Street','350','Mary Brown'),
('VangStore3Google','Los Angeles','United States','Wall Street','12','John Smith'),
('HaHaHomeApple','Phoenix','United States','Park Avenue','850','Mary Brown'),
('DoStore5Apple','Houston','United Kingdom','Park Avenue','968','John Smith'),
('HeheHouseGoogle','Houston','France','Hollywood Boulevard','682','John Smith'),
('HaHaStoreWalmart','Houston','France','Main Street','1','John Smith'),
('HeheStore2Apple','Los Angeles','Canada','Wall Street','336','Jane Doe'),
('HaHaStore2Apple','Los Angeles','France','Hollywood Boulevard','855','John Smith'),
('HihiHouseWalmart','Los Angeles','United Kingdom','Wall Street','867','John Smith'),
('HaHaStore5Microsoft','Los Angeles','Canada','Park Avenue','190','Jane Doe'),
('VangStoreMicrosoft','Los Angeles','France','Main Street','805','David Williams'),
('VangStoreGoogle','Phoenix','Canada','Wall Street','196','John Smith'),
('DoHomeGoogle','Houston','Canada','Park Avenue','229','John Smith'),
('HihiStore4Walmart','Houston','United States','Fifth Avenue','611','Jane Doe'),
('HaHaHomeApple','New York','Germany','Hollywood Boulevard','829','Jane Doe'),
('DoStore4Walmart','Phoenix','Germany','Hollywood Boulevard','20','John Smith'),
('PhaleHomeAmazon','Phoenix','Germany','Main Street','743','Mary Brown'),
('HaHaStore2Google','Houston','United States','Fifth Avenue','632','Peter Jones'),
('VangStore3Apple','Phoenix','Canada','Wall Street','369','David Williams'),
('VangStore2Google','Los Angeles','France','Park Avenue','206','John Smith'),
('DoStore5Walmart','Houston','Canada','Hollywood Boulevard','515','Peter Jones'),
('PhaleStoreAmazon','Houston','United States','Park Avenue','401','David Williams'),
('PhaleStore7Apple','Phoenix','United Kingdom','Wall Street','158','Mary Brown'),
('PhaleStore5Apple','Los Angeles','France','Wall Street','490','Jane Doe'),
('MongMoStore4Microsoft','Phoenix','Germany','Wall Street','556','John Smith'),
('DoStore2Walmart','Houston','France','Fifth Avenue','83','David Williams'),
('VangStore7Google','New York','United Kingdom','Fifth Avenue','839','Peter Jones'),
('MongMoStoreMicrosoft','New York','France','Park Avenue','734','David Williams'),
('DoStoreGoogle','Phoenix','United States','Park Avenue','533','Jane Doe'),
('HaHaStore7Walmart','Phoenix','United Kingdom','Hollywood Boulevard','244','Mary Brown'),
('TimStore5Microsoft','Phoenix','France','Fifth Avenue','480','Mary Brown'),
('TimStore4Walmart','Chicago','Canada','Hollywood Boulevard','614','Jane Doe'),
('MongMoStore4Walmart','Los Angeles','Germany','Hollywood Boulevard','29','John Smith'),
('HeheStore2Amazon','Houston','Germany','Wall Street','802','Peter Jones'),
('DoStoreWalmart','Los Angeles','United States','Hollywood Boulevard','216','David Williams'),
('DoStore4Apple','Los Angeles','United States','Park Avenue','699','Mary Brown'),
('VangStore4Microsoft','New York','United Kingdom','Fifth Avenue','596','Peter Jones'),
('VangHouseGoogle','Phoenix','United Kingdom','Main Street','323','Jane Doe'),
('HaHaStore5Apple','Chicago','Germany','Fifth Avenue','310','David Williams'),
('TimStoreGoogle','Houston','Canada','Fifth Avenue','915','Peter Jones'),
('DoStoreMicrosoft','Houston','United Kingdom','Wall Street','177','Peter Jones'),
('PhaleStore3Amazon','Phoenix','United States','Park Avenue','455','Mary Brown'),
('MongMoStore3Walmart','New York','Germany','Park Avenue','491','Mary Brown'),
('TimStoreMicrosoft','Chicago','Germany','Park Avenue','39','Peter Jones'),
('HaHaStore5Google','Houston','United Kingdom','Park Avenue','450','Mary Brown'),
('TimHomeMicrosoft','Houston','France','Park Avenue','321','Peter Jones'),
('VangStoreAmazon','Chicago','United Kingdom','Park Avenue','863','Peter Jones'),
('TimHomeMicrosoft','Houston','Germany','Fifth Avenue','877','David Williams'),
('DoStore3Google','Phoenix','Germany','Main Street','923','Peter Jones'),
('HaHaStore5Microsoft','New York','United Kingdom','Hollywood Boulevard','383','Jane Doe'),
('HeheStoreWalmart','Los Angeles','Germany','Wall Street','591','David Williams'),
('HihiStore2Microsoft','New York','United States','Park Avenue','369','Jane Doe'),
('PhaleStoreApple','Los Angeles','United States','Park Avenue','511','Peter Jones'),
('TimStore2Amazon','Phoenix','France','Park Avenue','945','Mary Brown'),
('MongMoStore3Amazon','New York','United States','Wall Street','153','Jane Doe'),
('VangStore7Walmart','Los Angeles','Canada','Main Street','727','John Smith'),
('HihiStore3Google','Chicago','United Kingdom','Park Avenue','253','Peter Jones'),
('PhaleStoreMicrosoft','Los Angeles','United States','Main Street','636','David Williams'),
('HaHaHouseAmazon','Chicago','Canada','Park Avenue','504','Mary Brown'),
('PhaleStore3Apple','New York','France','Fifth Avenue','114','Jane Doe'),
('HeheStore4Walmart','Chicago','France','Main Street','628','John Smith'),
('HeheHomeMicrosoft','Chicago','France','Hollywood Boulevard','986','David Williams'),
('DoStore5Google','Phoenix','France','Wall Street','107','Jane Doe'),
('DoStore4Apple','Houston','United Kingdom','Park Avenue','530','John Smith'),
('HeheStore2Google','Los Angeles','France','Hollywood Boulevard','365','John Smith'),
('DoHouseMicrosoft','Chicago','Canada','Fifth Avenue','938','John Smith'),
('HihiStoreGoogle','New York','Canada','Main Street','294','Mary Brown'),
('VangStore2Amazon','Houston','Canada','Main Street','679','David Williams'),
('MongMoHouseGoogle','Los Angeles','United Kingdom','Park Avenue','231','David Williams'),
('HihiStoreAmazon','Phoenix','Canada','Wall Street','646','Peter Jones'),
('MongMoStoreAmazon','Houston','United States','Fifth Avenue','501','Mary Brown'),
('PhaleHouseWalmart','New York','United Kingdom','Park Avenue','466','Peter Jones'),
('TimStoreGoogle','Chicago','Canada','Park Avenue','768','Mary Brown'),
('HeheStore2Walmart','Houston','France','Hollywood Boulevard','890','Peter Jones'),
('PhaleStore3Walmart','Houston','Canada','Park Avenue','630','Peter Jones'),
('DoStore4Walmart','Phoenix','United Kingdom','Hollywood Boulevard','577','John Smith'),
('HihiStore2Apple','Phoenix','France','Hollywood Boulevard','550','John Smith'),
('PhaleStore7Apple','Los Angeles','United States','Fifth Avenue','917','John Smith'),
('HaHaStore7Walmart','New York','Canada','Main Street','993','Jane Doe'),
('VangStoreAmazon','Los Angeles','France','Main Street','61','David Williams'),
('MongMoStore4Google','Phoenix','United States','Fifth Avenue','297','Jane Doe'),
('HihiStoreApple','Phoenix','Germany','Hollywood Boulevard','106','Peter Jones'),
('HaHaHomeGoogle','Houston','Germany','Hollywood Boulevard','560','Jane Doe'),
('HaHaStore4Walmart','Phoenix','United Kingdom','Park Avenue','108','David Williams'),
('PhaleStore2Google','New York','United Kingdom','Hollywood Boulevard','687','David Williams'),
('PhaleHouseGoogle','Phoenix','Canada','Main Street','841','David Williams'),
('PhaleStore3Microsoft','New York','United States','Hollywood Boulevard','50','Mary Brown'),
('PhaleStore5Microsoft','Houston','France','Main Street','414','David Williams'),
('HaHaStoreGoogle','Houston','France','Wall Street','943','Peter Jones'),
('HeheStoreWalmart','Los Angeles','United Kingdom','Park Avenue','251','Mary Brown'),
('HihiStoreApple','Los Angeles','France','Main Street','750','Jane Doe'),
('MongMoStore7Microsoft','New York','France','Wall Street','737','David Williams'),
('DoStore5Walmart','Houston','Germany','Fifth Avenue','755','David Williams'),
('HaHaStore3Google','Los Angeles','United States','Wall Street','931','Mary Brown'),
('HaHaStore7Amazon','Chicago','Germany','Fifth Avenue','735','Mary Brown'),
('DoStore3Amazon','Houston','United States','Park Avenue','294','Mary Brown'),
('HeheHomeWalmart','Los Angeles','France','Park Avenue','133','Jane Doe'),
('VangStore2Microsoft','Los Angeles','France','Main Street','358','Peter Jones'),
('DoStore7Walmart','Phoenix','Canada','Wall Street','29','John Smith'),
('PhaleStore7Amazon','Phoenix','Germany','Fifth Avenue','399','Peter Jones'),
('MongMoStore4Google','Houston','United Kingdom','Main Street','377','Jane Doe'),
('DoStoreWalmart','Phoenix','Germany','Fifth Avenue','355','John Smith'),
('MongMoStore2Walmart','Los Angeles','United States','Main Street','332','Mary Brown'),
('HihiHouseWalmart','New York','Canada','Fifth Avenue','760','Jane Doe'),
('HeheHomeApple','Phoenix','Germany','Hollywood Boulevard','192','Jane Doe'),
('HeheHouseWalmart','Phoenix','Canada','Park Avenue','207','John Smith'),
('HihiHouseAmazon','Phoenix','France','Hollywood Boulevard','690','Jane Doe'),
('MongMoHouseMicrosoft','Chicago','Canada','Wall Street','445','Jane Doe'),
('HaHaStore5Google','Phoenix','Germany','Fifth Avenue','169','Mary Brown'),
('MongMoHomeGoogle','Chicago','Germany','Fifth Avenue','795','Peter Jones'),
('HeheStore7Google','Los Angeles','Canada','Wall Street','196','Mary Brown'),
('MongMoHouseGoogle','Los Angeles','Germany','Hollywood Boulevard','310','Jane Doe'),
('HeheHomeAmazon','Los Angeles','United Kingdom','Park Avenue','292','John Smith'),
('TimStoreGoogle','Los Angeles','United States','Park Avenue','442','John Smith'),
('HihiStore7Amazon','New York','France','Hollywood Boulevard','534','Mary Brown'),
('VangStore3Walmart','Houston','United Kingdom','Fifth Avenue','586','Peter Jones'),
('VangStore5Apple','Chicago','Canada','Hollywood Boulevard','434','David Williams'),
('TimStore4Apple','Houston','France','Hollywood Boulevard','331','Jane Doe'),
('VangStore5Amazon','Los Angeles','France','Main Street','802','David Williams'),
('TimStore5Microsoft','New York','Canada','Fifth Avenue','182','David Williams'),
('PhaleStoreAmazon','Houston','France','Hollywood Boulevard','441','Peter Jones'),
('TimStore4Google','New York','Germany','Hollywood Boulevard','973','Mary Brown'),
('TimHomeMicrosoft','New York','Germany','Fifth Avenue','810','John Smith'),
('MongMoHouseMicrosoft','Houston','France','Fifth Avenue','334','John Smith'),
('VangStore2Walmart','New York','United Kingdom','Hollywood Boulevard','752','Jane Doe'),
('TimStore2Apple','New York','France','Wall Street','540','John Smith'),
('HihiStore2Amazon','Los Angeles','Germany','Park Avenue','426','Mary Brown'),
('TimStore3Apple','Chicago','Germany','Park Avenue','276','Mary Brown'),
('MongMoStoreGoogle','Houston','France','Park Avenue','742','Mary Brown'),
('HihiStoreMicrosoft','New York','France','Fifth Avenue','206','Peter Jones'),
('VangStore5Google','Los Angeles','France','Fifth Avenue','799','David Williams'),
('HihiHouseGoogle','Chicago','Germany','Fifth Avenue','700','Peter Jones'),
('MongMoStore4Apple','Phoenix','United States','Main Street','500','John Smith'),
('DoStoreWalmart','Houston','United States','Wall Street','611','John Smith'),
('MongMoStore3Microsoft','Phoenix','France','Fifth Avenue','968','Peter Jones'),
('PhaleStore5Apple','Phoenix','United Kingdom','Hollywood Boulevard','111','Peter Jones'),
('VangStore5Apple','Los Angeles','United States','Wall Street','321','John Smith'),
('DoStore5Apple','Los Angeles','France','Hollywood Boulevard','443','Jane Doe'),
('HeheStore3Google','Los Angeles','United Kingdom','Hollywood Boulevard','152','Jane Doe'),
('HaHaHouseGoogle','Houston','United Kingdom','Hollywood Boulevard','355','Jane Doe'),
('VangStore4Amazon','Los Angeles','Canada','Hollywood Boulevard','918','David Williams'),
('VangHouseApple','Chicago','Germany','Main Street','91','Jane Doe'),
('PhaleHouseMicrosoft','Los Angeles','France','Hollywood Boulevard','51','Peter Jones'),
('VangStore2Amazon','Los Angeles','France','Park Avenue','160','Mary Brown'),
('MongMoStoreAmazon','Chicago','United Kingdom','Park Avenue','23','John Smith'),
('DoStore4Walmart','Los Angeles','United Kingdom','Fifth Avenue','340','Jane Doe'),
('HaHaStore3Google','Houston','Germany','Wall Street','506','John Smith'),
('TimStore7Walmart','Houston','France','Main Street','750','Mary Brown'),
('DoStoreMicrosoft','New York','United States','Fifth Avenue','839','Peter Jones'),
('HeheStore5Amazon','Los Angeles','United Kingdom','Hollywood Boulevard','610','John Smith'),
('MongMoStore4Apple','Houston','France','Wall Street','583','Peter Jones'),
('DoHouseApple','Los Angeles','France','Main Street','65','Jane Doe'),
('VangStore7Google','Houston','Canada','Hollywood Boulevard','58','Peter Jones'),
('VangStore4Walmart','Chicago','Canada','Hollywood Boulevard','932','John Smith'),
('VangStore3Microsoft','Chicago','United States','Park Avenue','677','Jane Doe'),
('TimStore7Microsoft','New York','Canada','Hollywood Boulevard','374','Jane Doe'),
('PhaleStore3Google','Los Angeles','United Kingdom','Wall Street','56','Jane Doe'),
('DoHouseMicrosoft','New York','United Kingdom','Main Street','696','Peter Jones'),
('TimStoreApple','New York','United Kingdom','Hollywood Boulevard','168','Jane Doe'),
('TimStore5Walmart','New York','United States','Main Street','434','David Williams'),
('PhaleStore5Apple','Phoenix','United States','Park Avenue','265','David Williams'),
('VangHomeApple','Los Angeles','United States','Hollywood Boulevard','36','David Williams'),
('HaHaHouseAmazon','New York','United Kingdom','Wall Street','733','David Williams'),
('HeheStore2Microsoft','Chicago','Canada','Fifth Avenue','862','Peter Jones'),
('HihiStore7Google','Los Angeles','France','Wall Street','202','Peter Jones'),
('HaHaStore7Walmart','Phoenix','United States','Park Avenue','690','David Williams'),
('DoStore3Apple','New York','Germany','Park Avenue','472','Jane Doe'),
('TimStore7Apple','New York','France','Main Street','913','Peter Jones'),
('HeheStoreGoogle','New York','United Kingdom','Main Street','300','David Williams'),
('PhaleStore4Microsoft','New York','United States','Hollywood Boulevard','190','Jane Doe'),
('PhaleHouseAmazon','Chicago','France','Wall Street','349','Peter Jones'),
('DoStore7Amazon','Houston','United States','Wall Street','64','John Smith'),
('TimStore7Amazon','Phoenix','United States','Hollywood Boulevard','818','John Smith'),
('HaHaStore5Walmart','Los Angeles','Canada','Fifth Avenue','109','Jane Doe')